### ISSUE TITLE
Model object: co.cesarnorena.pushapp.model.Contact is not registered with a Database. Did you forget an annotation?

### ISSUE THREAD

**Issue by cesarnorena** [Raizlabs/DBFlow#1032]
DBFlow Version: 4.0.0-beta1
Issue Kind: Bug

Description: 

I'm getting a error trying to save on Table Contact (I'm using Kotlin)`contact?.save()`. I saw the previous problems but nothing solves the bug (I have instant run disable)

```
<application
        android:name=".PushApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
```

```
@Database(name = PushDatabase.NAME, version = PushDatabase.VERSION)
class PushDatabase {

    companion object {
        const val NAME: String = "PushDatabase"
        const val VERSION: Int = 1
    }
}
```

```
class PushApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        FlowManager.init(FlowConfig.Builder(this).build())
    }
}
```

```
@Table(database = PushDatabase::class)
class Contact : BaseModel() {

    @SerializedName("direction")
    @Column
    var direction: String? = null

    @SerializedName("phone")
    @Column
    var phone: String? = null
}
```

```
FATAL EXCEPTION: main
                                                                   Process: co.cesarnorena.pushapp, PID: 22276
                                                                   com.raizlabs.android.dbflow.structure.InvalidDBConfiguration: Model object: co.cesarnorena.pushapp.model.Contact is not registered with a Database. Did you forget an annotation?
                                                                       at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseForTable(FlowManager.java:107)
                                                                       at com.raizlabs.android.dbflow.config.FlowManager.getModelAdapter(FlowManager.java:318)
                                                                       at co.cesarnorena.pushapp.database.DatabaseTransaction$Companion.fastTransaction(DatabaseTransaction.kt:11)
                                                                       at co.cesarnorena.pushapp.database.DatabaseTransaction$Companion.fastTransaction$default(DatabaseTransaction.kt:9)
                                                                       at co.cesarnorena.pushapp.server.ConfigurationResponse.save(ConfigurationResponse.kt:26)
                                                                       at co.cesarnorena.pushapp.activity.SplashActivity$getConfigurations$1.onResponse(SplashActivity.kt:50)
                                                                       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by trevjonez** [comment]
Try adding the generated database holder class literal to the config builder. I believe if initialized incorrectly this is the same error message.

**Comment by cesarnorena** [comment]
@trevjonez ¿Can you give me an example please?

**Comment by trevjonez** [comment]
```java
FlowManager.init(new FlowConfig.Builder(this)
           .addDatabaseHolder(YourDatabaseGeneratedDatabaseHolder.class)
           .openDatabasesOnInit(true) //Triggers migrations asap
           .build());
```

**Comment by agrosner** [comment]
that should do it. :) also is increment compilation on? there is a problem with that in Kotlin. I think Android fixed the issue, but still might be present in Kotlin.

**Comment by GrishinSergey** [comment]
I have the same issue. I used Kotlin and DBFlow 4.1.2. The saving goes well (I've seen the saved data), but I cann't select them
My select is looks like this:
`(select from Book_Table::class).list`
