### ISSUE TITLE
SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor

### ISSUE THREAD

**Issue by ovidiucp** [Raizlabs/DBFlow#1050]
DBFlow Version: 3.1.1 used with SQLCipher
Issue Kind (Bug, Question, Feature): Bug

I use an async transaction to do some processing in a background thread, and create a bunch of objects to be inserted in the database. The code runs just fine but it looks like some of the cursors used internally are not being closed properly. I get the dreaded 

```
W/SQLiteCompiledSql: Releasing statement in a finalizer. 
Please ensure that you explicitly call close() on your cursor
```

Here is the code:

```
        DatabaseDefinition database = FlowManager.getDatabase(AppDatabase.class);
        Transaction transaction = database.beginTransactionAsync(new ITransaction() {
            @Override
            public void execute(DatabaseWrapper databaseWrapper) {
                    // Some processing here
                    resort.save(databaseWrapper);
            }
        }).success(new Transaction.Success() {
            @Override
            public void onSuccess(Transaction transaction) {
               // ...
            }
        }).error(new Transaction.Error() {
            @Override
            public void onError(Transaction transaction, Throwable error) {
               // ...
            }
        }).build();
        transaction.execute();
```

The complete stacktrace being shown below. The insert operation that is mentioned in the stacktrace happens in the `save()` operation in my code.

The problem is that even though the initial work is done in a worker thread, the cursor release happens during garbage collection on the main thread, in the `net.sqlcipher.database.SQLiteCompiledSql.finalize()` method. This causes all sorts of unwanted slowdowns and bad user experience, even though it doesn't cause a crash.

Any thoughts on what's going on and what I can do to close the cursors earlier?

```
W/SQLiteCompiledSql: Releasing statement in a finalizer. 
Please ensure that you explicitly call close() on your cursor: 
INSERT INTO `available_resorts`(`name`,`search_name`,`resort_id`,`resort_uid`,`resort_version`,`size

net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here

at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:103)
at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1541)
at com.raizlabs.dbflow.android.sqlcipher.SQLCipherDatabase.compileStatement(SQLCipherDatabase.java:57)
at com.raizlabs.android.dbflow.structure.ModelAdapter.getInsertStatement(ModelAdapter.java:65)
at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:44)
at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:108)
at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:56)
at com.jollyturns.ResortsManager$4.execute(ResortsManager.java:352)
at com.raizlabs.android.dbflow.config.DatabaseDefinition.executeTransaction(DatabaseDefinition.java:233)
at com.raizlabs.android.dbflow.structure.database.transaction.Transaction.executeSync(Transaction.java:115)
at com.raizlabs.android.dbflow.structure.database.transaction.DefaultTransactionQueue.run(DefaultTransactionQueue.java:53)
```

**Comment by ovidiucp** [comment]
Any thoughts on this issue?

I'm getting closer to releasing the app on Android, and I still haven't found an answer to this. Random finalizers warnings like the ones above seem to pop-up everywhere, which makes me question the completeness of the data in the database.

Even though I'm close to the release, I'd be willing to upgrade to 4.0alpha2 if there's a guarantee that it fixes the problem.

Thanks!

**Comment by ovidiucp** [comment]
Another issue I observed today that's due to cursors being released in finalizers. This time it caused the app to crash, not cool.

In my app I have a background-running service that writes into the database. It looks to me that the service wanted to release a cursor in a finalizer. This operation wanted to acquire a lock, which was already acquired, causing a timeout.

Since the cursors are not exposed through the API, there doesn't seem to be a way to close them when you're done with them.

@agrosner, @trevjonez: What's the best way to release cursors earlier than in a finalizer?

```
Fatal Exception: java.util.concurrent.TimeoutException: net.sqlcipher.database.SQLiteCompiledSql.finalize() timed out after 10 seconds
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:813)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:846)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1175)
       at java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:195)
       at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:256)
       at net.sqlcipher.database.SQLiteDatabase.lock(SQLiteDatabase.java:505)
       at net.sqlcipher.database.SQLiteCompiledSql.releaseSqlStatement(SQLiteCompiledSql.java:106)
       at net.sqlcipher.database.SQLiteCompiledSql.finalize(SQLiteCompiledSql.java:152)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
       at java.lang.Thread.run(Thread.java:841)
```

I looked at the other threads to see what they were doing.

```
AsyncTask #5
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:813)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:846)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1175)
       at java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:195)
       at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:256)
       at net.sqlcipher.database.SQLiteDatabase.lock(SQLiteDatabase.java:505)
       at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1536)
       at com.raizlabs.dbflow.android.sqlcipher.SQLCipherDatabase.compileStatement(SQLCipherDatabase.java:57)
       at com.raizlabs.android.dbflow.sql.SqlUtils.longForQuery(SqlUtils.java:205)
       at com.raizlabs.android.dbflow.sql.language.Where.count(Where.java:207)
       at com.jollyturns.model.SkiDay_Adapter.exists(SkiDay_Adapter.java:256)
       at com.jollyturns.model.SkiDay_Adapter.exists(SkiDay_Adapter.java:22)
       at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:50)
       at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:40)
       at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:103)
       at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:51)
       at com.jollyturns.statistics.StatisticsManager.updateStatisticsWithLocation(StatisticsManager.java:205)
       at com.jollyturns.location.LocationService.publishLocation(LocationService.java:282)
       at com.jollyturns.location.LocationService$2.doInBackground(LocationService.java:255)
       at com.jollyturns.location.LocationService$2.doInBackground(LocationService.java:251)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

The DBFlow Transaction Queue:

```
DBFlow Transaction Queue
       at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:40)
       at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:103)
       at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:51)
       at com.jollyturns.model.SkiSeason.skiSeasonFromProto(SkiSeason.java:120)
       at com.jollyturns.model.SkiSeason.skiSeasonsFromProto(SkiSeason.java:72)
       at com.jollyturns.model.Person.personFromProtoUser(Person.java:184)
       at com.jollyturns.model.Person.personFromProtoUser(Person.java:125)
       at com.jollyturns.BaseFragment$3$3.execute(BaseFragment.java:300)
       at com.raizlabs.android.dbflow.config.DatabaseDefinition.executeTransaction(DatabaseDefinition.java:233)
       at com.raizlabs.android.dbflow.structure.database.transaction.Transaction.executeSync(Transaction.java:115)
       at com.raizlabs.android.dbflow.structure.database.transaction.DefaultTransactionQueue.run(DefaultTransactionQueue.java:53)
```

The main thread also seems to be blocked in a lock:

```
main
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:813)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:846)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1175)
       at java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:195)
       at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:256)
       at net.sqlcipher.database.SQLiteDatabase.lock(SQLiteDatabase.java:505)
       at net.sqlcipher.database.SQLiteCursor.<init>(SQLiteCursor.java:225)
       at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:53)
       at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1772)
       at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1737)
       at com.raizlabs.dbflow.android.sqlcipher.SQLCipherDatabase.rawQuery(SQLCipherDatabase.java:66)
       at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:56)
       at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:51)
       at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:35)
       at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:62)
       at com.raizlabs.android.dbflow.sql.language.Where.querySingle(Where.java:285)
       at com.jollyturns.model.Person.personWithIdentifier(Person.java:196)
       at com.jollyturns.BaseFragment$3$2.onSuccess(BaseFragment.java:307)
       at com.raizlabs.android.dbflow.structure.database.transaction.Transaction$1.run(Transaction.java:126)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5001)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by trevjonez** [comment]
I am not familiar with that part of the API. 

Have you tried saving via the save queue rather than doing your own transactions? I typically always try to use the save queue for any save operations since I can have  many threads trying to write to the DB at one time. In my case I increase the save queue buffer size by a significant amount and flush at the end of each operation.

**Comment by ovidiucp** [comment]
Thanks for the quick reply! I'm not familiar with save queues. Can you point me to the right place?

**Comment by trevjonez** [comment]
https://github.com/Raizlabs/DBFlow/issues/996

There is a snippet in this issue. Also worth noting the add all signature change in v4

**Comment by ovidiucp** [comment]
I saw the first crash in production because of this issue. Releasing statements in a finalizer cause a timeout, which killed the process. It happened on a SM-G800F device.

```
Exception java.util.concurrent.TimeoutException: net.sqlcipher.database.SQLiteCompiledSql.finalize() timed out after 10 seconds
java.lang.Daemons$Daemon.isRunning (Daemons.java:82)
java.lang.Daemons$FinalizerDaemon.run (Daemons.java:186)
java.lang.Thread.run (Thread.java:818)
```

**Comment by agrosner** [comment]
To provide fastest writes, we cache the INSERT statements, which seems to be causing this issue. Call any operation on a `Model` using the `DatabaseWrapper` as a param, and it will not cache it and close it manually for you.
```java

 DatabaseDefinition database = FlowManager.getDatabase(AppDatabase.class);
        Transaction transaction = database.beginTransactionAsync(new ITransaction() {
            @Override
            public void execute(DatabaseWrapper databaseWrapper) {
                    // Some processing here
                    resort.save(databaseWrapper);
            }
        }).success(new Transaction.Success() {
            @Override
            public void onSuccess(Transaction transaction) {
               // ...
            }
        }).error(new Transaction.Error() {
            @Override
            public void onError(Transaction transaction, Throwable error) {
               // ...
            }
        }).build();
        transaction.execute();

```

That snippet should close the `SQLiteStatement` at least 3.0.0 and higher. Any save/insert ops that you dont use the wrapper for?
