### ISSUE TITLE
.delete() causes exception "expected 1 row from this query but query returned no data."

### ISSUE THREAD

**Issue by mdolnik** [Raizlabs/DBFlow#1071]
DBFlow Version: 4.0.0-beta2
Issue Kind (Bug)

Description: 
Every time I call delete on an object it seems to successfully delete the row from the db, yet it calls an SQLiteDoneException.

```
E/FlowLog: android.database.sqlite.SQLiteDoneException: expected 1 row from this query but query returned no data. check the query: DELETE FROM `MyCollection` WHERE (`id`=1)
               at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:142)
               at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.simpleQueryForLong(AndroidDatabaseStatement.java:67)
               at com.raizlabs.android.dbflow.sql.SqlUtils.longForQuery(SqlUtils.java:204)
               at com.raizlabs.android.dbflow.sql.language.BaseQueriable.count(BaseQueriable.java:44)
               at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.delete(ModelSaver.java:122)
               at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.delete(ModelSaver.java:113)
               at com.raizlabs.android.dbflow.structure.ModelAdapter.delete(ModelAdapter.java:168)
               at com.raizlabs.android.dbflow.structure.BaseModel.delete(BaseModel.java:73)
               at com.dolnik.myappname.MainActivity.onClick(MainActivity.java:68)
               at android.view.View.performClick(View.java:3534)
               at android.view.View$PerformClick.run(View.java:14263)
               at android.os.Handler.handleCallback(Handler.java:605)
               at android.os.Handler.dispatchMessage(Handler.java:92)
               at android.os.Looper.loop(Looper.java:137)
               at android.app.ActivityThread.main(ActivityThread.java:4441)
               at java.lang.reflect.Method.invokeNative(Native Method)
               at java.lang.reflect.Method.invoke(Method.java:511)
               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
               at dalvik.system.NativeStart.main(Native Method)
```

Class:
```
@Table(database = DbFlow.class)
public class MyCollection extends BaseModel {
    @Column @NotNull @PrimaryKey(autoincrement = true)
    int id;

    @Column
    String name;

    @Column
    Date dateCreated;

    @Column
    Date dateModified;
}
```

Both of the following code snippets cause the exception:
```
Date date = new Date();
MyCollection collection = new MyCollection();
collection.name = "My Name";
collection.dateCreated = date;
collection.dateModified = date;
collection.save();

collection.delete();
```
```
List<MyCollection> collectionList = SQLite.select()
        .from(MyCollection.class)
        .queryList();
for (MyCollection collection : collectionList) {
    collection.delete();
}
```

I know these may not be the best examples for deleting items, but I tried to simplify the use case

**Comment by agrosner** [comment]
The issue was I was calling `count()` instead of `executeUpdateDelete()`. Thank you for finding this. 
```
 boolean successful = SQLite.delete(modelAdapter.getModelClass())
                .where(modelAdapter.getPrimaryConditionClause(model))
                .executeUpdateDelete(wrapper) != 0;
```

**Comment by agrosner** [comment]
fixed in `develop`.

**Comment by DreierF** [comment]
@agrosner When will beta 3 get published?
