### ISSUE TITLE
FileNotFoundException MyDatabase.db first time running app or after clearing data

### ISSUE THREAD

**Issue by simernes** [Raizlabs/DBFlow#109]
Whenever I install my app project for the first time, or I have cleaned data I get a FileNotFoundException for the database file. The app doesn't actually crash, I just get an error saying the file doesn't exist in the Log, and then the app just keeps going. Next time I start the app it doesn't happen, I guess because the file has been created. So it's not critical but a little worrying. Is there some way to initate other than FlowManager.init? Didn't see anything in the doc.

 java.io.FileNotFoundException: MyDatabase.db
            at android.content.res.AssetManager.openAsset(Native Method)
            at android.content.res.AssetManager.open(AssetManager.java:313)
            at android.content.res.AssetManager.open(AssetManager.java:287)
            at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper.movePrepackagedDB(FlowSQLiteOpenHelper.java:227)
            at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper.<init>(FlowSQLiteOpenHelper.java:55)
            at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getHelper(BaseDatabaseDefinition.java:92)
            at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:98)
            at com.raizlabs.android.dbflow.sql.SqlUtils.hasData(SqlUtils.java:246)
            at com.raizlabs.android.dbflow.sql.language.Where.hasData(Where.java:414)
            at org.hisp.dhis2.android.sdk.persistence.models.User$Adapter.exists(User$Adapter.java:77)
            at org.hisp.dhis2.android.sdk.persistence.models.User$Adapter.exists(User$Adapter.java:12)
            at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:309)
            at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:61)
            at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:54)

**Comment by agrosner** [comment]
its been moved up to a ```FlowLog.W``` or warning. so setting the ```FlowLog.setLevel(Level.E)``` should suppress it.
