### ISSUE TITLE
Compile time NullPointerException in project with dagger 2

### ISSUE THREAD

**Issue by fdoyle** [Raizlabs/DBFlow#110]
`Caused by: java.lang.NullPointerException
	at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:89)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)
	... 72 more`

Getting this after attempting to build a project that includes a stub dagger 2 component. If I take the component out, it builds fine. 

edit: 
This is using version 1.6 with the 2.0-Snap of dagger

**Comment by agrosner** [comment]
interesting issue. Trying to find a default database class so if you don't specify one in your ```@Table``` class it defaults to the first element it finds. Not sure why it fails there and how dagger 2 effects this. I have used other annotation processors with it and works just fine.
