### ISSUE TITLE
get an Error when i try to get count of rows

### ISSUE THREAD

**Issue by tux-world** [Raizlabs/DBFlow#1109]
for this line of code as: (beta-2) 

`long checkExistsUser = SQLite.select().from(UserInformation.class).count();`

I get this error:

```
android.database.sqlite.SQLiteDoneException
    at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:602)
    at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
    at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
    at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.simpleQueryForLong(AndroidDatabas
    at com.raizlabs.android.dbflow.sql.SqlUtils.longForQuery(SqlUtils.java:204)
    at com.raizlabs.android.dbflow.sql.language.BaseQueriable.count(BaseQueriable.java:44)
    at com.raizlabs.android.dbflow.sql.language.BaseQueriable.count(BaseQueriable.java:59)
    at com.raizlabs.android.dbflow.sql.language.From.count(From.java:182)
```

**Comment by xanscale** [comment]
count is not user frendly actually

`SQLite.selectCountOf().from(Model.class).count()`
