### ISSUE TITLE
File is encrypted or is not a database

### ISSUE THREAD

**Issue by RimonGazi** [Raizlabs/DBFlow#1127]
DBFlow Version: "3.1.1"
Sqlcipher Version : "3.5.1"

Issue Kind (Bug):
Caused by: net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;

Description:
 When i run fist time app it show this error    
Caused by: net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                                                     at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                                                     at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                                                     at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                                                     at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
                                                     at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
                                                     at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
                                                     at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1762)
                                                     at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1727)
                                                     at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2344)
                                                     at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1091)
                                                     at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1154)
                                                     at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
                                                     at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
                                                     at com.raizlabs.dbflow.android.sqlcipher.SQLCipherOpenHelper.getDatabase(SQLCipherOpenHelper.java:63)
                                                     at com.raizlabs.android.dbflow.config.DatabaseDefinition.getWritableDatabase(DatabaseDefinition.java:222)
                                                     at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:35)
                                                     at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:62)
                                                     at com.raizlabs.android.dbflow.sql.language.Where.querySingle(Where.java:285)           
 
My query is 
`  UserDataModel mUserDataModel = SQLite.select()
                .from(UserDataModel.class)
                .where(UserDataModel_Table.mIdPrimaryKey.eq(UserDataModel.DEFAULT))
                .querySingle();`

here is my model 
```
@Table(database = UcmpDatabase.class)
class UserDataModel extends BaseModel {

    public static final long  DEFAULT = 0;

    @PrimaryKey(autoincrement = false)
    long mIdPrimaryKey;

    @Column
    String mName;

    @Column
    String mEmail;

    @Column
    String mPhotoUri;

    @Column(defaultValue = "0")
    boolean isLogin;
}
```
but after clean the app form setting this time it run well . i did anything mistake or it is bug?

**Comment by RimonGazi** [comment]
still not find any answer form the dbflow if it is bug then it is big mistake of dbflow  implementation

**Comment by agrosner** [comment]
this is a SQLCipher question not a DBFlow question. Check out [this thread]()https://github.com/sqlcipher/android-database-sqlcipher/issues/247). File a new issue if it comes down to a DBFlow issue.
