### ISSUE TITLE
Updated Version - Crashing

### ISSUE THREAD

**Issue by radvansky-tomas** [Raizlabs/DBFlow#1133]
DBFlow Version: 4.0.0-Beta5
Issue Kind (Bug, Question, Feature): Bug

Description: 
Table description:
@Table(database = AppDatabase.class, uniqueColumnGroups = {@UniqueGroup(groupNumber = 1, uniqueConflict = ConflictAction.REPLACE)})

 @Column
    @PrimaryKey
    @Unique(unique = true, uniqueGroups = 1)
    @SerializedName("id")
    @Expose
    public Integer id;

Database description
@Database(name = AppDatabase.NAME, version = AppDatabase.VERSION)
public class AppDatabase {
    public static final String NAME = "AppDatabase";
    public static final int VERSION = 1;
}

```
01-05 23:37:33.523 7377-7377/plc.sixpm.iworkforce E/SQLiteLog: (1) conflicting ON CONFLICT clauses specified
01-05 23:37:33.525 7377-7377/plc.sixpm.iworkforce E/FlowLog: android.database.sqlite.SQLiteException: conflicting ON CONFLICT clauses specified (code 1): , while compiling: CREATE TABLE IF NOT EXISTS `SIPUser`(`extension` INTEGER,`id` INTEGER UNIQUE ON CONFLICT FAIL,`status` TEXT,`username` TEXT, UNIQUE(`id`) ON CONFLICT REPLACE, PRIMARY KEY(`id`));
                                                                 at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                 at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                 at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                 at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                 at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                 at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                 at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
                                                                 at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
                                                                 at com.raizlabs.android.dbflow.structure.database.AndroidDatabase.execSQL(AndroidDatabase.java:27)
                                                                 at com.raizlabs.android.dbflow.structure.database.BaseDatabaseHelper.executeCreations(BaseDatabaseHelper.java:79)
                                                                 at com.raizlabs.android.dbflow.structure.database.BaseDatabaseHelper.onCreate(BaseDatabaseHelper.java:46)
                                                                 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.onCreate(DatabaseHelperDelegate.java:70)
                                                                 at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.onCreate(FlowSQLiteOpenHelper.java:71)
                                                                 at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
                                                                 at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                 at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.getDatabase(FlowSQLiteOpenHelper.java:54)
                                                                 at com.raizlabs.android.dbflow.config.DatabaseDefinition.getWritableDatabase(DatabaseDefinition.java:207)
                                                                 at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:35)
                                                                 at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:57)
                                                                 at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:237)
                                                                 at com.sixpmplc.iworkforce.model.Message.getSortedMessages(Message.java:205)
                                                                 at com.sixpmplc.iworkforce.activities.MainActivity.LoadSqlData(MainActivity.java:383)
                                                                 at com.sixpmplc.iworkforce.fragments.MainFragment$2.onResponse(MainFragment.java:145)
                                                                 at com.sixpmplc.iworkforce.helpers.Core$4.onResponse(Core.java:321)
                                                                 at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by agrosner** [comment]
turn off `unique` on specific annotation. its not a bug its a SQLiteException for a reason.
these two statements. First one is b/c you defined `unique=true`, second one is unique group setup.
```
`id` INTEGER UNIQUE ON CONFLICT FAIL
 UNIQUE(`id`) ON CONFLICT REPLACE
```

**Comment by radvansky-tomas** [comment]
Sure I do, but can you please explain it to me:( 

What I was trying to achieve is to tell to DBFlow, that my ID field is unique (true) and it belongs to group = 1, and that group in terms of same ID replace whole entry.

**Comment by agrosner** [comment]
you probably don't need unique groups for a single field. simply leaving `@Unique(unique = true,
onUniqueConflict = ConflictAction.REPLACE)` should do what you want.

**Comment by radvansky-tomas** [comment]
ok thank you I will try;)
