### ISSUE TITLE
NullPointerException: ModelSaver.java

### ISSUE THREAD

**Issue by Digisha** [Raizlabs/DBFlow#1139]
DBFlow Version: 3.3.1
Issue Kind (Bug, Question, Feature): Bug

Description: 
We are getting following crash in our app mainly on 6.0.1

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.raizlabs.android.dbflow.structure.b.f com.raizlabs.android.dbflow.structure.e.getInsertStatement()' on a null object reference
!	1	at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.insert(ModelSaver.java:91)
2	at com.raizlabs.android.dbflow.structure.ModelAdapter.insert(ModelAdapter.java:129)
3	at com.raizlabs.android.dbflow.structure.BaseModel.insert(BaseModel.java:84)
4	at com.pocketgeek.alerts.data.dao.DeviceEventDao.createDeviceEvent(DeviceEventDao.java:34)
5	at com.pocketgeek.base.update.b.a.a(a.java:53)
6	at com.pocketgeek.base.update.b.a.a(a.java:53)
7	a
8	at com.pocketgeek.base.update.b.g.b(g.java:27)
```

**Comment by agrosner** [comment]
Are you doing anything custom the to `ModelAdapter`?

**Comment by Digisha** [comment]
We are not doing anything custom to the `ModelAdapter` in our code.

**Comment by agrosner** [comment]
might not be valid anymore. if repro with 4.0.5, please reopen.
