### ISSUE TITLE
Is it possible to determine when all migrations have finished? 

### ISSUE THREAD

**Issue by gekitz** [Raizlabs/DBFlow#1202]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 
Is it possible to determine when all migrations have finished? A PeriodicTask is uploading data for me, it kicks off when I start the app, although if I have pending migrations, it seems that the task is crashing. 

Any ideas how I can start the task once the migrations are done?

**Comment by gekitz** [comment]
That's the crash I see
```
Attempt to invoke interface method 'void com.raizlabs.android.dbflow.sql.language.SQLCondition.appendConditionToQuery(com.raizlabs.android.dbflow.sql.QueryBuilder)' on a null object reference
                                                                                     at com.raizlabs.android.dbflow.sql.language.ConditionGroup.getQuery(ConditionGroup.java:209)
                                                                                     at com.raizlabs.android.dbflow.sql.language.Where.getQuery(Where.java:221)
                                                                                     at com.raizlabs.android.dbflow.sql.language.Where.query(Where.java:243)
                                                                                     at com.raizlabs.android.dbflow.sql.language.BaseQueriable.execute(BaseQueriable.java:96)
                                                                                     at com.raizlabs.android.dbflow.sql.migration.UpdateTableMigration.migrate(UpdateTableMigration.java:69)
                                                                                     at com.raizlabs.android.dbflow.structure.database.BaseDatabaseHelper.executeMigrations(BaseDatabaseHelper.java:158)
                                                                                     at com.raizlabs.android.dbflow.structure.database.BaseDatabaseHelper.onUpgrade(BaseDatabaseHelper.java:53)
                                                                                     at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.onUpgrade(DatabaseHelperDelegate.java:78)
                                                                                     at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.onUpgrade(FlowSQLiteOpenHelper.java:76)
                                                                                     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
                                                                                     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                                     at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.getDatabase(FlowSQLiteOpenHelper.java:54)
                                                                                     at com.raizlabs.android.dbflow.config.DatabaseDefinition.getWritableDatabase(DatabaseDefinition.java:222)
                                                                                     at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:35)
                                                                                     at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:55)
                                                                                     at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:266)
                                                                                     at at.meisterwork.meisterwork.service.util.PartUploadHelper.getNotUploadedOrders(PartUploadHelper.java:83)
                                                                                     at at.meisterwork.meisterwork.service.util.PartUploadHelper.uploadNotSyncedOrders(PartUploadHelper.java:39)
                                                                                     at at.meisterwork.meisterwork.service.UploadService.startUpload(UploadService.java:134)
                                                                                     at at.meisterwork.meisterwork.service.UploadService.onHandleIntent(UploadService.java:114)
                                                                                     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
```

I'm not quite sure how to deal with it.

**Comment by agrosner** [comment]
the crash - whats causing it. Are you appending a `null` condition? I guess what I want to see is your migration code.

**Comment by agrosner** [comment]
to know if migrations are finished - youll need to subclass `FlowSQLiteOpenHelper` - or `SQLCipherOpenHelper`, override the `onMigrateMethod()` and after `super()` you can do what you need. https://github.com/Raizlabs/DBFlow/blob/master/usage2/Databases.md#custom-flowsqliteopenhelper

**Comment by gekitz** [comment]
I believe I'm doing something wrong during my migrations, basically I try to do 2 things:
- add a new column
- fill the new column with a value for all existing entries in the table

```
@Migration(version = 29, priority = 2, database = MeisterWorkDb.class)
public class AddCommentAndFloatAmountToOrder extends AlterTableMigration<Order> {

    public AddCommentAndFloatAmountToOrder(Class<Order>table) {
        super(table);
    }

    @Override
    public void onPreMigrate() {
        addColumn(SQLiteType.REAL, "floatAmount");
        addColumn(SQLiteType.TEXT, "comment");
    }
}
```
and 
```
@Migration(version = 29, priority = 1, database = MeisterWorkDb.class)
public class UpdateAmountValuesInOrder extends UpdateTableMigration<Order> {

    public UpdateAmountValuesInOrder(Class<Order> table) {
        super(table);
    }

    @Override
    public void onPreMigrate() {
        super.onPreMigrate();
        set(Order_Table.floatAmount.eq(1));
    }
}
```

The update migration fails for some reason.

**Comment by agrosner** [comment]
ahh. yes I found it. appending a `null` `WhereOperatorGroup` to the `OperatorGroup` (names changed from `Condition`/`ConditionGroup`) causes the crash. This is now fixed.

**Comment by agrosner** [comment]
in `develop`.

**Comment by gekitz** [comment]
Thank you for your effort @agrosner :D
