### ISSUE TITLE
Execution failed for task ':app:compileDebugAndroidTestJavaWithJavac'. > kotlin.UninitializedPropertyAccessException: lateinit property outputClassName has not been initialized

### ISSUE THREAD

**Issue by pamartineza** [Raizlabs/DBFlow#1209]
DBFlow Version: 4.0.0-beta5
Issue Kind: Bug, can't assemble/run  android Tests (e.g. ./gradlew assembleAndroidTest or connectedDebugAndroidTest)
Android Studio: 2.3
Kotlin: 1.1.1
Disabling instant-run has no effect

Example repo to reproduce issue: https://github.com/pamartineza/DBflowKotlin

**Description:** 
This is a 100% kotlin android project, the app and database work successfully, but If I try to run AndroidTests I will get the error:
```
Execution failed for task ':app:compileDebugAndroidTestJavaWithJavac'. > kotlin.UninitializedPropertyAccessException: lateinit property outputClassName has not been initialized.
```
running the task with --stacktrace flag provides some extra info:

```
Caused by: java.lang.RuntimeException: kotlin.UninitializedPropertyAccessException: lateinit property outputClassName has not been initialized
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:206)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:187)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:130)
        at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property outputClassName has not been initialized
        at com.raizlabs.android.dbflow.processor.definition.BaseDefinition.getTypeSpec(BaseDefinition.kt:127)
        at com.raizlabs.android.dbflow.processor.ProcessorManager.handle(ProcessorManager.kt:294)
        at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:92)
        at org.jetbrains.kotlin.annotation.AnnotationProcessorWrapper.process(AnnotationProcessorWrapper.kt:129)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:627)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1033)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1198)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 89 more
```

build.gradle files are available here: https://github.com/pamartineza/DBflowKotlin/blob/master/build.gradle
https://github.com/pamartineza/DBflowKotlin/blob/master/app/build.gradle

**Comment by pamartineza** [comment]
@agrosner I have just found that if I declare the AppDatabase class in a Java file instead of kotlin, Android tests compile and run, this may help you
