### ISSUE TITLE
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed

### ISSUE THREAD

**Issue by kistitan** [Raizlabs/DBFlow#1242]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature): Bug

Description: 

Half of our App users receive the following issue:
When trying to "save" a Model, DBFlow tries to insert but SQLite complains it already exists.
Also if I try to retrieve an item with DBFlow with the same primary key, it returns null, so also DBFlow says no item is stored with that key, but SQLite thinks differently.

I saw one similar closed issue where it was mentioned it seems to be an SQLite issue, but for me it doesn't. It really happens for many different users with many different devices and OS versions.

Do you have any hints?

Fatal Exception: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: Member.id (code 1555)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:789)
       at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
       at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
       at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.executeInsert(AndroidDatabaseStatement.java:77)
       at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.insert(ModelSaver.java:110)
       at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:57)
       at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:40)
       at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:102)
       at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:51)
       at com.bitlove.fetlife.model.pojos.Member.save(Member.java:315)

**Comment by agrosner** [comment]
1. are you doing this on different threads? deleting/ saving same models?
2. What does your `Member` class look like.

**Comment by kistitan** [comment]
Thanks for the reply.
I had to refactor the code to make it stable and the issue is not reproducable any more.

Hmm... Different threads... Might be, but not was not aware of them.
It is gone for now anyways.
Thanks

**Comment by SatyakamShailesh** [comment]
@kistitan Could you please explain what you did to do away with the issue.
