### ISSUE TITLE
.hasData() --> SQLiteDoneException

### ISSUE THREAD

**Issue by 2x2xplz** [Raizlabs/DBFlow#1257]
DBFlow Version: 4.0.0.-beta7
Issue Kind (Bug, Question, Feature): Bug?

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
When I use the .hasData() function, if there is no data, the FlowLog logs a SQLiteDoneException. 

```
04-24 14:21:02.025 27217-27596/com.xxxxx.android E/FlowLog: android.database.sqlite.SQLiteDoneException
                                                                                     at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
                                                                                     at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:598)
                                                                                     at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
                                                                                     at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
                                                                                     at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.simpleQueryForLong(AndroidDatabaseStatement.java:67)
                                                                                     at com.raizlabs.android.dbflow.sql.SqlUtils.longForQuery(SqlUtils.java:208)
                                                                                     at com.raizlabs.android.dbflow.sql.language.BaseQueriable.count(BaseQueriable.java:48)
                                                                                     at com.raizlabs.android.dbflow.sql.language.BaseQueriable.count(BaseQueriable.java:63)
                                                                                     at com.raizlabs.android.dbflow.sql.language.BaseTransformable.count(BaseTransformable.java:48)
                                                                                     at com.raizlabs.android.dbflow.sql.language.BaseQueriable.hasData(BaseQueriable.java:68)
```

I'm using Kotlin. #672 states that internally, hasData() is using count() which shouldn't raise the above error. 

Current workaround seems to be use .selectCountOf ... == 0 instead of .hasData()

**Comment by agrosner** [comment]
as stated in doc `simpleQueryForLong`:
```
An exception that indicates that the SQLite program is done.
 * Thrown when an operation that expects a row (such as {@link
 * SQLiteStatement#simpleQueryForString} or {@link
 * SQLiteStatement#simpleQueryForLong}) does not get one.
```
So it expects a row, but does not get one, meaning result is 0. the error is still logged as a warning to you, but does not crash the app. `selectCountOf()` returns a row of the count as a 1 x 1 table from the resulting `count` call. I guess the documentation on this method is wrong. Ill add it to method docs.

**Comment by agrosner** [comment]
also bumped level from `E` to `W` so it shows up as a warning instead.
