### ISSUE TITLE
 java.io.FileNotFoundException: colony_db.db

### ISSUE THREAD

**Issue by wang9090980** [Raizlabs/DBFlow#1333]
Hi：
  DBFlow Version: 4.0.4
  Issue Kind (Warning, Question):

  Description:
  When starting the app for the first time I get this warning and error message, but I have  assets folder in
my app;
![image](https://user-images.githubusercontent.com/6111077/27162817-f122e7be-51b5-11e7-8e87-e654b32c8100.png)

```
W/FlowLog: Failed to open file
                                                                 java.io.FileNotFoundException: colony_db.db
                                                                     at android.content.res.AssetManager.openAsset(Native Method)
                                                                     at android.content.res.AssetManager.open(AssetManager.java:322)
                                                                     at android.content.res.AssetManager.open(AssetManager.java:296)
                                                                     at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.movePrepackagedDB(DatabaseHelperDelegate.java:136)
                                                                     at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.performRestoreFromBackup(DatabaseHelperDelegate.java:45)
                                                                     at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.performRestoreFromBackup(FlowSQLiteOpenHelper.java:39)
                                                                     at com.raizlabs.android.dbflow.config.DatabaseDefinition.getHelper(DatabaseDefinition.java:247)
                                                                     at com.raizlabs.android.dbflow.config.DatabaseDefinition.getWritableDatabase(DatabaseDefinition.java:254)
                                                                     at com.raizlabs.android.dbflow.sql.language.Where.query(Where.java:224)
                                                                     at com.raizlabs.android.dbflow.list.FlowCursorList.<init>(FlowCursorList.java:76)
                                                                     at com.raizlabs.android.dbflow.list.FlowCursorList.<init>(FlowCursorList.java:25)
                                                                     at com.raizlabs.android.dbflow.list.FlowCursorList$Builder.build(FlowCursorList.java:358)
                                                                     at com.raizlabs.android.dbflow.list.FlowQueryList.<init>(FlowQueryList.java:72)
                                                                     at com.raizlabs.android.dbflow.list.FlowQueryList.<init>(FlowQueryList.java:39)
                                                                     at com.raizlabs.android.dbflow.list.FlowQueryList$Builder.build(FlowQueryList.java:734)
                                                                     at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.flowQueryList(BaseModelQueriable.java:101)
                                                                     at `net.wl.test.dbflowdemo.activity.GettingStartActivity.flowQueryList(GettingStartActivity.java:119)`
```

**Comment by agrosner** [comment]
your assets folder is empty. Doesnt contain colony_db.db. If its just a warning then you can ignore it.

**Comment by wang9090980** [comment]
@agrosner  Thanks .  But, my assets folder is not empty.

**Comment by agrosner** [comment]
Screenshot says otherwise
