### ISSUE TITLE
Database Migration

### ISSUE THREAD

**Issue by MahipalsinhJhala** [Raizlabs/DBFlow#1341]
DBFlow Version: 3.1.1
App getting crash after migration

Description: 
I am not able to perform any task related to database, either it is insert,update,delete or select query
It always shows below error.

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                        at com.raizlabs.android.dbflow.sql.QueryBuilder.appendQuotedIfNeeded(QueryBuilder.java:198)
                                                                        at com.raizlabs.android.dbflow.sql.language.Index.getQuery(Index.java:154)
                                                                        at com.raizlabs.android.dbflow.sql.migration.IndexMigration.migrate(IndexMigration.java:46)
                                                                        at com.raizlabs.android.dbflow.structure.database.BaseDatabaseHelper.executeMigrations(BaseDatabaseHelper.java:158)
                                                                        at com.raizlabs.android.dbflow.structure.database.BaseDatabaseHelper.onUpgrade(BaseDatabaseHelper.java:53)
                                                                        at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.onUpgrade(DatabaseHelperDelegate.java:78)
                                                                        at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.onUpgrade(FlowSQLiteOpenHelper.java:76)
                                                                        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
                                                                        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                        at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.getDatabase(FlowSQLiteOpenHelper.java:54)
                                                                        at com.raizlabs.android.dbflow.config.DatabaseDefinition.getWritableDatabase(DatabaseDefinition.java:222)
                                                                        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:35)
                                                                        at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:55)
                                                                        at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:266)

**Comment by agrosner** [comment]
are you returning `null` from the `IndexMigration` class?

**Comment by agrosner** [comment]
fixed in `develop`. should be in 4.1.0
