### ISSUE TITLE
Minor issue with model in Android library

### ISSUE THREAD

**Issue by laenger** [Raizlabs/DBFlow#138]
I keep all model classes and related functionality in an Android Library within the same project as the App itself. DBFlow works just fine but the gradle build shows an exception (which does not break the build) related to the generated `App$Database` class:

```
javax.annotation.processing.FilerException: Attempt to recreate a file for type com.raizlabs.android.dbflow.config.App$Database
        at com.sun.tools.javac.processing.JavacFiler.checkNameAndExistence(JavacFiler.java:522)
        at com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:396)
        at com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:378)
        at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:277)
        at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:94)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
        ...
```

I can't fully figure out the reason for this. I suspect that it occurs because my `@Database` annotated class also resides inside the library due to the depencency of the classes annotated with `@Table(databaseName = AppDatabase.NAME)`. Moving the Database class to the App module resolves the exception but that does not work with my actual model.

For now this exception seems to only be a minor flaw but maybe you already have an idea why this happens :)

**Comment by agrosner** [comment]
I've seen this and not sure exactly why it happens. Its possible that we have duplicate ```DatabaseWriter``` for the same database created. Or due to the ```RoundEnvironment``` nature of the annotation processor its possible duplicate rounds are run.
