### ISSUE TITLE
DBFlow Transaction Queue Blocked

### ISSUE THREAD

**Issue by gzgang** [Raizlabs/DBFlow#1394]
DBFlow Version: 3.1.1
DBFlow Transaction Queue Blocked

[traces.txt](https://github.com/Raizlabs/DBFlow/files/1196137/traces.txt)

I have a  thread pool (ExecutorService = newSingleThreadExecutor), and I submit a task to it; 
in the task,I delete a record from db; when I submit a first task, it's work ok and the task has finish, but when I submit second task to it, the code execute at delete record from db, it's Blocked.

the blocked code: ugcVideoBean.delete().
if I use ugcVideoBean.async().delete(); it work ok and not blocked; 
that's why?

there're some information from traces.txt

"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x758953a8 self=0xf4676a00
  | sysTid=25984 nice=0 cgrp=default sched=0/0 handle=0xf7013de4
  | state=S schedstat=( 7879516470 2282251591 9472 ) utm=689 stm=98 core=2 HZ=100
  | stack=0xff25b000-0xff25d000 stackSize=8MB
  | held mutexes=
  at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:40)
  - waiting to lock <0x01be5d67> (a com.raizlabs.android.dbflow.sql.saveable.ModelSaver) held by thread 86
  at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:103)
  at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:51)
  at com.lab.ugcmodule.EditShortVideoActivity.enterUgcPage(EditShortVideoActivity.java:214)
  at com.lab.ugcmodule.EditShortVideoActivity.access$100(EditShortVideoActivity.java:41)
  at com.lab.ugcmodule.EditShortVideoActivity$2.onClick(EditShortVideoActivity.java:173)
  at com.kg.v1.prompt.TipDialogHelper$1.onClick(TipDialogHelper.java:113)
  at android.view.View.performClick(View.java:5265)
  at android.view.View$PerformClick.run(View.java:21527)
  at android.os.Handler.handleCallback(Handler.java:815)
  at android.os.Handler.dispatchMessage(Handler.java:104)
  at android.os.Looper.loop(Looper.java:207)
  at android.app.ActivityThread.main(ActivityThread.java:5701)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)

"pool-12-thread-1" prio=5 tid=86 TimedWaiting
  | group="main" sCount=1 dsCount=0 obj=0x334e3820 self=0xd0763900
  | sysTid=27229 nice=0 cgrp=default sched=0/0 handle=0xcea81930
  | state=S schedstat=( 3955096190 1100479455 11251 ) utm=263 stm=132 core=0 HZ=100
  | stack=0xce97f000-0xce981000 stackSize=1038KB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x0dc87c9d> (a java.lang.Object)
  at java.lang.Thread.parkFor$(Thread.java:1220)
  - locked <0x0dc87c9d> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:299)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:198)
  at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:670)
  at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
  at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
  at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:752)
  at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
  at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.executeUpdateDelete(AndroidDatabaseStatement.java:34)
  at com.raizlabs.android.dbflow.sql.language.Where.count(Where.java:204)
  at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.delete(ModelSaver.java:126)
  - locked <0x01be5d67> (a com.raizlabs.android.dbflow.sql.saveable.ModelSaver)
  at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.delete(ModelSaver.java:119)
  - locked <0x01be5d67> (a com.raizlabs.android.dbflow.sql.saveable.ModelSaver)
  at com.raizlabs.android.dbflow.structure.ModelAdapter.delete(ModelAdapter.java:169)
  at com.raizlabs.android.dbflow.structure.BaseModel.delete(BaseModel.java:62)
  at com.lab.ugcmodule.upload.TaskItem.run(TaskItem.java:125)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)

**Comment by gzgang** [comment]
#1364 
some as it
