### ISSUE TITLE
NullPointerException in java.lang.Class com.raizlabs.android.dbflow.structure.ModelAdapter.getModelClass()

### ISSUE THREAD

**Issue by VicentZhou** [Raizlabs/DBFlow#1407]
DBFlow Version:4.3.0
Issue Kind (Bug, Question, Feature):Bug

Description: 

I got this issue twice, and I did not modify the ModelAdapter and ModelSaver directly in my code.
I read the source code of DBFlow and everything seems fine, modelSaver.setModelAdapter(this) will be called whenever ModelAdapter.modelSaver is modify, so would it cause by concurrent access?

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class com.raizlabs.android.dbflow.structure.ModelAdapter.getModelClass()' on a null object reference (clone 0)
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:309)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class com.raizlabs.android.dbflow.structure.ModelAdapter.getModelClass()' on a null object reference
    at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.getWritableDatabase(SourceFile:156)
    at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(SourceFile:29)
    at com.raizlabs.android.dbflow.structure.ModelAdapter.save(SourceFile:169)
    at com.raizlabs.android.dbflow.structure.BaseModel.save(SourceFile:62)
    at xxx.xxx.xxx.a(SourceFile:7060)
    at xxx.xxx.xxx.ReadingActivity.a(SourceFile:337)
    at xxx.xxx.xxx.ReadingActivity$87.a(SourceFile:7013)
    at xxx.xxx.xxx.ReadingActivity$87.doInBackground(SourceFile:7008)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by agrosner** [comment]
without more information, not sure what you are doing here. Are you closing and reopening a DB? 

PS DBFlow does not have a 4.3.0 version. :)
