### ISSUE TITLE
Foreign key constraint when execute transaction

### ISSUE THREAD

**Issue by smuriana** [Raizlabs/DBFlow#1468]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 
I have 2 tables like these:
**Table A**
```
public class A extend BaseModel {
    @Column
    @PrimaryKey(autoincrement = true)
    @Index
    private int id;

List<B> objectsOfTableB;

...
}
```
**Table B**
```
public class B extend BaseModel {
    @PrimaryKey
    @ForeignKey(saveForeignKeyModel = false)
    @Index
    ForeignKeyContainer<A> AForeignKeyContainer;

...
}
```
I'm trying to save a list with associated objects of both tables (ensuring that first are object from table A and nextly objects from table B) with the next code:
```
DatabaseDefinition database = FlowManager.getDatabase(AppDatabase.class);
ProcessModelTransaction<BaseModel> processModelTransaction =
new ProcessModelTransaction.Builder<>(new ProcessModelTransaction.ProcessModel<BaseModel>() {
     @Override
     public void processModel(BaseModel model) {
        model.save();
     }
}).addAll(models).build();
database.executeTransaction(processModelTransaction);
```
And I can't by foreign key constraint 
```
android.database.sqlite.SQLiteConstraintException: foreign key constraint failed (code 19)
   at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
   at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:973)
   at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
   at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
   at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.executeInsert(AndroidDatabaseStatement.java:77)
   at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.insert(ModelSaver.java:110)
   at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:57)
   at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:40)
   at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:103)
   at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:51)
   at com.company.data.local.DbFlowDataManagerHelper$1.processModel(DbFlowDataManagerHelper.java:47)
   at com.company.data.local.DbFlowDataManagerHelper$1.processModel(DbFlowDataManagerHelper.java:44)
   at com.raizlabs.android.dbflow.structure.database.transaction.ProcessModelTransaction.execute(ProcessModelTransaction.java:68)
```

I'm searching in Google if SQLite or DBFlow have this constraint for transactions but I don't see anything relative to this.

How can I save all objects of both tables in a transaction?

Thank you for your time!

**Comment by agrosner** [comment]
`android.database.sqlite.SQLiteConstraintException: foreign key constraint failed (code 19)` probably means you tried to save `B` before there was an `A`. you need to disable checking on foreign key constraints or save the `A` before a `B`. each transaction is executed sequentially so you should be ok in terms of adding one after another.
