### ISSUE TITLE
[Edited] DatabaseObjectNotClosedException from executeUpdateDelete

### ISSUE THREAD

**Issue by muhammadzadeh** [Raizlabs/DBFlow#1497]
Hi
i am using dbflow with sqlcipher
`

def dbflow_version = "4.1.2"
def sqlcipher_version = "3.5.4"

    annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflow_version}"
    implementation "net.zetetic:android-database-sqlcipher:${sqlcipher_version}@aar"
`
and my application class when as following app crash,i found helperListener is always null
`
public class iApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        try {
            FlowManager.init(new FlowConfig.Builder(this)
                .addDatabaseConfig(
                        new DatabaseConfig.Builder(dDataBase.class)
                                .openHelper(new DatabaseConfig.OpenHelperCreator() {
                                    @Override
                                    public OpenHelper createHelper(DatabaseDefinition databaseDefinition, DatabaseHelperListener helperListener) {
                                        return new SQLCipherHelperImpl(databaseDefinition, helperListener,iApplication.this);
                                    }
                                })
                                .build())
                .build());
        }
        catch (Exception e)
        {
            Log.d(dbFlowTag,e.getMessage());
        }

    }

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
}
`
when i use this,work
`

public class iApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

       FlowManager.init(this);
    }

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
}
`

**Comment by agrosner** [comment]
can you specify stacktrace please.

**Comment by muhammadzadeh** [comment]
Sorry
i cant get stacktrace because app closing with out crash in following,in line  super(databaseDefinition, listener);

`
public class SQLCipherHelperImpl extends SQLCipherOpenHelper {

    private Context context;

    public SQLCipherHelperImpl(DatabaseDefinition databaseDefinition
            , DatabaseHelperListener listener
            ,Context context) {
        super(databaseDefinition, listener);
        this.context=context;
    }

    @Override
    protected String getCipherSecret() {
        return Constants.APP_USER;
    }
}
`

**Comment by muhammadzadeh** [comment]
@agrosner

**Comment by agrosner** [comment]
what is the crash, the `helperListener` will be null because you didnt specify one in the `DatabaseConfig`.

**Comment by muhammadzadeh** [comment]
in version 4.2.3 my app not crash 
stacktarce

`
Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: DELETE FROM `DutyTable` 
                                                                     net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                                                                         at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
                                                                         at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:109)
                                                                         at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
                                                                         at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1589)
                                                                         at com.raizlabs.android.dbflow.sqlcipher.SQLCipherDatabase.compileStatement(SQLCipherDatabase.java:56)
                                                                         at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.executeUpdateDelete(BaseModelQueriable.java:111)
                                                                         at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.executeUpdateDelete(BaseModelQueriable.java:106)
                                                                         at com.raizlabs.android.dbflow.sql.language.Delete.table(Delete.java:21)
                                                                         at me.kubak.passenger.views.activity.ActSplash.continueSetup(ActSplash.java:419)
                                                                         at me.kubak.passenger.views.activity.ActSplash.onSuccessfulStart(ActSplash.java:270)
                                                                         at me.kubak.passenger.api.DataConnector$6.onResponse(DataConnector.java:584)
                                                                         at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
                                                                         at android.os.Handler.handleCallback(Handler.java:743)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:150)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
`

**Comment by agrosner** [comment]
the bug appears to be something else entirely. It would have been more helpful to specify that stacktrace with proper title. I will modify title of this ticket since its something completely different.

**Comment by agrosner** [comment]
fixed in `develop`. you can try it by replacing version `4.1.2` with `3f3d0b437e`
