### ISSUE TITLE
Order field syntax error

### ISSUE THREAD

**Issue by renouille** [Raizlabs/DBFlow#182]
I have a table with a field called "order". When saving the object, it throws a syntax error :

    Category cat = new Category();
    cat.id = catJSON.getString(Category$Table.ID);
    cat.order = catJSON.getString(Category$Table.ORDER);
    cat.save(false);

    E/SQLiteLog﹕ (1) near "order": syntax error
    E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: dbflowtest, PID: 9839
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
    Caused by: android.database.sqlite.SQLiteException: near "order": syntax error (code 1): , while compiling: UPDATE  OR ABORT Category SET order=?,id=? WHERE `id`='3379629'
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at  android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1574)
            at com.raizlabs.android.dbflow.SQLiteCompatibilityUtils.updateWithOnConflict(SQLiteCompatibilityUtils.java:63)

**Comment by renouille** [comment]
FYI, I use version 1.8.0

**Comment by agrosner** [comment]
@renouille how are you updating model? Also can you send your `Model`?

**Comment by renouille** [comment]
Actually, I don't update it but only try to create one instance,the way I showed in the first post.

For my model:

    @Table
    public class Category extends ContentBase {

    @Column(columnType = Column.PRIMARY_KEY)
    public String id;
    @Column
    public String title;
    @Column
    public int order;
    @Column
    public String description;

    private List<MediaImage> childrenMediaImage;

    public Category() { }

    public List<MediaImage> getChildrenMediaImage() {

        if (childrenMediaImage == null) {
            childrenMediaImage = Select.all(MediaImage.class, Condition.column(MediaImage$Table.PARENTID).is(this.aioID));
        }
        return childrenMediaImage;
    }
    }

Category extends several fields from ContentBase. But I don't think it is related. I tried to show you a simplfied version of my model. I can however send you the files if you are interested.
