### ISSUE TITLE
Calling save() Inside transact() May Deadlock

### ISSUE THREAD

**Issue by dylanrjames** [Raizlabs/DBFlow#183]
I've run into an issue where I had some code that ends up trying to concurrently update the same model table via nested objects. Since one of the `save()` calls is wrapped in a `transact()`, there is a certain sequence of events which sometimes causes a deadlock. For context, I have model objects being stored that look something like:

```
public class MyInnerObject {
     // a bunch of fields
}

public class MyOuterObject {
    private MyInnerObject innerObject;
}
```

When the deadlock happens, I get the following message in logcat:

```
W/SQLiteConnectionPool﹕ The connection pool for database '/data/data/com.myapp/databases/AppDatabase.db' has been unable to grant a connection to thread 1 (main) with flags 0x5 for 60.002003 seconds.
    Connections: 0 active, 1 idle, 0 available.
```

At this point if I have the debugger attached and suspend all threads, I will find one thread waiting for the synchronized lock on the `ModelAdapter` for my inner object, with a stack trace like:

```
Thread-1@9999, prio=5, in group 'main', status: 'MONITOR'
	 waiting for Thread-1@9999 to release lock on <0x132a> (a com.myApp.MyInnerModel$Adapter)
	  at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:61)
	  at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:54)
	  at com.myApp.MyOuterModel$Adapter.bindToContentValues(MyOuterModel$Adapter.java:85)
	  at com.myApp.MyOuterModel$Adapter.bindToContentValues(MyOuterModel$Adapter.java:12)
	  at com.raizlabs.android.dbflow.sql.SqlUtils.update(SqlUtils.java:344)
	  at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:312)
	  at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:61)
	  at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:54)
	  at com.raizlabs.android.dbflow.structure.cache.BaseCacheableModel.save(BaseCacheableModel.java:82)
	  at com.myApp.MyOuterModelManager$1.run(MyOuterModelManager.java:99)
	  at com.raizlabs.android.dbflow.runtime.TransactionManager.transact(TransactionManager.java:120)
	  at com.raizlabs.android.dbflow.runtime.TransactionManager.transact(TransactionManager.java:109)
	  at com.myApp.MyOuterModelManager.store(MyOuterModelManager.java:99)
	  ...
```

I will find a second thread which is stuck waiting on the `SQLiteConnectionPool`, which has the following stack trace:

```
Thread-2@9999, prio=5, in group 'main', status: 'WAIT'
	 blocks Thread-2@9999
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor(Thread.java:1220)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
	  at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:670)
	  at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
	  at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
	  at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:586)
	  at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	  at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	  at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1574)
	  at com.raizlabs.android.dbflow.SQLiteCompatibilityUtils.updateWithOnConflict(SQLiteCompatibilityUtils.java:63)
	  at com.raizlabs.android.dbflow.sql.SqlUtils.update(SqlUtils.java:345)
	  at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:312)
	  at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:61)
	  at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:54)
	  at com.myApp.MyInnerModelManager.store(MyInnerModelManager.java:99)
	  ...
```

Thread 1 has started a transaction to make all of the changes to `MyOuterModel` through `save()`, but this `save()` is recursively going into the `MyInnerModel` and trying to do another `save()`. Thread 2 has come in and tried to call `save()` with a set of `MyInnerModel` updates. Thread 2 has made it far enough to take the `save()` lock for `MyInnerModel`, but it is unable to perform the SQL operations since Thread 1 has not ended its transaction. Thread 1 is unable to finish its transaction because it cannot perform the `save()` call on `MyInnerObject` since Thread 2 is holding the lock. As such the database deadlocks and I can no longer access or write to the database.

**Comment by nsatvik** [comment]
Facing this issue in the latest 3.0.1 Please suggest the fix/work around. Thanks!
