### ISSUE TITLE
Gradle Build Error - NullPointerException thrown during app:compileDebugJava gradle task

### ISSUE THREAD

**Issue by EGeorgiev** [Raizlabs/DBFlow#185]
Hello guys. Since few hours I have this error "Gradle Build Error - NullPointerException thrown during app:compileDebugJava gradle task"
I remove DBFlow from the project and now it starts fine. No errors.What I have to do now? Where is my fault?! 
Best regards.

**Comment by agrosner** [comment]
Can you send me the full gradle log. Usually this means there was an error thrown. Gradle is not good at showing true errors with annotation processing.

**Comment by EGeorgiev** [comment]
This is the full info from the Gradle Console.

Executing tasks: [:app:assembleDebug]

Configuration on demand is an incubating feature.
:app:preBuild
:app:compileDebugNdk UP-TO-DATE
:app:preDebugBuild
:app:checkDebugManifest
:app:preReleaseBuild
:app:prepareComAndroidSupportAppcompatV72103Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42103Library UP-TO-DATE
:app:prepareComRaizlabsAndroidDBFlow180Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJava'.
> java.lang.NullPointerException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.808 secs

**Comment by agrosner** [comment]
Can you run the command on the CLI and use the --stacktrace command and
push it here?

On Wed, Apr 8, 2015 at 9:37 AM, EGeorgiev <notifications@github.com> wrote:

> This is the full info from the Gradle Console.
>
> Executing tasks: [:app:assembleDebug]
>
> Configuration on demand is an incubating feature.
> :app:preBuild
> :app:compileDebugNdk UP-TO-DATE
> :app:preDebugBuild
> :app:checkDebugManifest
> :app:preReleaseBuild
> :app:prepareComAndroidSupportAppcompatV72103Library UP-TO-DATE
> :app:prepareComAndroidSupportSupportV42103Library UP-TO-DATE
> :app:prepareComRaizlabsAndroidDBFlow180Library UP-TO-DATE
> :app:prepareDebugDependencies
> :app:compileDebugAidl UP-TO-DATE
> :app:compileDebugRenderscript UP-TO-DATE
> :app:generateDebugBuildConfig UP-TO-DATE
> :app:generateDebugAssets UP-TO-DATE
> :app:mergeDebugAssets UP-TO-DATE
> :app:generateDebugResValues UP-TO-DATE
> :app:generateDebugResources UP-TO-DATE
> :app:mergeDebugResources UP-TO-DATE
> :app:processDebugManifest UP-TO-DATE
> :app:processDebugResources UP-TO-DATE
> :app:generateDebugSources UP-TO-DATE
> :app:compileDebugJava FAILED
>
> FAILURE: Build failed with an exception.
>
>    -
>
>    What went wrong:
>    Execution failed for task ':app:compileDebugJava'.
>
>    java.lang.NullPointerException
>
>     -
>
>    Try:
>    Run with --stacktrace option to get the stack trace. Run with --info
>    or --debug option to get more log output.
>
> BUILD FAILED
>
> Total time: 1.808 secs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Raizlabs/DBFlow/issues/185#issuecomment-90918515>.
>



-- 
--

*Andrew Grosner, Android Developer*

Mobile Strategy, Design & Development

www.raizlabs.com | Check my calendar
<https://www.google.com/calendar/embed?src=andrew.grosner@raizlabs.com&ctz=America/New_York&mode=WEEK>
 | @agrosner <http://www.twitter.com/agrosner> | 716-472-5075
[image: Raizlabs]

**Comment by EGeorgiev** [comment]
Sorry for the delay ... here is the info: 

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at com.sun.tools.javac.main.Main.compile(Main.java:469)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:42)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:97)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:158)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:138)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:92)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:235)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:222)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 47 more
Caused by: java.lang.NullPointerException
        at com.raizlabs.android.dbflow.processor.ProcessorUtils.implementsClass(ProcessorUtils.java:29)
        at com.raizlabs.android.dbflow.processor.definition.ColumnDefinition.<init>(ColumnDefinition.java:152)
        at com.raizlabs.android.dbflow.processor.definition.TableDefinition.createColumnDefinitions(TableDefinition.java:185)
        at com.raizlabs.android.dbflow.processor.definition.TableDefinition.<init>(TableDefinition.java:127)
        at com.raizlabs.android.dbflow.processor.handler.TableHandler.onProcessElement(TableHandler.java:34)
        at com.raizlabs.android.dbflow.processor.handler.BaseContainerHandler.handle(BaseContainerHandler.java:25)
        at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:263)
        at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:94)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
        at com.sun.tools.javac.main.Main.compile(Main.java:439)
        ... 65 more


BUILD FAILED

Total time: 13.13 secs

**Comment by caioyassoyama** [comment]
I had the same problem:

```
11:50:55.223 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NullPointerException
11:50:55.224 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.definition.ColumnDefinition.write(ColumnDefinition.java:175)
11:50:55.224 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.definition.TableDefinition.onWriteDefinition(TableDefinition.java:239)
11:50:55.225 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.definition.BaseDefinition.write(BaseDefinition.java:52)
11:50:55.226 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.utils.WriterUtils.writeBaseDefinition(WriterUtils.java:64)
11:50:55.227 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.handler.TableHandler.onProcessElement(TableHandler.java:36)
11:50:55.227 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.handler.BaseContainerHandler.handle(BaseContainerHandler.java:25)
11:50:55.228 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:263)
11:50:55.229 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:94)
11:50:55.241 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
11:50:55.242 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
11:50:55.243 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
11:50:55.243 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
11:50:55.244 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
11:50:55.245 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
11:50:55.245 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
11:50:55.248 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.Main.compile(Main.java:439)
11:50:55.249 [ERROR] [org.gradle.BuildExceptionReporter] 	... 65 more
```

The problem was that I've forgotten to define the columnType on a foreign key attribute annotation.

From (wrong):
```java
    @Column(references = {@ForeignKeyReference(columnName = "addressBook", columnType = long.class, foreignColumnName = "id")})
    AddressBook addressBook;
```
To (correct):
```java
    @Column(columnType = Column.FOREIGN_KEY,
            references = {@ForeignKeyReference(columnName = "addressBook", columnType = long.class, foreignColumnName = "id")})
    AddressBook addressBook;
```

**Comment by EGeorgiev** [comment]
I haven't FOREIGN KEY in my tables and I'm not obliged to have one.

**Comment by agrosner** [comment]
@EGeorgiev What's your `Model` look like? It may point to the issue, but there are 3 scenarios to look for here:
  1. Any fields that are _not_ `ModelContainer` with parameters in the field type? (very likely, like `List<Model>`
  2. Or a custom field type (less likely)

**Comment by gauravlucky** [comment]
@agrosner - I'm facing the same issue as above and I'm not able to locate the cause. Here's my stacktrace -
`12:19:15.958 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NullPointerException
12:19:15.959 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.definition.column.ColumnDefinition.getToModelMethod(ColumnDefinition.java:318)
12:19:15.960 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.definition.method.ToModelMethod.getMethodSpec(ToModelMethod.java:34)
12:19:15.961 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.definition.ModelContainerDefinition.onWriteDefinition(ModelContainerDefinition.java:98)
12:19:15.962 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.definition.BaseDefinition.getTypeSpec(BaseDefinition.java:119)
12:19:15.962 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.utils.WriterUtils.writeBaseDefinition(WriterUtils.java:17)
12:19:15.963 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:320)
12:19:15.963 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:100)
12:19:15.964 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
12:19:15.964 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
12:19:15.965 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
12:19:15.965 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
12:19:15.966 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
12:19:15.966 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
12:19:15.967 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
12:19:15.967 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.tools.javac.main.Main.compile(Main.java:439)
12:19:15.967 [ERROR] [org.gradle.BuildExceptionReporter] 	... 78 more
12:19:15.968 [ERROR] [org.gradle.BuildExceptionReporter]
12:19:15.968 [LIFECYCLE] [org.gradle.BuildResultLogger]
12:19:15.969 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED`

**Comment by gauravlucky** [comment]
Sorry my bad. Missed out one thing from documentation.

For anyone using custom TypeConverter facing this, make sure you are defining it in the column annotation attribute.

`@Column (typeConverter = DeliverySlotTypeConverter.class)
    DeliverySlot delivery_slot;`
