### ISSUE TITLE
Didn't find class "com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder"

### ISSUE THREAD

**Issue by rmirabelle** [Raizlabs/DBFlow#241]
```
05-14 11:22:23.349    2832-2832/com.mirabelle.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mirabelle.app, PID: 2832
    java.lang.RuntimeException: Unable to create application com.mirabelle.liquid.MyApplication: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
            at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:116)
            at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:155)
            at com.mirabelle.liquid.MyApplication.onCreate(MyApplication.groovy:17)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:309)
            at java.lang.Class.forName(Class.java:273)
            at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:113)
            at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:155)
            at com.mirabelle.liquid.MyApplication.onCreate(MyApplication.groovy:17)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder" on path: DexPathList[[zip file "/data/app/com.mirabelle.app-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:309)
            at java.lang.Class.forName(Class.java:273)
            at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:113)
            at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:155)
            at com.mirabelle.liquid.MyApplication.onCreate(MyApplication.groovy:17)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    Suppressed: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 18 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```
Project `build.gradle`:
```
buildscript {
    repositories {
        jcenter()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
        classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.6'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases" }
    }
}
```

Module `build.gradle`:

```
apply plugin: 'com.android.application'
apply plugin: 'groovyx.grooid.groovy-android'
apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.mirabelle.app"
        minSdkVersion 17
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {

    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.1.1'
    compile 'org.codehaus.groovy:groovy:2.4.3:grooid'
    compile 'io.reactivex:rxjava:1.0.10'
    compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1'
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    apt 'com.raizlabs.android:DBFlow-Compiler:2.0.0'
    compile 'com.raizlabs.android:DBFlow-Core:2.0.0'
    compile 'com.raizlabs.android:DBFlow:2.0.0'
}
```

**Comment by kamilzych** [comment]
@rmirabelle Do you have a dot character (.) in your database name? Apparently there is an error in library. When your database has a dot character - for example sqlite.db - it tries to generate a class which name is: sqlite.db$Database - in Java language classes can't have dot character in their names so this is the reason of compile error. @agrosner this error wasn't present before 2.0 release

**Comment by kamilzych** [comment]
@agrosner I made a pull  #243 request which doesn't solve this problem in any way but an error is thrown with more human readable error message in cases I've described in my previous comment.

**Comment by rmirabelle** [comment]
My database does have a period: it's called `database.db`

Will test with removal of (`.`) - but as this is perfectly valid from an OS standpoint, I think the library should naturally be updated to account for this, rather than throwing an exception.

**Comment by jhoobergs** [comment]
I have the same problem, but my databasename does not contain a period are something, it's just "flow"

**Comment by MaximEfimovRMR** [comment]
This is totally unclean, but until you create the first table (any class annotated with `@Table`), you would get this exception. In fact, it's most common case: you start project, add all required libraries, do initialization, and then start coding business-logic. But for DBFlow you just don't understand what is wrong with this trivial process. 
  
I strongly recommend to describe such behavior in docs, and fix exception to be more meaningful.

**Comment by matteinn** [comment]
Same issue here with v1.8.1
I'm simply calling 
FlowManager.init(this);
in the Application class.

Affected devices:
- Samsung Galaxy Note II with 4.4.4 and virtual device (Genymotion) running 4.4.4
Works fine with Lollipop

**Comment by nambv** [comment]
I got the same problem too :( does anyone find solution, please :( thanks a lot :(

**Comment by darkovski88** [comment]
So anyone has a fix on this? Im having the same issue... Can it be related with something with support library or compileSdkVersion?

**Comment by darkovski88** [comment]
maybe mentioning @agrosner will help

**Comment by wznshuai** [comment]
i got the same problem.please help me

**Comment by darkovski88** [comment]
Ah... finaly the solution..
The solutions is to create a table first, read the @MaximEfimovRMR  answer..
Create at least one table by following this: https://github.com/Raizlabs/DBFlow/blob/master/usage/DBStructure.md

**Comment by blackvvine** [comment]
I can confirm the solution above, weirdly there HAS to be a table created in the project so that the "init" call won't end in an error.

**Comment by voghDev** [comment]
+1. I was having the same issue and solved it by creating my first table

**Comment by yangzxstar** [comment]
i have the same problem in debug mode, but when i run in release mode, the error go away. so wired!

**Comment by AdamSHurwitz** [comment]
I'm getting this error when trying to add my objects to my database 'The global database holder is not initialized. Ensure you call FlowManager.init() before accessing the database.'

**Comment by voghDev** [comment]
Just an obvious question @AdamSHurwitz, are you sure that the FlowManager.init() line is reached at the App startup? Else you could the solution mentioned above

**Comment by AdamSHurwitz** [comment]
It turns out it was an issue with Kotlin. (I posted the details in a similar issue for this project. GitHub needs a way to search for all of your comments. If I find it I'll post here.)

Essentially, enable Kotlin first before setting up dbflow and ensure you use **kapt** instead of **annotaionProcessor**
