### ISSUE TITLE
SQLiteDiskIOException after resetting database

### ISSUE THREAD

**Issue by andmar1x** [Raizlabs/DBFlow#251]
Hi,

I receive crash every time when I'm trying to insert new items to the database after reset:
```
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
            at android.app.ActivityThread.access$900(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:976)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:282)
            at com.raizlabs.android.dbflow.structure.ModelAdapter.insert(ModelAdapter.java:64)
            at com.raizlabs.android.dbflow.structure.BaseModel.insert(BaseModel.java:76)
            at com.raizlabs.android.dbflow.DemoActivity.insertOne(DemoActivity.java:42)
            at com.raizlabs.android.dbflow.DemoActivity.onCreate(DemoActivity.java:32)
            at android.app.Activity.performCreate(Activity.java:5426)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
            at android.app.ActivityThread.access$900(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

```
Here's the code:
```
...

FlowManager.init(getBaseContext());

for (int i = 1; i <= 100; ++i) {
    insertOne(i);
}

FlowManager.getDatabase(AppDatabase.NAME).reset(getBaseContext());

for (int i = 101; i <= 200; ++i) {
    insertOne(i);
}

...
```
`insertOne(int i)` method:
```
private void insertOne(int i) {
    AModel aModel = new AModel();
    aModel.date = new Date();
    aModel.name = AModel.class.getSimpleName() + " " + i;
    aModel.time = System.currentTimeMillis();

    aModel.insert();
}
```

I'm tried to use solution from https://github.com/Raizlabs/DBFlow/issues/78#issuecomment-74755922, but it not helps.
I use a latest version of DBFlow (2.0.0).

**Comment by kaeawc** [comment]
I've had a similar issue, read the docs but it doesn't seem clear whether FlowManager.init needs time to reinitialize the database. Been trying to figure out the best way to do a database wipe + rebuild tables without having the user restart the app.

**Comment by andmar1x** [comment]
After some research I found that recreating [mDatabaseHolder](https://github.com/Raizlabs/DBFlow/blob/master/library/src/main/java/com/raizlabs/android/dbflow/config/FlowManager.java#L33) after reset could help, but maybe this workaround is not good.

**Comment by jonathanrz** [comment]
I had the same problem, someone found any workaround?

**Comment by franzejr** [comment]
I think this bug still up? Someone know some workaround?

I think this bug is the same of (for some Mobile Phones, mostly Samsung):

```
 java.lang.RuntimeException: android.database.sqlite.SQLiteException: cannot rollback - no transaction is active (code 1)
                                                                                         at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:75)
                                                                                      Caused by: android.database.sqlite.SQLiteException: cannot rollback - no transaction is active (code 1)
                                                                                         at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
                                                                                         at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
                                                                                         at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
                                                                                         at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
                                                                                         at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
                                                                                         at com.raizlabs.android.dbflow.runtime.TransactionManager.transact(TransactionManager.java:111)
                                                                                         at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelHelper.process(ProcessModelHelper.java:28)
                                                                                         at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelInfo.processModels(ProcessModelInfo.java:159)
                                                                                         at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelTransaction.onExecute(ProcessModelTransaction.java:73)
                                                                                         at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelTransaction.onExecute(ProcessModelTransaction.java:13)
                                                                                         at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.ja
```

**Comment by WasimMemon** [comment]
Still getting this issue with V4.0.4  
Any update on this.

```
statement aborts at 1: [BEGIN EXCLUSIVE;] disk I/O error
file unlinked while open: /data/user/0/
E/FlowLog: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.app/databases/appdb.db
           at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
           at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
```
