### ISSUE TITLE
DBFlow not compatible with Gradle 2.5

### ISSUE THREAD

**Issue by nasahapps** [Raizlabs/DBFlow#318]
When using Gradle 2.5, any build results in this error:  

>FAILURE: Build failed with an exception.
* What went wrong:
Could not find method executeWithoutThrowingTaskFailure() for arguments [] on task ':linkSources'.
* Try:
Run with --info or --debug option to get more log output.
* Exception is:
org.gradle.api.internal.MissingMethodException: Could not find method executeWithoutThrowingTaskFailure() for arguments [] on task ':linkSources'.
        at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
        at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:175)
        at com.raizlabs.LinkSourcesTask_Decorated.invokeMethod(Unknown Source)
        at com.raizlabs.LinkSourcesTask$_linkSourcesFromProject_closure1.doCall(LinkSourcesTask.groovy:45)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy9.projectsEvaluated(Unknown Source)
        at org.gradle.initialization.DefaultGradleLauncher$5.run(DefaultGradleLauncher.java:165)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:47)
        at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLauncher.java:189)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:159)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:104)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleLauncher.java:184)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:93)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:27)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.executeBuildAndAccumulateInputs(ContinuousBuildActionExecuter.java:161)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.executeMultipleBuilds(ContinuousBuildActionExecuter.java:106)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:70)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:44)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:49)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
BUILD FAILED  

Would appreciate if this was fixed so we can use the latest and greatest Gradle version.

**Comment by nasahapps** [comment]
Build setup mistake on my part. Was still using 

`classpath 'com.raizlabs:griddle:1.0.3`  

in my project build.gradle. Removing that fixed the issue.

**Comment by arturonaredo** [comment]
Having same issue with 2.5, 2.6, 2.7 :(

```
2015-09-16 00:38:41,688 [2948928]   WARN - nal.AbstractExternalSystemTask - Gradle DSL method not found: 'executeWithoutThrowingTaskFailure()' 
com.intellij.openapi.externalSystem.model.ExternalSystemException: Gradle DSL method not found: 'executeWithoutThrowingTaskFailure()'
	at com.android.tools.idea.gradle.project.ProjectImportErrorHandler.createUserFriendlyError(ProjectImportErrorHandler.java:274)
	at com.android.tools.idea.gradle.project.ProjectImportErrorHandler.getUserFriendlyError(ProjectImportErrorHandler.java:90)
	at com.android.tools.idea.gradle.project.AndroidGradleProjectResolver.getUserFriendlyError(AndroidGradleProjectResolver.java:344)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:164)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:366)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:332)
	at org.jetbrains.plugins.gradle.service.project.GradleExecutionHelper.execute(GradleExecutionHelper.java:215)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:97)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:65)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:41)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4.execute(ExternalSystemUtil.java:540)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5$2.run(ExternalSystemUtil.java:621)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

2015-09-16 00:38:41,691 [2948931]   WARN - radle.project.ProjectSetUpTask -  
2015-09-16 00:38:41,692 [2948932]   INFO - radle.project.ProjectSetUpTask - Gradle DSL method not found: 'executeWithoutThrowingTaskFailure()'

Consult IDE log for more details (Help | Show Log) 
2015-09-16 00:38:41,692 [2948932]   INFO - ls.idea.gradle.GradleSyncState - Sync with Gradle for project 'glownet-next' failed: Gradle DSL method not found: 'executeWithoutThrowingTaskFailure()'

Consult IDE log for more details (Help | Show Log) 
2015-09-16 00:38:41,775 [2949015]   INFO -       #com.jetbrains.cidr.lang - Clearing symbols finished in 0 s. 
2015-09-16 00:38:41,812 [2949052]   INFO -       #com.jetbrains.cidr.lang - Loading symbols finished in 0 s. 
2015-09-16 00:38:41,816 [2949056]   INFO -       #com.jetbrains.cidr.lang - Building symbols finished in 0 s. 
2015-09-16 00:38:41,816 [2949056]   INFO -       #com.jetbrains.cidr.lang - Saving symbols finished in 0 s. 
2015-09-16 00:38:46,138 [2953378]   INFO - ls.idea.gradle.GradleSyncState - Started sync with Gradle for project 'glownet-next'. 
2015-09-16 00:38:46,149 [2953389]   INFO - s.plugins.gradle.GradleManager - Instructing gradle to use java from /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home 
```

My configuration seems to be ok though:
        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases" }
        classpath 'com.raizlabs:Griddle:1.0.3'

apply plugin: 'com.android.application'
apply plugin: 'com.raizlabs.griddle'

dBFlowVersion = '2.2.1'

dataDependencies = [
            dBFlowCompiler:             "com.raizlabs.android:DBFlow-Compiler:${dBFlowVersion}",
            dBFlowCore:                 "com.raizlabs.android:DBFlow-Core:${dBFlowVersion}",
            dBFlow:                     "com.raizlabs.android:DBFlow:${dBFlowVersion}",
]

    apt     dataDependencies.dBFlowCompiler
    compile dataDependencies.dBFlowCore
    compile dataDependencies.dBFlow

**Comment by jonathanrz** [comment]
Same problem here, could find any solutions :/

**Comment by JohnnyTwoShoes** [comment]
Can you please post me your two build.gradle files (top level and app level). I can't get this crap to work, and I'm about to pull my hair out in frustration with this pile of ****. Also, why is it that I can't get it to work with other libraries, eg DBFlow with Robobinding? I can get them to work individually , but, when I combine them, I get these cryptic useless messages , eg Error:Gradle DSL method not found: 'executeWithoutThrowingTaskFailure()'

**Comment by agrosner** [comment]
are you using the `aar-linksources` plugin? It doesn't work in newer
versions of gradle.

**Comment by JohnnyTwoShoes** [comment]
I apologise for my rudeness, spending days on getting just the gradle to work is frustrating. Here are my two build.gradle files:
buildscript {
    repositories {
        jcenter()
//        mavenCentral()
//        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases"}
        maven() {
            name 'RoboBinding AspectJPlugin Maven Repository'
            url "https://github.com/RoboBinding/RoboBinding-aspectj-plugin/raw/master/mavenRepo"
        }
        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases"}

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
        classpath 'org.robobinding:aspectj-plugin:0.8.4'
        classpath 'com.raizlabs:Griddle:1.0.3'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
allprojects {
    repositories {
        jcenter()
        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases"}
        maven() {
            name 'RoboBinding AspectJPlugin Maven Repository'
            url "https://github.com/RoboBinding/RoboBinding-aspectj-plugin/raw/master/mavenRepo"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

//app level build.gradle:

apply plugin: 'com.android.application'
apply plugin: 'com.raizlabs.griddle'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'org.robobinding.android-aspectj'


android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.example.iqbalhajat.myapplicationrobobinding"
        minSdkVersion 18
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
ext {
    robobindingVersion = 'latest.integration'
    //RoboBinding 0.8.6 is out.
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'


    compile("org.robobinding:robobinding:$robobindingVersion:with-aop-and-dependencies") {
        exclude group: 'com.google.guava', module: 'guava'
    }
    aspectPath("org.robobinding:robobinding:$robobindingVersion:with-aop-and-dependencies") {
        exclude group: 'com.google.guava', module: 'guava'
    }
    apt "org.robobinding:codegen:$robobindingVersion"

    apt 'com.raizlabs.android:DBFlow-Compiler:2.2.1'
    compile "com.raizlabs.android:DBFlow-Core:2.2.1"
    compile "com.raizlabs.android:DBFlow:2.2.1"


    compile files('libs/gson-2.5.jar')
}


anything there that seems incorrect?

**Comment by jonathanrz** [comment]
JohnnyTwoShoes -> remove the griddle dependencies, it is not necessary anymore

**Comment by agrosner** [comment]
Yes good call. I would remove that, it's no longer in active development.

**Comment by JohnnyTwoShoes** [comment]
I'm getting:
Error:Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.google.auto.service.processor.AutoServiceProcessor could not be instantiated: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(Z)V
:app:compileDebugJavaWithJavac FAILED

**Comment by JohnnyTwoShoes** [comment]
Does this help:
20:30:41.861 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Sets.newHashSet(Ljava/lang/Iterable;)Ljava/util/HashSet;
20:30:41.862 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.handler.BaseContainerHandler.handle(BaseContainerHandler.java:19)
20:30:41.862 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:278)
20:30:41.862 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:85)

**Comment by JohnnyTwoShoes** [comment]
also why does the rebuild project succeed but the run fails? here is the rebuild project output:
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2311Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72311Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:app:prepareComRaizlabsAndroidDBFlow221Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:preDebugAndroidTestBuild UP-TO-DATE
:app:prepareDebugAndroidTestDependencies
:app:compileDebugAndroidTestAidl
:app:processDebugAndroidTestManifest UP-TO-DATE
:app:compileDebugAndroidTestRenderscript
:app:generateDebugAndroidTestBuildConfig UP-TO-DATE
:app:generateDebugAndroidTestAssets UP-TO-DATE
:app:mergeDebugAndroidTestAssets UP-TO-DATE
:app:generateDebugAndroidTestResValues UP-TO-DATE
:app:generateDebugAndroidTestResources
:app:mergeDebugAndroidTestResources
:app:processDebugAndroidTestResources
:app:generateDebugAndroidTestSources

BUILD SUCCESSFUL

**Comment by fcemmonA** [comment]
Hello, I am working for integrating DBFlow into my Android Studio project.
The DBFlow version is 4.0.0-beta7.
But I am getting the following error when building gradle:

Error:Could not find method executeWithoutThrowingTaskFailure() for arguments [] on task ':linkSources' of type com.raizlabs.LinkSourcesTask.

Can you guid me for this issue?

Thank you
