### ISSUE TITLE
Problems testing with Robolectric

### ISSUE THREAD

**Issue by wongcain** [Raizlabs/DBFlow#34]
This may be more of a question for the Robolectric team, but I'll post it here first.

I have a very simple Dao class:
```
public class ReviewsDao {

    public ReviewsDao() {
    }

    public synchronized void saveList(List<Review> reviews){
        TransactionManager.getInstance().saveOnSaveQueue(reviews);
    }

    public Review get(String key){
        return Select.byId(Review.class, key);
    }

}
```

And a very simple Unit test:
```
@RunWith(RobojavaTestRunner.class)
public class ReviewsDaoTest {

    ReviewsDao dao;

    @Test
    public void testSaveListAndGet() throws Exception {
        dao = new ReviewsDao();
        List<Review> reviews = new ArrayList<>(10);
        for(int i=0; i<10; i++){
            Review review = new Review();
            review.id = "id_" + i;
            review.title = "Review " + i;
            reviews.add(review);
        }
        dao.saveList(reviews);
        Thread.sleep(100);
        for(int i=0; i<10; i++) {
            Review review = dao.get("id_" + i);
            assertThat(review).isNotNull();
            assertThat(review.title).isEqualTo("Review " + i);
        }
    }

}
```

When I run this unit test alone, it completes without error.  However, when I run it as part of an entire test suite, I get the following errors:
```
WARNING: [sqlite] [ROLLBACK;]DB[1][C]: exception when clearing
com.almworks.sqlite4java.SQLiteException: [1] DB[1] reset [cannot rollback - no transaction is active]
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1309)
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1282)
	at com.almworks.sqlite4java.SQLiteConnection.cacheStatementHandle(SQLiteConnection.java:1211)
	at com.almworks.sqlite4java.SQLiteConnection.access$900(SQLiteConnection.java:54)
	at com.almworks.sqlite4java.SQLiteConnection$CachedController.dispose(SQLiteConnection.java:1606)
	at com.almworks.sqlite4java.SQLiteStatement.dispose(SQLiteStatement.java:187)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$4.call(ShadowSQLiteConnection.java:394)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:422)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:416)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

Exception in thread "TransactionManager" java.lang.RuntimeException: android.database.sqlite.SQLiteException: Cannot execute, base error code: 1
	at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:77)
Caused by: android.database.sqlite.SQLiteException: Cannot execute, base error code: 1
	at org.robolectric.shadows.ShadowSQLiteConnection.rethrow(ShadowSQLiteConnection.java:48)
	at org.robolectric.shadows.ShadowSQLiteConnection.access$500(ShadowSQLiteConnection.java:26)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:436)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativeExecute(ShadowSQLiteConnection.java:112)
	at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
	at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
	at com.raizlabs.android.dbflow.runtime.TransactionManager.transact(TransactionManager.java:119)
	at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelHelper.process(ProcessModelHelper.java:26)
	at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelTransaction.onExecute(ProcessModelTransaction.java:34)
	at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelTransaction.onExecute(ProcessModelTransaction.java:12)
	at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:63)
Caused by: com.almworks.sqlite4java.SQLiteException: [1] DB[1] step() [ROLLBACK;]DB[1][C] [cannot rollback - no transaction is active]
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1309)
	at com.almworks.sqlite4java.SQLiteConnection$BaseController.throwResult(SQLiteConnection.java:1562)
	at com.almworks.sqlite4java.SQLiteStatement.stepResult(SQLiteStatement.java:1231)
	at com.almworks.sqlite4java.SQLiteStatement.step(SQLiteStatement.java:302)
	at com.almworks.sqlite4java.SQLiteStatement.stepThrough(SQLiteStatement.java:316)
	at org.robolectric.shadows.ShadowSQLiteConnection$4.call(ShadowSQLiteConnection.java:116)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:422)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:416)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

Any ideas of what I can do, perhaps at `@Before` in the unit test to prevent this problem?

**Comment by agrosner** [comment]
hey @wongcain I would shy against using the ```saveOnSaveQueue()``` for time important tasks such as testing.The way it works is that it batches up model objects to save until its buffer is "full." Then it processes the models. If the queue does not reach max capacity within 30 seconds, there will be some models unprocessed. Its possible that this is getting executed later in your tests, causing this failure. I would switch to ```TransactionManager.getInstance().save(ProcessModel.withModels(reviews))```

**Comment by wongcain** [comment]
Actually I originally had `TransactionManager.getInstance().save(ProcessModel.withModels(reviews))` as you recommend.  I switched to the `saveOnSaveQueue()` trying to troubleshoot this problem.  I've now switched it back and still the same issue.

**Comment by wongcain** [comment]
Current DAO:
```
public class ReviewsDao {

    public ReviewsDao() {
    }

    public synchronized void saveList(List<Review> reviews){
        TransactionManager.getInstance().save(ProcessModelInfo.withModels(reviews));
    }

    public Review get(String key){
        return Select.byId(Review.class, key);
    }

}
```

**Comment by agrosner** [comment]
@wongcain I will look into this issue, but not sure what is happening. Does an issue like this happen in production running on the app?

**Comment by wongcain** [comment]
No, it's only an issue with unit testing, and probably specific to Robolectric.

**Comment by agrosner** [comment]
look at this @wongcain this may help: https://github.com/robolectric/robolectric/issues/569

**Comment by wongcain** [comment]
It seems that the problem is actually related to the FlowCursorList.  One of my other unit test was instantiating a FlowCursorList.  Event though I was calling "close()" on the object at the end of the test, it seemed to leave things in a bad state.  I've reworked my setup and now am only mocking the FlowCursorList, and all my tests run fine.  It might be worth looking into the FlowCursorList.close() method to ensure that it is freeing any resources that it should.

**Comment by agrosner** [comment]
@wongcain good to note I am checking this out now.

**Comment by agrosner** [comment]
@wongcain  its possible holding onto the ```Cursor``` reference after closing it causes the DB to still be open..A fix is on ```develop``` branch for 1.2.1

**Comment by agrosner** [comment]
ps @wongcain you are now listed as a Contributor. Thanks for your help and hope for you to continue and maybe at some point in the near future suggest / create pull requests for new features?

**Comment by wongcain** [comment]
Cool, and thanks for both the fix and listing me.  Yes I'll definitely suggest and/or implement fixes and features as I think of them.  It's a great library, and I'm happy to be contributor.
