### ISSUE TITLE
Model Caching always fail

### ISSUE THREAD

**Issue by vodkhang** [Raizlabs/DBFlow#352]
I am making a complicated object graph, so I need to cache some of the models. I just extend the BaseCacheableModel like this:
public class Match extends BaseCacheableModel {
}

but whenever I try to queryList the Match, I got the following exceptions:

08-07 10:37:27.840    4780-4780/com.zappasoft.prodigy E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: You cannot call this method for a table that has no caching id. Eitheruse one Primary Key or call convertToList()
            at com.raizlabs.android.dbflow.sql.SqlUtils.convertToCacheableList(SqlUtils.java:78)
            at com.raizlabs.android.dbflow.sql.SqlUtils.convertToCacheableList(SqlUtils.java:116)
            at com.raizlabs.android.dbflow.sql.SqlUtils.queryList(SqlUtils.java:54)
            at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:35)
            at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:347)
            at com.zappasoft.prodigy.dbflowmodels.Week.getWeekMatches(Week.java:67)
            at com.zappasoft.prodigy.utils.HeuristicEngine.generateSeasonData(HeuristicEngine.java:143)
            at com.zappasoft.prodigy.StateAndTeamSelectActivity.continueButtonPressed(StateAndTeamSelectActivity.java:108)
            at com.zappasoft.prodigy.StateAndTeamSelectActivity$1.onClick(StateAndTeamSelectActivity.java:94)
            at android.view.View.performClick(View.java:4232)
            at android.view.View$PerformClick.run(View.java:17318)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4921)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
            at dalvik.system.NativeStart.main(Native Method)

It stops at this line: 
            if(!instanceAdapter.hasCachingId()) {
                throw new IllegalArgumentException("You cannot call this method for a table that has no caching id. Eitheruse one Primary Key or call convertToList()");
            }
The problem is the ModelAdapter hasCachingID() always return false;

**Comment by kaeawc** [comment]
@vodkhang We use a BaseCacheableModel and it seems to work fine, we override `getCacheSize` to return `1` because we just need to cache one record. Are you actually trying to cache a list?

**Comment by agrosner** [comment]
`You cannot call this method for a table that has no caching id. Eitheruse one Primary Key`
@vodkhang can you show or send me what the generated class code file looks like `Match$Adapter` class? thanks.

**Comment by glureau** [comment]
@agrosner @kaeawc What if you have only one Primary key but with autoincrement=true? Looks like the generated code doesn't override the hasCachingId(), so is it impossible to use OnSpecificModelStateChangedListener in this case?
I have also tried to append my primary key in the URIs but it's still not working (despite the fact that getCachingColumnName() and getCachingId() returns the right values).

    @Override
    public Uri getDeleteUri() {
        return CONTENT_URI.buildUpon().appendQueryParameter("id", Long.toString(getId())).build();
    }

**Comment by agrosner** [comment]
fixed in 3.0, caching has been revamped.
