### ISSUE TITLE
DBFlow performs an insert instead of an update

### ISSUE THREAD

**Issue by ragunathjawahar** [Raizlabs/DBFlow#402]
When trying to save an object with the same primary key value, DBFlow performs an insert instead of an update. I inspected the DB on the device and could see the entry already exists.

````
Caused by: android.database.sqlite.SQLiteConstraintException: columns person_autoincrement_id, value are not unique (code 19)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:972)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:314)
	at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:268)
	at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:54)
	at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:50)
	at com.opentimeapp.opentime.models.person.elements.Email.save(Email.java:93)
	at com.opentimeapp.opentime.models.person.Person.save(Person.java:541)
	... 9 more
````

**Comment by woodcockjosh** [comment]
This can be fixed if you use "INSERT ON CONFLICT IGNORE"

**Comment by panzerfahrer** [comment]
Check your `Person` model: it most likely not up-to-date with what exists in the database. If you call `save` DBFlow checks if your model has the primary key field set, if it isn't it will perform an `INSERT`. Only if the primary key field is set will perform an `UPDATE`. This all happens without regards to whether the corresponding database entry actually exists.

**Comment by agrosner** [comment]
not sure if any longer valid in 3.0
