### ISSUE TITLE
Rename a column in a table

### ISSUE THREAD

**Issue by devilmac** [Raizlabs/DBFlow#421]
Hi Raizlabs,
I'm using this great ORM in my app and yesterday I faced on a question: how to rename a column in a table.
After a search on internet, I got that rename a column in SQLite is not an easy operation. What I found to do this is the following:
suppose you have a table like this:
``CREATE TABLE team(Name TEXT, Coach TEXT, City TEXT);``
and after you want to change column "City" in "Location", you have to follow steps below.
**Step 1:** Rename the original table:
``ALTER TABLE team RENAME TO team_orig;``
**Step 2:** Create the replacement table with the original name and corrected column name:
``CREATE TABLE team(Name TEXT, Coach TEXT, Location TEXT);``
**Step 3:** Copy the data from the original table to the new table:
``INSERT INTO team(Name, Coach, Location) SELECT Name, Coach, City FROM team_orig;``
**Step 4:** Drop the original table:
``DROP TABLE team_orig;``

I tried to put snippets above in a {dbVersion}.sql file inside /assets/migrations/{dbName}/ directory without success (I got the following error:

``java.lang.RuntimeException: android.database.sqlite.SQLiteException: not an error (code 0)
     at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:75)
  Caused by: android.database.sqlite.SQLiteException: not an error (code 0)
     at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
     at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1676)
     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
     at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper.executeSqlScript(FlowSQLiteOpenHelper.java:469)
     at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper.access$600(FlowSQLiteOpenHelper.java:37)
     at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper$4.run(FlowSQLiteOpenHelper.java:409)
     at com.raizlabs.android.dbflow.runtime.TransactionManager.transact(TransactionManager.java:108)
     at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper.executeMigrations(FlowSQLiteOpenHelper.java:400)
     at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper.onUpgrade(FlowSQLiteOpenHelper.java:315)
     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
     at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:165)
     at com.raizlabs.android.dbflow.sql.SqlUtils.queryList(SqlUtils.java:51)
     at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:35)
     at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:347)
     at com.raizlabs.android.dbflow.runtime.transaction.SelectListTransaction.onExecute(SelectListTransaction.java:73)
     at com.raizlabs.android.dbflow.runtime.transaction.SelectListTransaction.onExecute(SelectListTransaction.java:15)
     at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:61)``)

So, my question is: how can I do column renaming using class migration like ``AlterTableMigration<ModelClass extends Model>`` or others?

Thank you,

Federico

**Comment by agrosner** [comment]
no current functionality or support like that. Best bet is to keep the same column name but rename the variable:
```java

@Column(name = "oldName")
String newName;
```

**Comment by agrosner** [comment]
column names cannot be renamed with SQLite without creating a new table and inserting all data over from current into it, then renaming the new table to the original.
