### ISSUE TITLE
CursorWindow: Could not allocate CursorWindow

### ISSUE THREAD

**Issue by sowrabh** [Raizlabs/DBFlow#426]
```java
new Select().from(Student.class).queryList());
```
Calling the above code frequently caused tons of these errors in logcat -
```
10-15 11:38:26.544 26881-27374/<package name> E/CursorWindow: Could not allocate CursorWindow '/data/data/<package name>/databases/care.db' of size 2097152 due to error -12.
10-15 11:38:26.549 26881-27308/<package name> E/CursorWindow: Could not allocate CursorWindow '/data/data/<package name>/databases/care.db' of size 2097152 due to error -12.
```
and ultimately causing the query to fail 
```
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=491 (# cursors opened by this proc=491)
```
To diagnose the issue I enabled `StrictMode` which resulted in the below stack trace
```
10-15 17:10:01.478 20093-20106/<package name> E/StrictMode: Finalizing a Cursor that has not been deactivated or closed. database = /data/data/<package name>/databases/database.db, table = null, query = SELECT * FROM `Students`
10-15 17:10:01.478 20093-20106/<package name> E/StrictMode: android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
10-15 17:10:01.478 20093-20106/<package name> E/StrictMode:     at android.database.sqlite.SQLiteCursor.<init>(SQLiteCursor.java:98)
10-15 17:10:01.478 20093-20106/<package name> E/StrictMode:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:50)
10-15 17:10:01.478 20093-20106/<package name> E/StrictMode:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
10-15 17:10:01.478 20093-20106/<package name> E/StrictMode:     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
10-15 17:10:01.478 20093-20106/<package name> E/StrictMode:     at com.raizlabs.android.dbflow.sql.SqlUtils.queryList(SqlUtils.java:51)
10-15 17:10:01.478 20093-20106/<package name> E/StrictMode:     at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:35)
10-15 17:10:01.478 20093-20106/<package name> E/StrictMode:     at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:347)
10-15 17:10:01.478 20093-20106/<package name> E/StrictMode:     at com.raizlabs.android.dbflow.sql.language.From.queryList(From.java:165)
```
Looks like there's a leak of `Cursor` object somewhere. The code in `SqlUtils::queryList` didn't seem suspicious. Am I missing something here?

**Comment by agrosner** [comment]
probably due to `Cursor` not getting close from an error. added try..finally blocks to cursor ops to always close it after use when querying.
