### ISSUE TITLE
issue with AndroidAnnotations 4.0-SNAPSHOT

### ISSUE THREAD

**Issue by noinnion** [Raizlabs/DBFlow#429]
Hi, I am having an issue using DBFlow with androidannotations 4.0-SNAPSHOT

See this thread:
https://github.com/excilys/androidannotations/issues/1594

Seems Migration Annotation does something wrong in build process.

Thanks

**Comment by WonderCsabo** [comment]
Can you share your project?

**Comment by agrosner** [comment]
right, I have seen this error too. It's going to go on my radar to fix.

**Comment by agrosner** [comment]
```
Caused by: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.TypeElement
at com.raizlabs.android.dbflow.processor.handler.MigrationHandler.onProcessElement(MigrationHandler.java:23)
at com.raizlabs.android.dbflow.processor.handler.BaseContainerHandler.handle(BaseContainerHandler.java:23)
at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:278)
at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:85)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
at com.sun.tools.javac.main.Main.compile(Main.java:439)
```

**Comment by noinnion** [comment]
+1
will it be fixed in 3.0 or will be there a patch for 2.2.1?

**Comment by noinnion** [comment]
@WonderCsabo @agrosner 
I created a test project which causes the issue. But it only happens with AndroidAnnotation 4.0-SNAPSHOT. I don't know why it happened only there.

Download: https://dl.dropboxusercontent.com/u/3214472/DFAATest.zip

**Comment by agrosner** [comment]
This may occur if there are compile issues with generated code. in `develop`/3.0 added fix so this class cast doesnt occur, but it's most likely AndroidAnnotations fault.

**Comment by WonderCsabo** [comment]
@noinnion i checked out your project. It contained real errors related to your REST client. After i fixed those error, the project compiles, although i got some warnings.

warning: Attempt to recreate a file for type com.raizlabs.android.dbflow.config.Database$Database
warning: Attempt to recreate a file for type com.raizlabs.android.dbflow.config.Database$Database
warning: Attempt to recreate a file for type com.raizlabs.android.dbflow.config.Database$Database
warning: File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.

There are clearly coming for DBFlow. Actually your project does not have any class which could create a clash between AA and DBFlow.

**Comment by WonderCsabo** [comment]
Hey guys! @mathieudebrito also experienced a similar problem. In the investigation it turned out the root of the problem was that he was using `@NoTitle`, but that annotation was removed so that created a compile error and in the end resulted in an exception. You should check the annotation usages of AA 4.0 that you are using all annotations correctly. There will be a list of breaking changes of AA 4.0 when it is released.
