### ISSUE TITLE
TypeConverter with List ModelClass won't pass build

### ISSUE THREAD

**Issue by mariciv** [Raizlabs/DBFlow#43]
I'm trying to create TypeCoverter with ModelClass List instance that looks like this:

```java
@com.raizlabs.android.dbflow.annotation.TypeConverter
public class IntListTypeConverter extends TypeConverter<String, ArrayList<Integer>>{

    @Override
    public String getDBValue(ArrayList<Integer> model) {
        String dbValue = "";
        for(int i : model) {
            dbValue += i + ";";
        }
        dbValue = dbValue.substring(0, dbValue.length() - 1);
        return dbValue;
    }

    @Override
    public ArrayList<Integer> getModelValue(String data) {
        ArrayList<Integer> modelValue = new ArrayList<>();
        for(String s : data.split(";")){
            modelValue.add(Integer.parseInt(s));
        }
        return modelValue;
    }
```

The error I'm getting is:
` Error:Execution failed for task ':app:compileStagingDebugJava'.
  java.lang.NullPointerException`

And here is last part of stacktrace for more information:
`Caused by: java.lang.NullPointerException
        at com.raizlabs.android.dbflow.processor.definition.TypeConverterDefinition.getModelClassQualifiedName(TypeConverterDefinition.java:60)
        at com.raizlabs.android.dbflow.processor.model.ProcessorManager.addTypeConverterDefinition(ProcessorManager.java:96)
        at com.raizlabs.android.dbflow.processor.handler.TypeConverterHandler.onProcessElement(TypeConverterHandler.java:43)
        at com.raizlabs.android.dbflow.processor.handler.BaseContainerHandler.handle(BaseContainerHandler.java:25)
        at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:215)
        at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:85)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
        at com.sun.tools.javac.main.Main.compile(Main.java:439)`

If I change ModelClass type to any other class build passes but i can't get it to work with List. Can you please help me?

**Comment by agrosner** [comment]
Remove the type parameter for your ```TypeConverter```. It will not work with typed-types because type parameters are erased for the converters since ```List<Integer>.class``` is not a valid class name. You will need to extend ```ArrayList<Integer>``` into your own custom class so it can be handled properly.

**Comment by agrosner** [comment]
But yes @mariciv this should not crash so I will take this opportunity to A. warn and throw error for this, or B. do not crash
