### ISSUE TITLE
RuntimeException Failed to change locale for db to 'en_US'

### ISSUE THREAD

**Issue by evgenyh** [Raizlabs/DBFlow#440]
```java
Fatal Exception: java.lang.RuntimeException: Unable to start receiver me.truecontact.client.receiver.CallReceiver: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/me.truecontact.free/databases/TRUE_CONTACT.db' to 'en_US'.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java)
       at android.app.ActivityThread.access$1600(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/me.truecontact.free/databases/TRUE_CONTACT.db' to 'en_US'.
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java)
       at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(SourceFile)
       at com.raizlabs.android.dbflow.sql.SqlUtils.querySingle(SourceFile)
       at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(SourceFile)
       at com.raizlabs.android.dbflow.sql.language.Where.querySingle(SourceFile)
```

**Comment by agrosner** [comment]
are you changing locales on the database? not sure if this is a DBFlow issue here....

**Comment by franzejr** [comment]
I got a similar issue:

```
Fatal Exception: java.lang.RuntimeException: android.database.sqlite.SQLiteException: Failed to change locale for db '/storage/emulated/0/Android/data/com.habitrpg.android.habitica/files/HabiticaDatabase/Habitica.db' to 'es_ES'.
       at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:75)
Caused by android.database.sqlite.SQLiteException: Failed to change locale for db '/storage/emulated/0/Android/data/com.habitrpg.android.habitica/files/HabiticaDatabase/Habitica.db' to 'es_ES'.
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:459)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:250)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:203)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1169)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
       at com.habitrpg.android.habitica.HabiticaApplication.openOrCreateDatabase(HabiticaApplication.java:66)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:165)
       at com.raizlabs.android.dbflow.sql.SqlUtils.querySingle(SqlUtils.java:218)
       at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:40)
       at com.raizlabs.android.dbflow.sql.language.Where.querySingle(Where.java:366)
       at com.raizlabs.android.dbflow.runtime.transaction.SelectSingleModelTransaction.onExecute(SelectSingleModelTransaction.java:54)
       at com.raizlabs.android.dbflow.runtime.transaction.SelectSingleModelTransaction.onExecute(SelectSingleModelTransaction.java:13)
       at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:61)
Caused by android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:621)
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:437)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:250)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:203)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1169)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
       at com.habitrpg.android.habitica.HabiticaApplication.openOrCreateDatabase(HabiticaApplication.java:66)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:165)
       at com.raizlabs.android.dbflow.sql.SqlUtils.querySingle(SqlUtils.java:218)
       at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:40)
       at com.raizlabs.android.dbflow.sql.language.Where.querySingle(Where.java:366)
       at com.raizlabs.android.dbflow.runtime.transaction.SelectSingleModelTransaction.onExecute(SelectSingleModelTransaction.java:54)
       at com.raizlabs.android.dbflow.runtime.transaction.SelectSingleModelTransaction.onExecute(SelectSingleModelTransaction.java:13)
       at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:61)
```


Some hint?

**Comment by mathieudebrito** [comment]
Same here.
on Stackoverflow, they solved it by replacing 

``` SQLiteDatabase.openDatabase(myPath, null, SQLiteDatabase.OPEN_READWRITE);```

by 

```SQLiteDatabase.openDatabase(myPath, null, SQLiteDatabase.NO_LOCALIZED_COLLATORS | SQLiteDatabase.OPEN_READWRITE);```

(http://stackoverflow.com/questions/19491675/failed-to-change-locale-for-db-data-data-my-easymedi-controller-databases-easy)

**Comment by farkerhaiku** [comment]
I had this problem in a simple app because I was out of storage.  `adb shell "rm -rf /data/local/tmp"` fixed it.

**Comment by agrosner** [comment]
This functionality is not supported by the `SQLiteOpenHelper` in Android since it doesn't open the DB with the flag `SQLiteDatabase.NO_LOCALIZED_COLLATORS`. You may have to write your own custom `FlowSQLiteOpenHelper` to fix this.
