### ISSUE TITLE
Adding new column of type Date during migration makes the app to crash.

### ISSUE THREAD

**Issue by AntonioCappiello** [Raizlabs/DBFlow#448]
A migration strategy like the one below

```java
@Migration(version = 6, databaseName = "App")
public class Migration3 extends AlterTableMigration<AModel> {

    public Migration3() {
        super(AModel.class);
    }

    @Override
    public void onPreMigrate() {
        addColumn(Date.class, "date2");
    }
}
```
makes the app to crash with the following log messages:
```
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime: FATAL EXCEPTION: main
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime: Process: com.raizlabs.android.dbflow.app, PID: 26738
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.raizlabs.android.dbflow.app/com.raizlabs.android.dbflow.DemoActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.raizlabs.android.dbflow.sql.SQLiteType.name()' on a null object reference
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.raizlabs.android.dbflow.sql.SQLiteType.name()' on a null object reference
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.sql.QueryBuilder.appendSQLiteType(QueryBuilder.java:115)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.sql.QueryBuilder.appendType(QueryBuilder.java:105)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.sql.migration.AlterTableMigration.addColumn(AlterTableMigration.java:107)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.Migration3.onPreMigrate(Migration3.java:20)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper$4.run(FlowSQLiteOpenHelper.java:420)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.runtime.TransactionManager.transact(TransactionManager.java:108)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper.executeMigrations(FlowSQLiteOpenHelper.java:400)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper.onUpgrade(FlowSQLiteOpenHelper.java:315)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:165)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.sql.SqlUtils.hasData(SqlUtils.java:243)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.sql.language.Where.hasData(Where.java:376)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.AModel$Adapter.exists(AModel$Adapter.java:133)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.AModel$Adapter.exists(AModel$Adapter.java:12)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:262)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:54)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:50)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.raizlabs.android.dbflow.DemoActivity.onCreate(DemoActivity.java:28)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5990)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254) 
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
11-09 10:53:20.792 26738-26738/com.raizlabs.android.dbflow.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by agrosner** [comment]
It appears that you've added in invalid type to the migration statement. To fix this, use the database type-class of the column you're adding.

**Comment by agrosner** [comment]
for 3.0, you now have to use the `SQLiteType` specification so that it is more clear. Fixed in 3.0 branch

**Comment by AntonioCappiello** [comment]
This bug is connected to my PR https://github.com/Raizlabs/DBFlow/pull/449 done against the development branch where the SQLiteType is not used yet as in version 3.0.

> README.md
> ...
> 3 Pull requests must be made against develop branch.
> ...

Despite of the that, the type DATE is not part yet of the enumerator SQLiteType and of its relative HashMap, which cause the migration to fail anytime that we want to add a column with the Date type.

I believe that this issue is still open.

**Comment by eyal-fairfly** [comment]
I am trying to add a column of my own class which includes an int and a String an am getting the same crash.. Is it possible to add a column during migration of a custom class?

Thanks in advance.

**Comment by AntonioCappiello** [comment]
@eyal-fairfly could you post your code? it may be a different cause because int and String are correctly "mapped" by the library during migration. At least I have no problem with them.

**Comment by eyal-fairfly** [comment]
```
@Migration(version = 2, databaseName = name)

public class Version2MyClassMigration extends AlterTableMigration<MyClass> {

    public Version2MyClassMigration() {
        super(MyClass.class);

    }

    @Override
    public void onPreMigrate() {
        super.onPreMigrate();
        addColumn(MyClass2.class, "my_class2");
    }
    
}
...

public class MyClass2 implements Parcelable {

    public int status;
    public String result_id;

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(this.status);
        dest.writeString(this.result_id);
    }

    public MyClass2() {
    }

    protected MyClass2(Parcel in) {
        this.status = in.readInt();
        this.result_id = in.readString();
    }

    public static final Parcelable.Creator<MyClass2> CREATOR = new Parcelable.Creator<MyClass2>() {
        public MyClass2 createFromParcel(Parcel source) {
            return new MyClass2(source);
        }

        public MyClass2[] newArray(int size) {
            return new MyClass2[size];
        }
    };
}
```

And getting the error:
```
java.lang.RuntimeException: Unable to resume activity {com.fairfly.fairfly/com.fairfly.fairfly.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.raizlabs.android.dbflow.sql.SQLiteType.name()' on a null object reference
```

MyClass2 is defined with the @Column notation in MyClass.
When I change MyClass2 to a primitive everything works...

**Comment by mayank-kgp** [comment]
@eyal-fairfly Did you get any solution?

**Comment by mayank-kgp** [comment]
@agrosner What is the solution of this?
