### ISSUE TITLE
NPE when trying to Update entity

### ISSUE THREAD

**Issue by mykolado** [Raizlabs/DBFlow#454]
```
0 	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class com.raizlabs.android.dbflow.structure.ModelAdapter.getModelClass()' on a null object reference
! 	1 	at com.raizlabs.android.dbflow.sql.builder.ConditionQueryBuilder.getTableClass(ConditionQueryBuilder.java:112)
	2 	at com.raizlabs.android.dbflow.sql.language.Set.getTable(Set.java:140)
	3 	at com.raizlabs.android.dbflow.sql.language.Where.<init>(Where.java:67)
	4 	at com.raizlabs.android.dbflow.sql.language.Set.where(Set.java:107)
	5 	at com.raizlabs.android.dbflow.sql.language.Set.where(Set.java:98)
	6 	at co.hinge.mobile.android.data.model.queryhandler.MatchQueryHandler.updateWithShotClockStatusQuery(MatchQueryHandler.java:519)
```

**Comment by glureau** [comment]
Some code or a test to reproduce?

**Comment by agrosner** [comment]
yes be helpful to find out what's happening. as of 3.0, the `ConditionQueryBuilder` class is no more.
