### ISSUE TITLE
java.lang.NoSuchMethodError: com.raizlabs.android.dbflow.sql.builder.ConditionQueryBuilder.appendSpaceSeparated

### ISSUE THREAD

**Issue by evant** [Raizlabs/DBFlow#471]
Getting this stracktrace using version 2.2.1
```
java.lang.RuntimeException: java.lang.NoSuchMethodError: com.raizlabs.android.dbflow.sql.builder.ConditionQueryBuilder.appendSpaceSeparated
   at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:75)
Caused by: java.lang.NoSuchMethodError: com.raizlabs.android.dbflow.sql.builder.ConditionQueryBuilder.appendSpaceSeparated
   at com.raizlabs.android.dbflow.sql.builder.ConditionQueryBuilder.getQuery(ConditionQueryBuilder.java:137)
   at com.raizlabs.android.dbflow.sql.language.Where.getQuery(Where.java:297)
   at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:35)
   at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:350)
 ```

when attempting to use certain methods on the query builder. It appears this is due to the signature of `appendSpaceSeparated()` being changed from taking a String to and Object in DbFlow-Core (https://github.com/Raizlabs/DBFlow/commit/6bc63a7f102eab1ad59b3128fc1ebe7a2049d9e0) but DbFlow not being recompiled. Please recompile and upload a new version that fixes this.

**Comment by evant** [comment]
Was actually not an issue with the library, was depending on inconsistent versions
```groovy
    apt 'com.raizlabs.android:DBFlow-Compiler:2.2.1'
    compile "com.raizlabs.android:DBFlow-Core:2.2.1"
    compile "com.raizlabs.android:DBFlow:2.1.0"
```
