### ISSUE TITLE
[3.0] ClassCastException: java.util.LinkedHashMap cannot be cast to com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer

### ISSUE THREAD

**Issue by simplysoft** [Raizlabs/DBFlow#472]
```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer
	at com.app.android.data.db.WebService_Container.loadFromCursor(WebService_Container.java:276)
	at com.app.android.data.db.WebService_Container.loadFromCursor(WebService_Container.java:21)
	at com.raizlabs.android.dbflow.sql.SqlUtils.convertToModelContainer(SqlUtils.java:198)
	at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryModelContainer(BaseModelQueriable.java:47)
	at com.app.android.data.db.Pass_Adapter.loadFromCursor(Pass_Adapter.java:925)
	at com.app.android.data.db.Pass_Adapter.loadFromCursor(Pass_Adapter.java:31)
	at com.raizlabs.android.dbflow.sql.SqlUtils.convertToList(SqlUtils.java:144)
	at com.raizlabs.android.dbflow.sql.SqlUtils.queryList(SqlUtils.java:62)
	at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:37)
	at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:246)
	at com.raizlabs.android.dbflow.sql.language.From.queryList(From.java:122)
```

the offending line looks like this:
```
	    modelContainer.put("passType",
          (com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer<com.app.android.data.db.PassType>) new com.raizlabs.android.dbflow.sql.language.Select()
              .from(com.app.android.data.db.PassType.class)
              .where()
              .and(com.app.android.data.db.PassType_Table.pid.eq(
                  cursor.getLong(indexpass_type_pid)))
              .queryModelContainer(modelContainer.getInstance(modelContainer.newDataInstance(),
                  com.app.android.data.db.PassType.class))
              .getData());
```

Any Idea where the problem is? Is `modelContainer.newDataInstance()` wrong or is the cast wrong?

**Comment by agrosner** [comment]
I think I see the issue. For any sense, can you paste your model class where this is happening. Thank you.

**Comment by simplysoft** [comment]
sure, here you go
```
@Table(name = "web_service", database = Database.class)
@ModelContainer
public class WebService extends BaseModel {

  @Column
  @PrimaryKey(autoincrement = true)
  long pid;

  @Column
  @ForeignKey(
      references = {@ForeignKeyReference(columnName = "pass_type_pid",
          columnType = long.class,
          foreignKeyColumnName = "pid")},
      saveForeignKeyModel = false)
  ForeignKeyContainer<PassType> passType;

  @Column(name = "service_url") String serviceUrl;

  public void associatePassType(PassType passType) {
    this.passType = FlowManager.getContainerAdapter(PassType.class).toForeignKeyContainer(passType);
  }
}
```

**Comment by agrosner** [comment]
fixed in `develop` now.
