### ISSUE TITLE
Upgrading android studio, google repository and sdk version dbflow throws runtime exception

### ISSUE THREAD

**Issue by saurabhghewari** [Raizlabs/DBFlow#482]
Below is the runtime exception.
This exception occurs when I build the app on api 16 android devices, else this error does not occur when I build app on api 21 or higher.

 java.lang.RuntimeException: Unable to create application com.wiksate.DBManager.ApplnWiksateDBFlow: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4154)
                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:130)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                               at android.os.Looper.loop(Looper.java:137)
                                                               at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                               at dalvik.system.NativeStart.main(Native Method)
                                                            Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
                                                               at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:109)
                                                               at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:147)
                                                               at com.wiksate.DBManager.ApplnWiksateDBFlow.onCreate(ApplnWiksateDBFlow.java:24)
                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:130) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                               at android.os.Looper.loop(Looper.java:137) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                            Caused by: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
                                                               at java.lang.Class.classForName(Native Method)
                                                               at java.lang.Class.forName(Class.java:217)
                                                               at java.lang.Class.forName(Class.java:172)
                                                               at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:107)
                                                               at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:147) 
                                                               at com.wiksate.DBManager.ApplnWiksateDBFlow.onCreate(ApplnWiksateDBFlow.java:24) 
                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151) 
                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:130) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                               at android.os.Looper.loop(Looper.java:137) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                            Caused by: java.lang.NoClassDefFoundError: com/raizlabs/android/dbflow/config/GeneratedDatabaseHolder
                                                               at java.lang.Class.classForName(Native Method) 
                                                               at java.lang.Class.forName(Class.java:217) 
                                                               at java.lang.Class.forName(Class.java:172) 
                                                               at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:107) 
                                                               at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:147) 
                                                               at com.wiksate.DBManager.ApplnWiksateDBFlow.onCreate(ApplnWiksateDBFlow.java:24) 
                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151) 
                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:130) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                               at android.os.Looper.loop(Looper.java:137) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                            Caused by: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                               at java.lang.Class.classForName(Native Method) 
                                                               at java.lang.Class.forName(Class.java:217) 
                                                               at java.lang.Class.forName(Class.java:172) 
                                                               at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:107) 
                                                               at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:147) 
                                                               at com.wiksate.DBManager.ApplnWiksateDBFlow.onCreate(ApplnWiksateDBFlow.java:24) 
                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151) 
                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:130) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                               at android.os.Looper.loop(Looper.java:137) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                               at dalvik.system.NativeStart.main(Native Method) 

This is my gradle config:
App level build.gradle:-
apt 'com.raizlabs.android:DBFlow-Compiler:1.8.0'
compile 'com.raizlabs.android:DBFlow-Core:1.8.0'
compile 'com.raizlabs.android:DBFlow:1.8.0'

project level build.gradle
classpath 'com.raizlabs:Griddle:1.0.3'

Where I am going wrong.
**Also note:- I have integrated the google analytics, and from that onwards this runtime exception occurs for every build for api 16 device.

**Comment by romulof** [comment]
Try cleaning up. I've had several build and runtime problems when updating libraries without cleaning up.

**Comment by saurabhghewari** [comment]
Yeah thanks for the quick reply. But I solved it. The problem was with the "multiDEXEnabled true". Need put under the dependencies of gradle file.
