### ISSUE TITLE
[3.0.0-beta1] @QueryModel Annotation causes ClassCastException (TableDefinition.class)

### ISSUE THREAD

**Issue by graf-semmel** [Raizlabs/DBFlow#504]
When I use the @QueryModel Annotation I get the following ClassCastException

```java
Error:Execution failed for task ':provider:compileReleaseJavaWithJavac'.
java.lang.ClassCastException:
com.raizlabs.android.dbflow.processor.definition.QueryModelDefinition
cannot be cast to com.raizlabs.android.dbflow.processor.definition.TableDefinition
```

**Comment by lnikkila** [comment]
Same happens to @ModelView, here’s the stack trace:

```
java.lang.ClassCastException: com.raizlabs.android.dbflow.processor.definition.ModelViewDefinition cannot be cast to com.raizlabs.android.dbflow.processor.definition.TableDefinition
        at com.raizlabs.android.dbflow.processor.definition.method.LoadFromCursorMethod.getMethodSpec(LoadFromCursorMethod.java:66)
        at com.raizlabs.android.dbflow.processor.definition.ModelViewDefinition.onWriteDefinition(ModelViewDefinition.java:221)
        at com.raizlabs.android.dbflow.processor.definition.BaseDefinition.getTypeSpec(BaseDefinition.java:109)
        at com.raizlabs.android.dbflow.processor.utils.WriterUtils.writeBaseDefinition(WriterUtils.java:17)
        at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:291)
        at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:98)
```

**Comment by agrosner** [comment]
fixed in `develop`
