### ISSUE TITLE
Adding column to existing Database

### ISSUE THREAD

**Issue by mustansarsaeed** [Raizlabs/DBFlow#520]
Hi Raizlabs,

I am using this library and its working perfectly fine. I am trying to add new column "temp_comments" to existing database but getting the sqliteexception. I have also updated the database version. I am using following libraries:
compile 'com.raizlabs.android:DBFlow-Core:2.2.1'
compile 'com.raizlabs.android:DBFlow:2.2.1'
 
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          android.database.sqlite.SQLiteException: table TempFormData has no column named TEMP_COMMENTS (code 1): , while compiling: INSERT INTO `TempFormData` (`TEMP_FORMDATA`, `TEMP_INCHARGENAME`, `TEMP_INCHARGEPHONENUMBER`, `TEMP_FACILITYTYPE`, `TEMP_FACILITYNAME`, `TEMP_DISTRICTNAME`, `TEMP_TEHSILNAME`, `TEMP_TEHSILID`, `TEMP_COMMENTS`, `TEMP_FACILITY_TYPE_CODE`, `TEMP_FACILITYID`, `TEMP_DISTRICTID`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                                                                              at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                              at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:891)
                                                                              at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
                                                                              at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                              at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                              at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                              at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:992)
                                                                              at com.raizlabs.android.dbflow.structure.ModelAdapter.getInsertStatement(ModelAdapter.java:29)
                                                                              at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:312)
                                                                              at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:268)
                                                                              at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:54)
                                                                              at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:50)

Can you please assist me how I can add new column?

**Comment by TheWhiteLlama** [comment]
Have you already tried one of the helper classes for a table migration (e.g. UpdateTableMigration / AlterTableMigration)?

**Comment by mustansarsaeed** [comment]
Yes I have tried and worked perfectly using AlterTableMigration. Thanks for your help.

**Comment by mayank-kgp** [comment]
@mustansarsaeed Can you please share the code which you have added?
