### ISSUE TITLE
Method.max(IProperty).as(...) breaks the sql statement 

### ISSUE THREAD

**Issue by GNima** [Raizlabs/DBFlow#523]
When assigning an alias to a method, the sql statement breaks. Example:

```java
    WifiEvent wifiEvent =
        SQLite.select(WifiEvent_Table.SSID, WifiEvent_Table.BSSID, WifiEvent_Table.capability,
            WifiEvent_Table.channel, WifiEvent_Table.eventType, WifiEvent_Table.frequency,
            WifiEvent_Table.latitude, WifiEvent_Table.longitude, WifiEvent_Table.level,
            WifiEvent_Table.operatorFriendlyName, WifiEvent_Table.venueName,
            Method.max(WifiEvent_Table.timestamp).as("something"))
            .from(WifiEvent.class)
            .where(WifiEvent_Table.BSSID.eq(bssid))
            .groupBy(WifiEvent_Table.BSSID)
            .querySingle();
```
```
android.database.sqlite.SQLiteException: no such column: MAX (code 1): , while compiling: SELECT `SSID`,`BSSID`,`capability`,`channel`,`eventType`,`frequency`,`latitude`,`longitude`,`level`,`operatorFriendlyName`,`venueName`,`MAX` AS `something` FROM `wlan_events` WHERE `BSSID`='06:7c:34:a3:0e:34' GROUP BY `BSSID` LIMIT 1
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by GNima** [comment]
MAX AS something is wrong, it should be MAX(timestamp) AS something

**Comment by graf-semmel** [comment]
This problem occures at all methods. But you can use this hack. 
```java
...new OperationalMethod(Method.max(WifiEvent_Table.timestamp)).as("something")...
```

**Comment by agrosner** [comment]
fixed in `develop`. Removed `OperationalMethod` by merging it's logic with `Method` to work as one would expect.
