### ISSUE TITLE
No way to set primary, boolean, Model and enum fields to be private

### ISSUE THREAD

**Issue by re3lex** [Raizlabs/DBFlow#528]
hi,
I have found the following issue: even in case my private fields have correct getter/setter DBFLow cannot use them and throws error. 
For example I have the following class that I got from Getting started guide and added private modifiers to fields

```
@ModelContainer
@Table(database = ColonyDatabase.class, useIsForPrivateBooleans = true)
public class Ant extends BaseModel {

  @PrimaryKey(autoincrement = true)
  private Long id;

  @Column
  private Type type;

  @Column
   private boolean male;

  @ForeignKey
   private Queen queen;

  public Queen getQueen() {
    return queen;
  }

  public void setQueen(Queen queen) {
    this.queen = queen;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Type getType() {
    return type;
  }

  public void setType(Type type) {
    this.type = type;
  }

  public boolean isMale() {
    return male;
  }

  public void setMale(boolean male) {
    this.male = male;
  }

  public enum Type {
    TYPE1,
    TYPE2
  }
}
```

while Primary column has private modifier I'm getting the following issue during compilation:
```
Caused by: java.lang.NullPointerException
	at com.raizlabs.android.dbflow.processor.definition.column.PrivateColumnAccess.<init>(PrivateColumnAccess.java:20)
	at com.raizlabs.android.dbflow.processor.definition.column.ColumnDefinition.<init>(ColumnDefinition.java:108)
	at com.raizlabs.android.dbflow.processor.definition.column.ColumnDefinition.<init>(ColumnDefinition.java:227)
	at com.raizlabs.android.dbflow.processor.definition.TableDefinition.createColumnDefinitions(TableDefinition.java:307)
	at com.raizlabs.android.dbflow.processor.definition.TableDefinition.<init>(TableDefinition.java:192)
	at com.raizlabs.android.dbflow.processor.handler.TableHandler.onProcessElement(TableHandler.java:32)
	at com.raizlabs.android.dbflow.processor.handler.BaseContainerHandler.handle(BaseContainerHandler.java:23)
	at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:257)
```

While ForeignKey field has private modifier I'm getting the following issue during compilation:
```
Caused by: java.lang.NullPointerException
	at com.raizlabs.android.dbflow.processor.definition.column.PrivateColumnAccess.<init>(PrivateColumnAccess.java:20)
	at com.raizlabs.android.dbflow.processor.definition.column.ColumnDefinition.<init>(ColumnDefinition.java:108)
	at com.raizlabs.android.dbflow.processor.definition.column.ColumnDefinition.<init>(ColumnDefinition.java:227)
	at com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition.<init>(ForeignKeyColumnDefinition.java:59)
	at com.raizlabs.android.dbflow.processor.definition.TableDefinition.createColumnDefinitions(TableDefinition.java:305)
	at com.raizlabs.android.dbflow.processor.definition.TableDefinition.<init>(TableDefinition.java:192)
	at com.raizlabs.android.dbflow.processor.handler.TableHandler.onProcessElement(TableHandler.java:32)
	at com.raizlabs.android.dbflow.processor.handler.BaseContainerHandler.handle(BaseContainerHandler.java:23)
	at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:257)
```

While Type enum field has private modifier I'm getting the following issue during compilation:
`Error:(48, 15) error: type has private access in Ant` in autogenerated Ant_Adapter:
```
  public final void bindToInsertValues(ContentValues values, Ant model) {
    String reftype = model.getType() != null ? model.getType().name() : null;
    if ((model.type != null) && (reftype != null)) { //<<<<------ Issue is here: type is private
      values.put("`type`", reftype);
    } else {
      values.putNull("`type`");
    }
    values.put("`male`", model.male ? 1 : 0);
    if (model.queen != null) {
      values.put("`queen_id`", model.queen.id);
      model.queen.save();
    } else {
      values.putNull("`queen_id`");
    }
  }
```

While boolean field has private modifier I'm getting error in generated Ant_Container class:
`Error:(74, 61) error: incompatible types: int cannot be converted to boolean`
this is happening because in autogenerated Ant_Container class boolean `male` field is tried to be bind as LONG in bindToInsertStatement() method:
`statement.bindLong(2 + start, modelContainer.getIntValue("male") ? 1 : 0);`

**Comment by agrosner** [comment]
thanks for the help!! This really helped me find some bugs. All fixed in `develop` now.
