### ISSUE TITLE
Error:java.lang.NullPointerException

### ISSUE THREAD

**Issue by perchi** [Raizlabs/DBFlow#534]
I tried to generate a content provider, but i got the exception:

	at com.raizlabs.android.dbflow.processor.definition.method.provider.QueryMethod.getMethodSpec(QueryMethod.java:50)
	at com.raizlabs.android.dbflow.processor.definition.ContentProviderDefinition.onWriteDefinition(ContentProviderDefinition.java:164)
	at com.raizlabs.android.dbflow.processor.definition.BaseDefinition.getTypeSpec(BaseDefinition.java:109)
	at com.raizlabs.android.dbflow.processor.utils.WriterUtils.writeBaseDefinition(WriterUtils.java:17)
	at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:264)
	at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:98)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)

**Comment by perchi** [comment]
There is a bug in the documentation: 

@Table(database = ContentDatabase.class, tableName = ContentProviderModel.NAME)

but I removed "tableName" instead of rename it to "name" :)
