### ISSUE TITLE
NullPointer when calling `ForeignKeyContainer#toModel()` on a foreign key with a null relationship.

### ISSUE THREAD

**Issue by arriolac** [Raizlabs/DBFlow#538]
I have the following models:

```
@ModelContainer @Table(database = Database.class) public class Image extends Entity {
    @PrimaryKey @Column long id;
    @Column String url;
}

@ModelContainer @Table(database = Database.class) public class Channel extends Entity {
    @PrimaryKey @Column long id;
    @Column @ForeignKey(saveForeignKeyModel = false) Image image;
}

@ModelContainer @Table(database = Database.class) public class ChannelUser extends Entity {
    @PrimaryKey @Column long id;
    @Column @ForeignKey(saveForeignKeyModel = false) ForeignKeyContainer<Channel> channel;

    public Channel getChannel() {
         this.channel.toModel()
    }
```

When I construct a `Channel` with a null image followed by a `ChannelUser` referencing that `Channel`, calling `ChannelUser#getChannel()` returns a NPE.

```
                         E  FATAL EXCEPTION: main
                         E  Process: com.app, PID: 7130
                         E  java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
                         E      at com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer.getValue(ForeignKeyContainer.java:62)
                         E      at com.raizlabs.android.dbflow.structure.container.SimpleModelContainer.getLongValue(SimpleModelContainer.java:47)
                         E      at com.raizlabs.android.dbflow.structure.container.SimpleModelContainer.getLngValue(SimpleModelContainer.java:61)
                         E      at com.app.models.Image_Container.toModel(Image_Container.java:123)
                         E      at com.app.models.Image_Container.toModel(Image_Container.java:22)
                         E      at com.app.models.Channel_Container.toModel(Channel_Container.java:175)
```

**Comment by arriolac** [comment]
The problem seems to be with the generated `Channel_Container#toModel()` method which incorrectly checks the wrong object for `null`.

Currently:
```
    ModelContainer<User, ?> refimage = modelContainer.getInstance(modelContainer.getValue("image"), com.app.models.Image.class);
    if (refimage != null) {
      model.image = com.raizlabs.android.dbflow.config.FlowManager.getContainerAdapter(com.app.models.Image.class).toModel(refimage);
    }
```

...but should be (?):

```
    ModelContainer<User, ?> refimage = modelContainer.getInstance(modelContainer.getValue("image"), com.app.models.Image.class);
    if (refimage != null && refimage.toModel() != null) { // should check .toModel()
      model.image = com.raizlabs.android.dbflow.config.FlowManager.getContainerAdapter(com.app.models.Image.class).toModel(refimage);
    }
```

Will send a patch as soon as I can but not too familiar with annotation processing so might take me a bit.

**Comment by arriolac** [comment]
I was able to address this issue by calling `.load()` on channel instead of `.toModel()`. The docs indicate that `.toModel()` should be called to load an object—should this be corrected? When should one be called over the other?

**Comment by agrosner** [comment]
use `load()` in `ForeignKeyContainer` as it loads the relationship - I made it more clear in the docs. `toModel()` simply converts its underlying data into a `Model` representation of the `ModelContainer` data.

**Comment by arriolac** [comment]
@agrosner thanks!
