### ISSUE TITLE
Android Studio 2.0-EAP Problem (Instant Run)

### ISSUE THREAD

**Issue by mblcdr** [Raizlabs/DBFlow#547]
As you may know with version 2.0 of Android Studio, Google introduced Instant Run, which uses technics like multidex and/or APK split to hot swap changes of the application, which prevents complete installation of the whole package and results in a super fast relaunch of the current activity.

However there seems to be a problem when using DBFlow. It crashes the app with the following exception:
```Java
java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: java.lang.RuntimeException: java.lang.IllegalAccessError: Method 'void com.raizlabs.android.dbflow.config.DatabaseHolder.putDatabaseForTable(java.lang.Class, com.raizlabs.android.dbflow.config.BaseDatabaseDefinition)' is inaccessible to class 'com.raizlabs.android.dbflow.config.user_suggestion$Database' (declaration of 'com.raizlabs.android.dbflow.config.user_suggestion$Database' appears in /data/data/com.example.app.down/files/studio-fd/dex/slice-slice_9_3a738c38dde5b94284893c9599d6233e0348259d-classes.dex)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
    at android.app.ActivityThread.access$1500(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5221)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: Method 'void com.raizlabs.android.dbflow.config.DatabaseHolder.putDatabaseForTable(java.lang.Class, com.raizlabs.android.dbflow.config.BaseDatabaseDefinition)' is inaccessible to class 'com.raizlabs.android.dbflow.config.user_suggestion$Database' (declaration of 'com.raizlabs.android.dbflow.config.user_suggestion$Database' appears in /data/data/com.example.app.down/files/studio-fd/dex/slice-slice_9_3a738c38dde5b94284893c9599d6233e0348259d-classes.dex)
    at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:119)
    at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:158)
    at com.example.app.MyApplication.onCreate(MyApplication.java:51)
    at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:305)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
    at android.app.ActivityThread.access$1500(ActivityThread.java:144) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5221) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
Caused by: java.lang.IllegalAccessError: Method 'void com.raizlabs.android.dbflow.config.DatabaseHolder.putDatabaseForTable(java.lang.Class, com.raizlabs.android.dbflow.config.BaseDatabaseDefinition)' is inaccessible to class 'com.raizlabs.android.dbflow.config.user_suggestion$Database' (declaration of 'com.raizlabs.android.dbflow.config.user_suggestion$Database' appears in /data/data/com.example.app.down/files/studio-fd/dex/slice-slice_9_3a738c38dde5b94284893c9599d6233e0348259d-classes.dex)
    at com.raizlabs.android.dbflow.config.user_suggestion$Database.<init>(user_suggestion$Database.java:10)
    at com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder.<init>(GeneratedDatabaseHolder.java:6)
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at java.lang.Class.newInstance(Class.java:1572)
    at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:117)
    at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:158) 
    at com.example.app.MyApplication.onCreate(MyApplication.java:51) 
    at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:305) 
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011) 
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518) 
    at android.app.ActivityThread.access$1500(ActivityThread.java:144) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5221) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372)
```

I suppose making ```putDatabaseForTable``` public would solve this issue.

**Comment by agrosner** [comment]
made it public :) try now
