### ISSUE TITLE
3.0.0-beta2 table insertConflict being ignored

### ISSUE THREAD

**Issue by dwaynehoy** [Raizlabs/DBFlow#576]
I'm getting the following exception when attempting to insert an row that is already in the database

```

 android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: PointOfInterest._id (code 1555)
                                                                                at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                                at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:780)
                                                                                at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                                at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                                at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.executeInsert(AndroidDatabaseStatement.java:73)
                                                                                at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:370)
                                                                                at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:327)
                                                                                at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:60)
                                                                                at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:50)
```

Probably incorrectly, I presumed that when adding the insertConflict annotation parameter that the complied insert statement would contain *insert or update ...*, however this doesn't appear to be the case? Is this an issue or am I doing it wrong?

Relevant code below, please let me know if you need anything else.

PointOfInterest
```
@Table(database = CacheDatabase.class, insertConflict = ConflictAction.REPLACE)
public class PointOfInterest extends BaseModel {

    @PrimaryKey
    @Column(name = "_id")
    private long id;
...
```

PointOfInterest_Adapter insert statements
```
@Override
  public final String getInsertStatementQuery() {
    return "INSERT INTO `PointOfInterest`(`_id`,`siteKey`,`name`,`description`,`latitude`,`longitude`,`siteCategoryId`,`shareUrl`,`categoryForeignKey__id`) VALUES (?,?,?,?,?,?,?,?,?)";
  }

  @Override
  public final String getCompiledStatementQuery() {
    return "INSERT INTO `PointOfInterest`(`_id`,`siteKey`,`name`,`description`,`latitude`,`longitude`,`siteCategoryId`,`shareUrl`,`categoryForeignKey__id`) VALUES (?,?,?,?,?,?,?,?,?)";
  }
```

**Comment by agrosner** [comment]
fixed in `develop`.
