### ISSUE TITLE
NullPointerException at DatabaseHelperDelegate

### ISSUE THREAD

**Issue by MrDeus** [Raizlabs/DBFlow#591]
I'm trying to generate content provider through DBFlow but have been failing due to this NullPointer issue. I cant seem to find any valid reason to this. Appreciate some assistance. Having similar issue for both beta1 and beta 2.

```

> java.lang.NullPointerException: Attempt to invoke virtual method 'void com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.onCreate(com.raizlabs.android.dbflow.structure.database.DatabaseWrapper)' on a null object reference
> at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.onCreate(FlowSQLiteOpenHelper.java:83)
> at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper$1.onCreate(FlowSQLiteOpenHelper.java:35)
> at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
> at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
> at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper$BackupHelper.getDatabase(FlowSQLiteOpenHelper.java:110)
> at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.<init>(DatabaseHelperDelegate.java:69)
> at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.<init>(FlowSQLiteOpenHelper.java:45)
> at com.raizlabs.android.dbflow.config.AppDbAppDatabase_Database.createHelper(AppDbAppDatabase_Database.java:22)
> at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getHelper(BaseDatabaseDefinition.java:159)
> at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:169)
> at io.peronda.android.provider.AppProvider_Provider.insert(AppProvider_Provider.java:84)
> at android.content.ContentProvider$Transport.insert(ContentProvider.java:238)
> at android.content.ContentResolver.insert(ContentResolver.java:1217)
> at com.raizlabs.android.dbflow.structure.provider.ContentUtils.insert(ContentUtils.java:85)
> at io.peronda.android.test.provider.ContentProviderTest.testCreate(ContentProviderTest.java:44)
> at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
> at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
> at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
> at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1873)`

```

**Comment by MrDeus** [comment]
Found out the reason. If the backupEnabled to true, that DatabaseHelperDelegate will become null and crashed the app.

**Comment by agrosner** [comment]
this is probably a side effect of the change to support SQLCipher. let me look at this.

**Comment by agrosner** [comment]
fixed in `develop`. thanks!
