### ISSUE TITLE
Boolean field persister not working in DBFlow.

### ISSUE THREAD

**Issue by deveshmittal** [Raizlabs/DBFlow#610]
I am using DBFlow as the ORM solution for my database. It is able to create table when persisting all the other primitive fields ie int, long , string but it is not able to create table when I try to persist a boolean field.
```
    @Column
    private Boolean isGroupBooking;
```
I get the following stacktrace.
```
Information:Gradle tasks [:app:assembleDebug]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preDemoBuild UP-TO-DATE
:app:preProdBuild UP-TO-DATE
:app:preReleaseBuild UP-TO-DATE
:libraries:datewidget:preBuild UP-TO-DATE
:libraries:datewidget:preReleaseBuild UP-TO-DATE
:libraries:datewidget:compileReleaseNdk UP-TO-DATE
:libraries:datewidget:compileLint
:libraries:datewidget:copyReleaseLint UP-TO-DATE
:libraries:datewidget:checkReleaseManifest
:libraries:datewidget:preDebugAndroidTestBuild UP-TO-DATE
:libraries:datewidget:preDebugBuild UP-TO-DATE
:libraries:datewidget:preDebugUnitTestBuild UP-TO-DATE
:libraries:datewidget:preReleaseUnitTestBuild UP-TO-DATE
:libraries:datewidget:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:libraries:datewidget:prepareComAndroidSupportDesign2310Library UP-TO-DATE
:libraries:datewidget:prepareComAndroidSupportPercent2311Library UP-TO-DATE
:libraries:datewidget:prepareComAndroidSupportRecyclerviewV72310Library UP-TO-DATE
:libraries:datewidget:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:libraries:datewidget:prepareComJakewhartonTimberTimber410Library UP-TO-DATE
:libraries:datewidget:prepareNetDanlewAndroidJoda281Library UP-TO-DATE
:libraries:datewidget:prepareReleaseDependencies
:libraries:datewidget:compileReleaseAidl UP-TO-DATE
:libraries:datewidget:compileReleaseRenderscript UP-TO-DATE
:libraries:datewidget:generateReleaseBuildConfig UP-TO-DATE
:libraries:datewidget:generateReleaseAssets UP-TO-DATE
:libraries:datewidget:mergeReleaseAssets UP-TO-DATE
:libraries:datewidget:generateReleaseResValues UP-TO-DATE
:libraries:datewidget:generateReleaseResources UP-TO-DATE
:libraries:datewidget:mergeReleaseResources UP-TO-DATE
:libraries:datewidget:processReleaseManifest UP-TO-DATE
:libraries:datewidget:processReleaseResources UP-TO-DATE
:libraries:datewidget:generateReleaseSources UP-TO-DATE
:libraries:datewidget:compileReleaseJavaWithJavac UP-TO-DATE
:libraries:datewidget:extractReleaseAnnotations UP-TO-DATE
:libraries:datewidget:mergeReleaseProguardFiles UP-TO-DATE
:libraries:datewidget:packageReleaseRenderscript UP-TO-DATE
:libraries:datewidget:packageReleaseResources UP-TO-DATE
:libraries:datewidget:processReleaseJavaRes UP-TO-DATE
:libraries:datewidget:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:libraries:datewidget:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:libraries:datewidget:mergeReleaseJniLibFolders UP-TO-DATE
:libraries:datewidget:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:libraries:datewidget:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:libraries:datewidget:bundleRelease UP-TO-DATE
:libraries:fliplib:preBuild UP-TO-DATE
:libraries:fliplib:preReleaseBuild UP-TO-DATE
:libraries:fliplib:compileReleaseNdk UP-TO-DATE
:libraries:fliplib:compileLint
:libraries:fliplib:copyReleaseLint UP-TO-DATE
:libraries:fliplib:checkReleaseManifest
:libraries:fliplib:preDebugAndroidTestBuild UP-TO-DATE
:libraries:fliplib:preDebugBuild UP-TO-DATE
:libraries:fliplib:preDebugUnitTestBuild UP-TO-DATE
:libraries:fliplib:preReleaseUnitTestBuild UP-TO-DATE
:libraries:fliplib:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:libraries:fliplib:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:libraries:fliplib:prepareReleaseDependencies
:libraries:fliplib:compileReleaseAidl UP-TO-DATE
:libraries:fliplib:compileReleaseRenderscript UP-TO-DATE
:libraries:fliplib:generateReleaseBuildConfig UP-TO-DATE
:libraries:fliplib:generateReleaseAssets UP-TO-DATE
:libraries:fliplib:mergeReleaseAssets UP-TO-DATE
:libraries:fliplib:generateReleaseResValues UP-TO-DATE
:libraries:fliplib:generateReleaseResources UP-TO-DATE
:libraries:fliplib:mergeReleaseResources UP-TO-DATE
:libraries:fliplib:processReleaseManifest UP-TO-DATE
:libraries:fliplib:processReleaseResources UP-TO-DATE
:libraries:fliplib:generateReleaseSources UP-TO-DATE
:libraries:fliplib:compileReleaseJavaWithJavac UP-TO-DATE
:libraries:fliplib:extractReleaseAnnotations UP-TO-DATE
:libraries:fliplib:mergeReleaseProguardFiles UP-TO-DATE
:libraries:fliplib:packageReleaseRenderscript UP-TO-DATE
:libraries:fliplib:packageReleaseResources UP-TO-DATE
:libraries:fliplib:processReleaseJavaRes UP-TO-DATE
:libraries:fliplib:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:libraries:fliplib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:libraries:fliplib:mergeReleaseJniLibFolders UP-TO-DATE
:libraries:fliplib:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:libraries:fliplib:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:libraries:fliplib:bundleRelease UP-TO-DATE
:app:prepareBumble_bee_androidLibrariesDatewidgetUnspecifiedLibrary UP-TO-DATE
:app:prepareBumble_bee_androidLibrariesFliplibUnspecifiedLibrary UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:app:prepareComAndroidSupportCardviewV72311Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2311Library UP-TO-DATE
:app:prepareComAndroidSupportPercent2311Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72311Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:app:prepareComBignerdranchAndroidRecyclerviewMultiselect02Library UP-TO-DATE
:app:prepareComCrashlyticsSdkAndroidAnswers136Library UP-TO-DATE
:app:prepareComCrashlyticsSdkAndroidBeta114Library UP-TO-DATE
:app:prepareComCrashlyticsSdkAndroidCrashlytics255Library UP-TO-DATE
:app:prepareComCrashlyticsSdkAndroidCrashlyticsCore238Library UP-TO-DATE
:app:prepareComFernandocejasFrodoFrodoRuntime082Library UP-TO-DATE
:app:prepareComGithubRaizlabsDBFlowDbflow300Beta2Library UP-TO-DATE
:app:prepareComGithubRaizlabsDBFlowDbflowSqlcipher300Beta2Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAuth830Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase830Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement830Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMeasurement830Library UP-TO-DATE
:app:prepareComJakewhartonTimberTimber410Library UP-TO-DATE
:app:prepareComSoundcloudAndroidAndroidCrop100Library UP-TO-DATE
:app:prepareComSquareupLeakcanaryLeakcanaryAndroid131Library UP-TO-DATE
:app:prepareComTreeboBottomsheet11Library UP-TO-DATE
:app:prepareComWdullaerMaterialdatetimepicker211Library UP-TO-DATE
:app:prepareIoFabricSdkAndroidFabric1310Library UP-TO-DATE
:app:prepareIoReactivexRxandroid101Library UP-TO-DATE
:app:prepareNetDanlewAndroidJoda291Library UP-TO-DATE
:app:prepareNetZeteticAndroidDatabaseSqlcipher3312Library UP-TO-DATE
:app:prepareUkCoChrisjenxCalligraphy210Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:fabricGenerateResourcesDebug
:app:generateDebugResValues UP-TO-DATE
:app:processDebugGoogleServices
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugResources
:app:generateDebugSources
:app:compileDebugJavaWithJavac
/Users/devesh/bumble_bee_android/app/build/generated/source/apt/debug/com/treebo/bumblebee/flow/checkin/models/ComposedBooking_Adapter.java
Error:(63, 38) error: cannot find symbol method getIsGroupBooking()
Error:(63, 222) error: cannot find symbol method getIsGroupBooking()
Error:(134, 38) error: cannot find symbol method getIsGroupBooking()
Error:(134, 222) error: cannot find symbol method getIsGroupBooking()
Error:(231, 31) error: incompatible types: <null> cannot be converted to boolean
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
:app:compileRetrolambdaDebug
FAILURE: Build failed with an exception.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Error:org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:47)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 70 more
Information:BUILD FAILED
Information:Total time: 3.936 secs
Information:6 errors
Information:0 warnings
Information:See complete output in console
```

**Comment by agrosner** [comment]
hmm it appears you are missing getter methods for private field named:
```
Error:(63, 38) error: cannot find symbol method getIsGroupBooking()
Error:(63, 222) error: cannot find symbol method getIsGroupBooking()
Error:(134, 38) error: cannot find symbol method getIsGroupBooking()
Error:(134, 222) error: cannot find symbol method getIsGroupBooking()
Error:(231, 31) error: incompatible types: <null> cannot be converted to boolean
```
also you may need to set `@Table(useIsForPrivateBooleans = true)`

**Comment by agrosner** [comment]
so you can have a method named `isGroupBooking()`

**Comment by deveshmittal** [comment]
Perfect! That worked. Thanks!

**Comment by agrosner** [comment]
Ill need to add proper checking for that (somehow) to determine if there are valid getters and setters specified.

**Comment by agrosner** [comment]
in `develop`. Will print error message as follows:
```
Error:*==========*
  class com.raizlabs.android.dbflow.processor.validator.ColumnValidator: Could not find getter for private element: "hidden" from table class: TestEmptyModel. Consider adding a getter with name getHidden or making it more accessible.
  *==========*
Error:*==========*
  class com.raizlabs.android.dbflow.processor.validator.ColumnValidator: Could not find setter for private element: "hidden" from table class: TestEmptyModel. Consider adding a setter with name setHidden or making it more accessible.
  *==========*
```
