### ISSUE TITLE
[beta3] View Creation Help/Documentation

### ISSUE THREAD

**Issue by brwskitime** [Raizlabs/DBFlow#634]
I can't create the most basic view. I followed the only example I could find.

```
@ModelView(name = GamePlayerView.VIEW_NAME,database = MBDatabase.class)
public class GamePlayerView extends BaseModelView {
    public static final String VIEW_NAME = "view_game_players";

    @ModelViewQuery
    public static final Query query = new Select(GamePlayer_Table._id,GamePlayer_Table.game__id).from(GamePlayer.class);

}
```

This is the error. 

```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.sun.tools.javac.util.List.get(List.java:476)
	at com.raizlabs.android.dbflow.processor.definition.ModelViewDefinition.<init>(ModelViewDefinition.java:108)
	at com.raizlabs.android.dbflow.processor.handler.ModelViewHandler.onProcessElement(ModelViewHandler.java:22)
	at com.raizlabs.android.dbflow.processor.handler.BaseContainerHandler.handle(BaseContainerHandler.java:23)
	at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:276)
	at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:100)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 79 more
```

I can't tell if this is a bug or something I'm missing, since the only documentation I can find is one example buried in the migration docs.

**Comment by brwskitime** [comment]
Well I didn't follow the example after all.  You get this error if you don't include the generic. 

The fix:
```
public class GamePlayerView extends BaseModelView<GamePlayerView> {
```

**Comment by brwskitime** [comment]
The crash was all me.
