### ISSUE TITLE
Stackoverflow exception in generated database definition code

### ISSUE THREAD

**Issue by Pedramrn** [Raizlabs/DBFlow#649]
This happens in 3.0.0-beta3 after a transaction, `FlowManager.destroy()` and restarting the app process.
stacktrace:
```
FATAL EXCEPTION: main
Process: com.example.app, PID: 10239
java.lang.StackOverflowError
 at android.app.ContextImpl.validateFilePath(ContextImpl.java:2116)
 at android.app.ContextImpl.getDatabasePath(ContextImpl.java:977)
 at android.content.ContextWrapper.getDatabasePath(ContextWrapper.java:266)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.movePrepackagedDB(DatabaseHelperDelegate.java:96)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.<init>(DatabaseHelperDelegate.java:41)
 at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.<init>(FlowSQLiteOpenHelper.java:30)
 at com.raizlabs.android.dbflow.config.DatabasePushdatabase_push_Database.createHelper(DatabasePushdatabase_push_Database.java:34)
 at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getHelper(BaseDatabaseDefinition.java:159)
 at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:169)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.getWritableDatabase(DatabaseHelperDelegate.java:284)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.isDatabaseIntegrityOk(DatabaseHelperDelegate.java:138)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.movePrepackagedDB(DatabaseHelperDelegate.java:99)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.<init>(DatabaseHelperDelegate.java:41)
 at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.<init>(FlowSQLiteOpenHelper.java:30)
 at com.raizlabs.android.dbflow.config.DatabasePushdatabase_push_Database.createHelper(DatabasePushdatabase_push_Database.java:34)
 at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getHelper(BaseDatabaseDefinition.java:159)
 at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:169)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.getWritableDatabase(DatabaseHelperDelegate.java:284)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.isDatabaseIntegrityOk(DatabaseHelperDelegate.java:138)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.movePrepackagedDB(DatabaseHelperDelegate.java:99)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.<init>(DatabaseHelperDelegate.java:41)
 at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.<init>(FlowSQLiteOpenHelper.java:30)
 at com.raizlabs.android.dbflow.config.DatabasePushdatabase_push_Database.createHelper(DatabasePushdatabase_push_Database.java:34)
 at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getHelper(BaseDatabaseDefinition.java:159)
 at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:169)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.getWritableDatabase(DatabaseHelperDelegate.java:284)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.isDatabaseIntegrityOk(DatabaseHelperDelegate.java:138)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.movePrepackagedDB(DatabaseHelperDelegate.java:99)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.<init>(DatabaseHelperDelegate.java:41)
 at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.<init>(FlowSQLiteOpenHelper.java:30)
 at com.raizlabs.android.dbflow.config.DatabasePushdatabase_push_Database.createHelper(DatabasePushdatabase_push_Database.java:34)
 at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getHelper(BaseDatabaseDefinition.java:159)
 at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:169)
 at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.getWritableDatabase(DatabaseHelperDelegate.java:284)
	at com.raizlabs.android.dbflow.structure.database.Database
```

**Comment by gauravsak** [comment]
Could you please provide steps to reporoduce this stack trace? Thanks.

**Comment by Motoharujap** [comment]
Same here. Steps to reproduce (not sure about them though)
1. Copy database, created by application that uses DBFlow to, say, sdcard
2. Edit this database in SQLiteSpy (create new table, insert some values)
3. Put edited database in the assets folder
4. Go back to application. Use database somehow (view data for ex)
5. Kill application (go to settings - force stop)
6. reopen application - profit.

Logs:

```
java.lang.StackOverflowError
                                                                               at java.lang.String._getChars(String.java:908)
                                                                               at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:147)
                                                                               at java.lang.StringBuilder.append(StringBuilder.java:216)
                                                                               at java.io.File.join(File.java:215)
                                                                               at java.io.File.<init>(File.java:157)
                                                                               at java.io.File.<init>(File.java:124)
                                                                               at android.app.ContextImpl.makeFilename(ContextImpl.java:2200)
                                                                               at android.app.ContextImpl.validateFilePath(ContextImpl.java:2186)
                                                                               at android.app.ContextImpl.getDatabasePath(ContextImpl.java:1025)
                                                                               at android.content.ContextWrapper.getDatabasePath(ContextWrapper.java:266)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.movePrepackagedDB(DatabaseHelperDelegate.java:96)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.<init>(DatabaseHelperDelegate.java:41)
                                                                               at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.<init>(FlowSQLiteOpenHelper.java:30)
                                                                               at com.raizlabs.android.dbflow.config.InspectorDatabaseInspectorDatabase_Database.createHelper(InspectorDatabaseInspectorDatabase_Database.java:46)
                                                                               at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getHelper(BaseDatabaseDefinition.java:159)
                                                                               at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:169)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.getWritableDatabase(DatabaseHelperDelegate.java:284)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.isDatabaseIntegrityOk(DatabaseHelperDelegate.java:138)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.movePrepackagedDB(DatabaseHelperDelegate.java:99)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.<init>(DatabaseHelperDelegate.java:41)
                                                                               at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.<init>(FlowSQLiteOpenHelper.java:30)
                                                                               at com.raizlabs.android.dbflow.config.InspectorDatabaseInspectorDatabase_Database.createHelper(InspectorDatabaseInspectorDatabase_Database.java:46)
                                                                               at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getHelper(BaseDatabaseDefinition.java:159)
                                                                               at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:169)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.getWritableDatabase(DatabaseHelperDelegate.java:284)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.isDatabaseIntegrityOk(DatabaseHelperDelegate.java:138)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.movePrepackagedDB(DatabaseHelperDelegate.java:99)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.<init>(DatabaseHelperDelegate.java:41)
                                                                               at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.<init>(FlowSQLiteOpenHelper.java:30)
                                                                               at com.raizlabs.android.dbflow.config.InspectorDatabaseInspectorDatabase_Database.createHelper(InspectorDatabaseInspectorDatabase_Database.java:46)
                                                                               at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getHelper(BaseDatabaseDefinition.java:159)
                                                                               at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:169)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.getWritableDatabase(DatabaseHelperDelegate.java:284)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.isDatabaseIntegrityOk(DatabaseHelperDelegate.java:138)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.movePrepackagedDB(DatabaseHelperDelegate.java:99)
                                                                               at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.<init>(DatabaseHelperDelegate.java:41)
                                                                               at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.<init>(FlowSQLiteOpenHelper.java:30)
                                                                           	at com.raizlabs.android.dbflow.config.InspectorDatabaseInspectorDatabase_Database.createHelper(InspectorDatabaseInspectorDatabas
```

**Comment by agrosner** [comment]
fixed in `develop` :)
