### ISSUE TITLE
Cannot execute for last inserted row ID, base error code: 19

### ISSUE THREAD

**Issue by Vinoth7** [Raizlabs/DBFlow#676]
Hi DBFlow team,
I am trying to run unit test using Robolectric. But i am getting below error. I am not sure what is the issue here. I though it might me the static reference, i tried to clear it but it doesn't seems to resolving.

`@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21)
public class GCMAddAccountActivity_Test {
    GCMAddAccountActivity addAccountActivity = null;

    @Before
    public void setUp(){
        FlowManager.init(RuntimeEnvironment.application);
        FlowManager.getDatabase(GCMoneyDatabase.NAME).getWritableDatabase().beginTransaction();
        addAccountActivity = Robolectric.setupActivity(GCMAddAccountActivity.class);
    }

    @Test
    public void activityNotNull(){
        Assert.assertNotNull(addAccountActivity);
    }

    @After
    public void tearDown() throws Exception {
        FlowManager.getDatabase(GCMoneyDatabase.NAME).getWritableDatabase().endTransaction();
        FlowManager.getDatabase(GCMoneyDatabase.NAME).reset(RuntimeEnvironment.application);
        FlowManager.destroy();

        Field field = FlowManager.class.getDeclaredField("globalDatabaseHolder");
        field.setAccessible(true);
        field.set(null, null);
     }
}

Currency Class
@Table(database = GCMoneyDatabase.class)
public class Currency extends BaseModel{

    @Column
    @PrimaryKey (autoincrement = true)
    long id;

    @Column @Unique
    public String symbol;

    @Column
    public String shortName;

    @Column @Unique
    public String name;

    public static List<Currency> getCurrencies(){
        List<Currency> currencies = SQLite.select().from(Currency.class).queryList();
        if (currencies.isEmpty()) {
            GCMCurrencyData.getCurrencyData().loadCurrenciesInToDatabase();
            currencies = SQLite.select().from(Currency.class).queryList();
        }
        return currencies;
    } 
} 
`

`
android.database.sqlite.SQLiteException: Cannot execute for last inserted row ID, base error code: 19
	at org.robolectric.shadows.ShadowSQLiteConnection.rethrow(ShadowSQLiteConnection.java:56)
	at org.robolectric.shadows.ShadowSQLiteConnection.access$500(ShadowSQLiteConnection.java:33)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:466)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativeExecuteForLastInsertedRowId(ShadowSQLiteConnection.java:261)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.executeInsert(AndroidDatabaseStatement.java:73)
	at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:370)
	at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:327)
	at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:60)
	at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:50)
	at com.vsapps.vsmoney.database.predata.GCMCurrencyData.loadCurrenciesInToDatabase(GCMCurrencyData.java:24)
	at com.vsapps.vsmoney.database.tables.Currency.getCurrencies(Currency.java:36)
	at com.vsapps.vsmoney.accountmanager.GCMAddAccountActivity.createViewIds(GCMAddAccountActivity.java:135)
	at com.vsapps.vsmoney.accountmanager.GCMAddAccountActivity.onCreate(GCMAddAccountActivity.java:84)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:46)
	at com.vsapps.vsmoney.GCMAddAccountActivity_Test.setUp(GCMAddAccountActivity_Test.java:35)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.almworks.sqlite4java.SQLiteException: [19] DB[1] step() [INSERT INTO `Currency`(`symbol`,`shortName`,`name`) VALUES (?,?,?)]DB[1][C] [column symbol is not unique]
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1309)
	at com.almworks.sqlite4java.SQLiteConnection$BaseController.throwResult(SQLiteConnection.java:1562)
	at com.almworks.sqlite4java.SQLiteStatement.stepResult(SQLiteStatement.java:1231)
	at com.almworks.sqlite4java.SQLiteStatement.step(SQLiteStatement.java:302)
	at com.almworks.sqlite4java.SQLiteStatement.stepThrough(SQLiteStatement.java:316)
	at org.robolectric.shadows.ShadowSQLiteConnection$14.call(ShadowSQLiteConnection.java:265)
	at org.robolectric.shadows.ShadowSQLiteConnection$14.call(ShadowSQLiteConnection.java:261)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:452)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:446)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
`

Any help would be much appreciated.

**Comment by agrosner** [comment]
@Vinoth7 what does this line do:
```
        GCMCurrencyData.getCurrencyData().loadCurrenciesInToDatabase();

```

**Comment by agrosner** [comment]
take a look at https://github.com/Raizlabs/DBFlow/issues/78. It may help you

**Comment by Vinoth7** [comment]
@agrosner Here is the code on GCMCurrencyData.getCurrencyData().loadCurrenciesInToDatabase();

   ```
public void loadCurrenciesInToDatabase(){
        for (Currency currency : getCurrencies()) {// getCurrencies() is list of currencies
                currency.save(); // Here is the crash
        }
    }
```

I did looked at #78 before posting this. It doesn't help as `acquireReference` is no longer available in the latest DBFlow.

**Comment by Vinoth7** [comment]
@agrosner Fixed it. Sorry its my bad. It just data issue.
