### ISSUE TITLE
Glueing together tables and databases doesn't work reliably with Kotlin, Dagger and separate modules. 

### ISSUE THREAD

**Issue by asco33** [Raizlabs/DBFlow#685]
I'm trying to use DBFlow version 3.0.0-beta5 in a large project that uses
- Kotlin
- Dagger (2)
- separate modules for app and data

I often times get the following exception: 

```
Caused by: com.raizlabs.android.dbflow.structure.InvalidDBConfiguration: Table: 
com.example.fweigl.data.User is not registered with a Database. Did you forget the @Table annotation?
                                                                                         at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseForTable(FlowManager.java:109)
                                                                                         at com.raizlabs.android.dbflow.config.FlowManager.getModelAdapter(FlowManager.java:271)
                                                                                         at com.raizlabs.android.dbflow.structure.BaseModel.getModelAdapter(BaseModel.java:96)
                                                                                         at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:52)
```

This is not consistent, but happens very often, cleaning and rebuilding the app usually doesn't help (but sometimes does). 

I created a small-as-possible project that displays the same symptoms: https://bitbucket.org/asco33/dbflowmoduletest/. 

Is there anything fundamentally wrong with how I use the library or might this be a DBFlow issue?

PS: I'm aware of https://github.com/Raizlabs/DBFlow/issues/515 and I'm using the latest gradlew plugin that supposedly fixed the issue.

**Comment by asco33** [comment]
My colleague solved this for me: 
Running 'clean project' from Android Studio obviously doesn't delete the files created by Kotlin' kapt, so any changes to e.g. the database name would not be reflected in newer builds. 
Cleaning the project from the command line via gradle did the trick and made everything run. 
This can be closed then :)

**Comment by agrosner** [comment]
cool

**Comment by levibostian** [comment]
@asco33, have you continued to have success using `./gradlew clean`? I am using `./gradlew clean` and it fixes the issue about 30 - 40% of the time. 

`./gradlew clean`, build and install the app cross fingers it runs. 
If it runs, great. If not, clean again and cross fingers again. 

[Opened issue](https://github.com/Raizlabs/DBFlow/issues/745) to discuss it as I am getting this issue quite often and also using a few different libraries like yourself (except Kotlin).
