### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'. > java.lang.IllegalArgumentException: expected type but was null

### ISSUE THREAD

**Issue by cantasci** [Raizlabs/DBFlow#717]
Hi,

i have just started using DBFlow(3.0.0-beta5) and get all the time the following error.  

`Caused by: java.lang.IllegalArgumentException: expected type but was null
	at com.squareup.javapoet.CodeBlock$Builder.argToType(CodeBlock.java:207)
	at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:170)
	at com.squareup.javapoet.CodeBlock$Builder.addStatement(CodeBlock.java:249)
	at com.squareup.javapoet.MethodSpec$Builder.addStatement(MethodSpec.java:465)
	at com.raizlabs.android.dbflow.processor.definition.method.DatabaseDefinition.writeConstructor(DatabaseDefinition.java:130)
	at com.raizlabs.android.dbflow.processor.definition.method.DatabaseDefinition.onWriteDefinition(DatabaseDefinition.java:119)
	at com.raizlabs.android.dbflow.processor.definition.BaseDefinition.getTypeSpec(BaseDefinition.java:123)
	at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:302)
	at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:100)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)`

**Comment by brwskitime** [comment]
Can't tell what's going on from the log output, but here's something I ran into. All my models extend a BaseTable class, and until I put everything in the same package, I kept getting errors, even with all public variables.

**Comment by agrosner** [comment]
@cantasci may I ask what your `generatedClassSeparator` was in this case?

**Comment by agrosner** [comment]
should be fixed in `develop` if your `generatedClassSeparator` was `$` or `$$`
