### ISSUE TITLE
Exception running a Transaction in Migration

### ISSUE THREAD

**Issue by brwskitime** [Raizlabs/DBFlow#721]
I have to perform data conversion as part of a migration. The process creates a large number of new entries, which I put in a transaction. However this is causing db lock exceptions. 

```
03-25 12:46:11.556: E/AndroidRuntime(17385): Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1148)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.getDatabase(FlowSQLiteOpenHelper.java:51)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:169)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:37)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:41)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:266)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at com.snocru.snocru.appbackground.AppBackgroundStorageManager.setAppBackgroundForType(AppBackgroundStorageManager.java:35)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at com.snocru.snocru.SnoCruActivity.setWindowBackground(SnoCruActivity.java:224)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at com.snocru.snocru.SnoCruActivity.onResume(SnoCruActivity.java:109)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at com.snocru.snocru.MainActivity.onResume(MainActivity.java:182)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.app.Activity.performResume(Activity.java:6076)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
03-25 12:46:11.556: E/AndroidRuntime(17385): 	... 11 more
```

**Comment by brwskitime** [comment]
The call to AppBackgroundStorageManager is not part of the migration but gets called when the app first loads.

**Comment by agrosner** [comment]
When you run a migration, the code you execute already exists in a transaction. so hack away :)
