### ISSUE TITLE
How to update column value to null?

### ISSUE THREAD

**Issue by donnysim** [Raizlabs/DBFlow#748]
How can I set a column value to null? there's absolutely no documentation about how to work with null values in columns and I start to think that it's impossible to do with DBFlow.

` @Column
    var token: String? = null`

`SQLite.update(User::class.java).set(User_Table.token.?)`

can't find any method that would allow me to set it as null.

DBFlow 3

**Comment by agrosner** [comment]
1. first of all, using Kotlin for DBFlow classes is not supported as there are issues/bugs with KAPT on this. My bet is to write them in Java. 
2. try the `isNull()` and `isNotNull()` methods.

**Comment by Harti** [comment]
Yeah, this is not helpful.

> try the isNull() and isNotNull() methods.


`SQLite.update(Area.class).set(Area_Table.downloadedAt.isNull(), Area_Table.pointsOfDownload.isNull()).execute();` causes:

```
android.database.sqlite.SQLiteException: near "IS": syntax error (code 1): , while compiling: UPDATE `Area` SET `downloadedAt` IS NULL , `pointsOfDownload` IS NULL
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1677)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1608)
	at com.raizlabs.android.dbflow.structure.database.AndroidDatabase.execSQL(AndroidDatabase.java:26)
	at com.raizlabs.android.dbflow.sql.language.BaseQueriable.query(BaseQueriable.java:105)
	at com.raizlabs.android.dbflow.sql.language.Where.query(Where.java:216)
	at com.raizlabs.android.dbflow.sql.language.Where.query(Where.java:224)
	at com.raizlabs.android.dbflow.sql.language.BaseTransformable.query(BaseTransformable.java:33)
	at com.raizlabs.android.dbflow.sql.language.BaseQueriable.execute(BaseQueriable.java:122)
```

**Comment by agrosner** [comment]
try `.eq(null)`. just guessing.

**Comment by agrosner** [comment]
you probably will have to cast it to a type, use cast type of `downloadedAt`

**Comment by Harti** [comment]
Thanks for the swift reply, the cast was the crucial bit of information (as `.eq(null)` itself would not compile and I somehow didn't get the idea of casting `null`).

For further reference: In my case, I used:
`SQLite.update(Area.class).set(Area_Table.downloadedAt.eq((Date) null).execute();` 


Thanks again!!

**Comment by agrosner** [comment]
yes its because we have multiple methods to enforce typesafety within
calling code so you place objects of proper type on a specific `Property`
instance. I may think of better way in future instead of using null. if you
predeclared date as: `val date: Date? = null` then pass it in, you wouldn't
need casting.
