### ISSUE TITLE
Random "not an error: Could not register Android SQL functions."

### ISSUE THREAD

**Issue by ubuntudroid** [Raizlabs/DBFlow#750]
Since integrating DBFlow with SQLCipher (3.0.0-beta5) we are receiving reports about random

> not an error: Could not register Android SQL functions.

errors. All types of devices and Android versions seem to be affected.

The full stack trace looks like this:

> Non-fatal Exception: net.sqlcipher.database.SQLiteException: not an error: Could not register Android SQL functions.
       at net.sqlcipher.database.SQLiteDatabase.dbopen(SQLiteDatabase.java)
       at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2322)
       at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1087)
       at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1150)
       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
       at com.raizlabs.dbflow.android.sqlcipher.SQLCipherOpenHelper.getDatabase(SQLCipherOpenHelper.java:58)
       at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:169)
       at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:37)
       at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:46)
       at com.raizlabs.android.dbflow.sql.language.Where.querySingle(Where.java:285)
       ...

`querySingle()` is just one example where this happens - I have examples where it happens with other calls like `save()` as well.

It affects around 7% of our users although it could probably be a higher effective rate as not all users enter the sections where the database is used. I'm pretty sure it happens upon first database access, but I can't prove this right now, although there are some hints in our logs and stack traces which seem to point into that direction.

The issue could be related to https://github.com/sqlcipher/android-database-sqlcipher/issues/139.

**Comment by agrosner** [comment]
yeah if its happening in sqlcipher, its potentially their own issue. going to close this as we're not doing anything crazy that would cause this to always happen.

**Comment by ubuntudroid** [comment]
I'm not sure if this issue is an issue within SQLCipher. Looking at the linked SQLCipher issues some developers seemed to have been able to overcome the issue by just changing their implementation, so it could also be an issue in DBFlow's SQLCipher integration code.

**Comment by jeason789** [comment]
@ubuntudroid I'm using sqlcipher,and i also encounter this problem .it seems to be an issue in sqlcipher.
and eventually,did you solve this?

**Comment by ubuntudroid** [comment]
We still have this, but it somehow doesn't affect much fewer users as firstly thought, just around 0.0001%  for us right now.

**Comment by jeason789** [comment]
@ubuntudroid we solved it ; it happened because we created databases concurrently, so i created my databases in a serial executor. But here comes another problem.  Open or create database with sqlcipher is expensive, about 500-800ms per db file  and serial execution will make it even worse if you have more db file to open or create;  hope this might help.

**Comment by ubuntudroid** [comment]
@jeason789 We just have one database, so that cannot be the reason for the
error message in our app. :( But glad to hear it is fixed for you!

jeason789 <notifications@github.com> schrieb am Do., 19. Mai 2016, 10:01:

**Comment by KuoCH** [comment]
I encounter the same problem. Add follow into proguard solve my problems:

```
-keep class net.sqlcipher.** {
    *;
}

-keep class net.sqlcipher.database.** {
    *;
}
```

reference [this](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/proguard-project.txt)
