### ISSUE TITLE
IllegalArgumentException @ForeignKey

### ISSUE THREAD

**Issue by krzysiek-zgondek** [Raizlabs/DBFlow#751]
Error:java.lang.IllegalArgumentException: index 1 for '$T' not in range (received 0 arguments)

> 	at com.squareup.javapoet.Util.checkArgument(Util.java:62)
	at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:154)
	at com.squareup.javapoet.CodeBlock$Builder.addStatement(CodeBlock.java:249)
	at com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition.getLoadFromCursorMethod(ForeignKeyColumnDefinition.java:357)
	at com.raizlabs.android.dbflow.processor.definition.method.LoadFromCursorMethod.getMethodSpec(LoadFromCursorMethod.java:51)
	at com.raizlabs.android.dbflow.processor.definition.TableDefinition.writeAdapter(TableDefinition.java:597)
	at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:315)
	at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:100)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)

tables are here:
`@Table(database = ContentDatabase.class)
public class User extends BaseModel {
    @PrimaryKey(autoincrement = false)
    @Column public String id;
    @Column
    @ForeignKey
    Contact contact;
}

@ModelContainer
@Table(database = ContentDatabase.class)
public class Contact extends BaseModel {
    @PrimaryKey(autoincrement = true) public Long id;
    @Column public String name;
}
`
if i remove @ForeignKey Contact contact; it compiles without any error. Any idea what is wrong?

**Comment by krzysiek-zgondek** [comment]
it is due to generatedClassSeparator, after i removed it ForeignKey started to work again. But still it is a bug.

@Database(//generatedClassSeparator = "$",
        name = ContentDatabase.NAME,
        version = ContentDatabase.VERSION,
        foreignKeysSupported = true)

**Comment by agrosner** [comment]
fixed in `develop`. will be out in beta6
