### ISSUE TITLE
Close cursors after each test with Robolectric

### ISSUE THREAD

**Issue by wmora** [Raizlabs/DBFlow#78]
Hi,

I'm using this library and it has been working great so far. However, I'm having issues during my Robolectric tests run.

I have a test class that saves a record before each test and that same record gets deleted after each test. During the test run, the first test runs OK, but any subsequent test throws the following exception when trying to save the record:
```java
android.database.sqlite.SQLiteException: Cannot execute for last inserted row ID, base error code: 10
	at org.robolectric.shadows.ShadowSQLiteConnection.rethrow(ShadowSQLiteConnection.java:48)
	at org.robolectric.shadows.ShadowSQLiteConnection.access$500(ShadowSQLiteConnection.java:26)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:436)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativeExecuteForLastInsertedRowId(ShadowSQLiteConnection.java:239)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:379)
	at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:316)
	at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:61)
	at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:54)
	at com.raizlabs.android.dbflow.structure.cache.BaseCacheableModel.save(BaseCacheableModel.java:74)
	at com.nispok.fitcoach.models.GoalNotification$Adapter.bindToStatement(GoalNotification$Adapter.java:33)
	at com.nispok.fitcoach.models.GoalNotification$Adapter.bindToStatement(GoalNotification$Adapter.java:12)
	at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:378)
	at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:316)
	at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:61)
	at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:54)
	at com.raizlabs.android.dbflow.structure.cache.BaseCacheableModel.save(BaseCacheableModel.java:74)
	at com.nispok.fitcoach.models.Goal$Adapter.bindToStatement(Goal$Adapter.java:43)
	at com.nispok.fitcoach.models.Goal$Adapter.bindToStatement(Goal$Adapter.java:12)
	at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:378)
	at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:316)
	at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:61)
	at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:54)
	at com.raizlabs.android.dbflow.structure.cache.BaseCacheableModel.save(BaseCacheableModel.java:74)
	at com.nispok.fitcoach.services.GoalServiceTest.createGoalMock(GoalServiceTest.java:44)
	at com.nispok.fitcoach.services.GoalServiceTest.setUp(GoalServiceTest.java:24)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
Caused by: com.almworks.sqlite4java.SQLiteException: [1802] DB[2] step() [INSERT INTO `MY_TABLE` (`HOUR`, `MINUTE`) VALUES (?, ?)]DB[2][C] [disk I/O error]
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1309)
	at com.almworks.sqlite4java.SQLiteConnection$BaseController.throwResult(SQLiteConnection.java:1562)
	at com.almworks.sqlite4java.SQLiteStatement.stepResult(SQLiteStatement.java:1231)
	at com.almworks.sqlite4java.SQLiteStatement.step(SQLiteStatement.java:302)
	at com.almworks.sqlite4java.SQLiteStatement.stepThrough(SQLiteStatement.java:316)
	at org.robolectric.shadows.ShadowSQLiteConnection$14.call(ShadowSQLiteConnection.java:243)
	at org.robolectric.shadows.ShadowSQLiteConnection$14.call(ShadowSQLiteConnection.java:239)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:422)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:416)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

Here's the code setup for the class:
```java
@RunWith(RobolectricTestRunner.class)
public class GoalServiceTest {

    private Goal goalMock;

    @Before
    public void setUp() {
        createGoalMock();
    }

    @After
    public void tearDown() {
        goalMock.delete(false);
    }

    private void createGoalMock() {        
        goalMock = new Goal();
        // set goalMock values
        goalMock.save(false); // This is the line that throws the exception
    }

    @Test
    public void testOne() {
        ...
    }

    @Test
    public void testTwo() {
        ...
    }

    @Test
    public void testThree() {
        ...
    }

}
```
I've seen similar issues reported with other ORM libraries using Robolectric as well. For instance: https://github.com/robolectric/robolectric/issues/1164 and https://github.com/robolectric/robolectric/issues/1181. They all suggest to close all cursors or delete all databases after each test.

I've tried the latter (deleting the database with the line `FlowManager.getDatabase(myDatabaseName).getWritableDatabase().close();`) but then I get the following error during the second test run:
```java
java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:786)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:379)
	at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:316)
	at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:61)
	at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:54)
	at com.raizlabs.android.dbflow.structure.cache.BaseCacheableModel.save(BaseCacheableModel.java:74)
	at com.nispok.fitcoach.models.GoalNotification$Adapter.bindToStatement(GoalNotification$Adapter.java:33)
	at com.nispok.fitcoach.models.GoalNotification$Adapter.bindToStatement(GoalNotification$Adapter.java:12)
	at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:378)
	at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:316)
	at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:61)
	at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:54)
	at com.raizlabs.android.dbflow.structure.cache.BaseCacheableModel.save(BaseCacheableModel.java:74)
	at com.nispok.fitcoach.models.Goal$Adapter.bindToStatement(Goal$Adapter.java:43)
	at com.nispok.fitcoach.models.Goal$Adapter.bindToStatement(Goal$Adapter.java:12)
	at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:378)
	at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:316)
	at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:61)
	at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:54)
	at com.raizlabs.android.dbflow.structure.cache.BaseCacheableModel.save(BaseCacheableModel.java:74)
	at com.nispok.fitcoach.services.GoalServiceTest.createGoalMock(GoalServiceTest.java:47)
	at com.nispok.fitcoach.services.GoalServiceTest.setUp(GoalServiceTest.java:26)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
```
Any ideas? This lib is very helpful and I would like my tests to be running with Robolectric.

**Comment by agrosner** [comment]
can you reopen the connection to the DB? I would maybe try using ```FlowManager.getDatabase(myDatabaseName).reset()``` instead of close.

**Comment by wmora** [comment]
Thanks, this pointed me in the right direction. It's a threading problem; some other thread is keeping the lock for my instance `SQLiteDatabase` (my app also saved some records on app startup).

To solve this, I'm explicitly acquiring and releasing references in my setup/teardown:

```java
   @Before
    public void setUp() {
        FlowManager.init(Robolectric.application);
        FlowManager.getDatabase(myDatabaseName).getWritableDatabase().acquireReference();
    }

   @After
    public void tearDown() {
        FlowManager.getDatabase(myDatabaseName).getWritableDatabase().releaseReference();
        FlowManager.getDatabase(myDatabaseName).reset(Robolectric.application);
        FlowManager.destroy();
    }
```

**Comment by agrosner** [comment]
interesting. thats good to note. Not sure what's happening there. So this is fixed? I will close unless its not solved and you want to keep it open.

**Comment by wmora** [comment]
It's fixed for my project setup, but I haven't had time to check if it's a Robolectric problem or a problem with the lib.

What I'll do is I'll write the same tests as an `InstrumentationTestCase` to see if I get the same error. If I don't, then it's definitely an issue with Robolectric. I'll update this thread when I do that (probably later this week).

**Comment by AdamMTGreenberg** [comment]
Did you guys ever resolve the cause of this?

Following your setup as standard I am able to run successfully on the first test, however, on the second test I am unable to save anything to the DB successfully. Thanks for the help.

**Comment by DenisGL** [comment]
I had a similar issue with DBFlow 2.2.1 and Robolectric 3. @mickele solution in [Robolectric#1890](https://github.com/robolectric/robolectric/issues/1890) solved my issue:

    @After
    public void tearDown() throws Exception {
        Field field = FlowManager.class.getDeclaredField("mDatabaseHolder");
        field.setAccessible(true);
        field.set(null, null);
    }

**Comment by AdamMTGreenberg** [comment]
That's awesome. Thanks for linking this.
