### ISSUE TITLE
@ManyToMany endless loop on load

### ISSUE THREAD

**Issue by sebastianmaz** [Raizlabs/DBFlow#789]
DBFlow Version: 3.0.0-beta4
Issue Kind (Bug, Question, Feature): Bug

Description: 
I have two tables which should have many-to-many relationship:

```
@ModelContainer
@Table(database = DbName.class)
public class Product extends BaseModel {
    @SerializedName("id_product")
    @PrimaryKey(autoincrement = false)
    private Long id;

    @SerializedName("debtor")
    private List<Debtor> debtor = new ArrayList<Debtor>();
    
    @OneToMany(methods = {OneToMany.Method.LOAD}, variableName = "debtor")
    public List<Debtor> getProductDebtor() {
        if (debtor == null || debtor.isEmpty()) {
            List<Debtor_Product> listDebtorProduct = SQLite.select()
                    .from(Debtor_Product.class)
                    .where(Debtor_Product_Table.product_id.eq(id))
                    .queryList();

            debtor = new ArrayList<Debtor>();
            for (Debtor_Product debtorProduct : listDebtorProduct) {
                debtor.add(debtorProduct.getDebtor());
            }
        }
        return debtor;
    }
}
```

AND

```
@ModelContainer
@ManyToMany(referencedTable = Product.class)
@Table(database = DbName.class)
public class Debtor extends BaseModel {
    @SerializedName("id")
    @PrimaryKey
    private Long id;
}
```

Every time when I try to select list of Products  it hangs in infinite loop while executing getProductDebtor(). It looks like every time it creates new pair of Product and Debtor it executes getProductDebtor() again and again and again...

I am sure something is wrong with my configuration. Earlier I had just one-to-many relationship and it was OK. When I switched to many-to-many it fails.

**Comment by agrosner** [comment]
Can you provide me the `Debtor_Product` table? I think I know what is wrong

**Comment by agrosner** [comment]
My guess is generated table uses both `Product` and `Debtor`, and since you put `
@OneToMany(methods = {OneToMany.Method.LOAD}, variableName = "debtor")` It will always load this method when the `Product` loads, causing the infinite recursion you're seeing.

**Comment by sebastianmaz** [comment]
```
@Table(
    database = CmasMobileDatabase.class
)
public final class Debtor_Product extends BaseModel {
  @PrimaryKey(
      autoincrement = true
  )
  long _id;

  @ForeignKey(
      saveForeignKeyModel = false
  )
  Product product;

  @ForeignKey(
      saveForeignKeyModel = false
  )
  Debtor debtor;

  public final long getId() {
    return _id;
  }

  public final Product getProduct() {
    return product;
  }

  public final void setProduct(Product param) {
    product = param;
  }

  public final Debtor getDebtor() {
    return debtor;
  }

  public final void setDebtor(Debtor param) {
    debtor = param;
  }
}
```

**Comment by sebastianmaz** [comment]
I checked it and after I remove (methods = {OneToMany.Method.LOAD}, variableName = "debtor") and leave just @OneToMany it is still the same, stil going into loop. Any ideas ? Only one I have found so far is to not select list of Debtor_Product but only list of debtor_id and then load list of Debtor by this ids but it is much longer solution

**Comment by agrosner** [comment]
can you send me loop stacktrace, like where the loop is occurring would be great. Also ensure that the `getProductDebtor()` is not getting called on load of the database.

**Comment by sebastianmaz** [comment]
This is single loop stacktrace, this 19 lines are duplicated as long as application crashes. I am not sure if this is what you want 

```
at pl.com.casus.cmas.mobile.model.Product.getProductDebtor(Product.java:224)
	  at pl.com.casus.cmas.mobile.model.Product_Adapter.loadFromCursor(Product_Adapter.java:453)
	  at pl.com.casus.cmas.mobile.model.Product_Adapter.loadFromCursor(Product_Adapter.java:21)
	  at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:26)
	  at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:12)
	  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:61)
	  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:53)
	  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:37)
	  at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:46)
	  at com.raizlabs.android.dbflow.sql.language.Where.querySingle(Where.java:277)
	  at com.android.mobile.model.Debtor_Product_Adapter.loadFromCursor(Debtor_Product_Adapter.java:133)
	  at com.android.mobile.model.Debtor_Product_Adapter.loadFromCursor(Debtor_Product_Adapter.java:19)
	  at com.raizlabs.android.dbflow.sql.queriable.ListModelLoader.convertToData(ListModelLoader.java:33)
	  at com.raizlabs.android.dbflow.sql.queriable.ListModelLoader.convertToData(ListModelLoader.java:15)
	  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:61)
	  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:53)
	  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:37)
	  at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:41)
	  at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:258)
```

**Comment by agrosner** [comment]
Looks like `getProductDebtor()` is still getting called on load from DB.

**Comment by agrosner** [comment]
try rebuilding clean

**Comment by sebastianmaz** [comment]
I did clean and build many times. I think something is wrong because in `Product_Adapter` in method `loadFromCursor` still contains ` model.getProductDebtor();`

**Comment by agrosner** [comment]
you remove the `@OneToMany` annotation?

**Comment by sebastianmaz** [comment]
OK, my bad. I deleted only second part of annotation: (methods = {OneToMany.Method.LOAD}, variableName = "debtor") , but left @OneToMany. Now when I deleted @OneToMany annotation completely it is ok :-)
