### ISSUE TITLE
Basic usage of DBFlow

### ISSUE THREAD

**Issue by nglauber** [Raizlabs/DBFlow#82]
I'm trying to use DBFlow following the steps described here (https://github.com/Raizlabs/DBFlow) but I'm getting the error:

    Process: br.com.nglauber.testgroovy, PID: 1626
    java.lang.RuntimeException: Unable to create application br.com.nglauber.testgroovy.App: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.Database$Holder
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.Database$Holder
            at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:90)
            at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:127)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
            at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:148)
            at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
            at br.com.nglauber.testgroovy.App.onCreate(App.groovy:14)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.Database$Holder
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at java.lang.Class.forName(Class.java:272)
            at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:88)
            at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:127)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
            at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:148)
            at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
            at br.com.nglauber.testgroovy.App.onCreate(App.groovy:14)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.raizlabs.android.dbflow.config.Database$Holder" on path: DexPathList[[zip file "/data/app/br.com.nglauber.testgroovy-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at java.lang.Class.forName(Class.java:272)
            at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:88)
            at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:127)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
            at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:148)
            at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
            at br.com.nglauber.testgroovy.App.onCreate(App.groovy:14)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
    Suppressed: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.Database$Holder
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 26 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

My App class is listed below

    package br.com.nglauber.testgroovy
    import android.app.Application
    import com.raizlabs.android.dbflow.config.FlowManager
    import com.squareup.otto.Bus
    
    public class App extends Application {

        Bus bus

        @Override
        public void onCreate() {
            super.onCreate()

            FlowManager.init(this);

            bus = new Bus()
        }

        @Override
        public void onTerminate() {
            super.onTerminate()
            FlowManager.destroy()
        }
    } 

The unique model class is that

    import br.com.nglauber.testgroovy.AppDatabase
    import com.raizlabs.android.dbflow.annotation.Column
    import com.raizlabs.android.dbflow.annotation.Table
    import com.raizlabs.android.dbflow.structure.BaseModel

    @Table(databaseName = AppDatabase.NAME)
    public class Palavra extends BaseModel{
        @Column(columnType = Column.NORMAL)
        public String texto;
    }

My build.gradle is here: http://pastebin.com/0Qeqkmxi

Any idea?

**Comment by agrosner** [comment]
@nglauber you probably are not using Android-apt plugin. you need to use it to generate code for you. Look at the "Including in your project" section of the main README.md

**Comment by nglauber** [comment]
Have you seen my build.gradle? I think I'm using it... Can you explain what I did wrong?

**Comment by agrosner** [comment]
Are you seeing the generated classes in build/generated/source/apt/  ? I am
not sure what is happening but it appears you are using groovy as well. Not
sure if there's compatibility issues there.

On Tue, Feb 17, 2015 at 12:48 PM, Nelson Glauber <notifications@github.com>
wrote:

> Have you seen my build.gradle? I think I'm using it... Can you explain
> what I did wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Raizlabs/DBFlow/issues/82#issuecomment-74714664>.
>



-- 
--

*Andrew Grosner, Android Developer*

Mobile Strategy, Design & Development

www.raizlabs.com | Check my calendar
<https://www.google.com/calendar/embed?src=andrew.grosner@raizlabs.com&ctz=America/New_York&mode=WEEK>
 | @agrosner <http://www.twitter.com/agrosner> | 716-472-5075
[image: Raizlabs]

**Comment by nglauber** [comment]
Yes, I'm using groovy with Android Studio. Everything works fine but DBFlow. If you comment this line, application runs
FlowManager.init(this);

I build the project and checked the directory and it is empty...
BTW my dummy project is at https://github.com/nglauber/TestGroovy I'll really appreciate if you could says unless: "sorry, it's not going to work dude!" :(

**Comment by agrosner** [comment]
Interesting. Groovy is pretty groovy. yeah so I believe the android-apt
plugin only works with the java plugin and it may be possible that the
groovy plugin is screwing or overriding the step that the apt-plugin uses.
Ill check it out when I can, but can't until probably later tonight/later
this week.

On Tue, Feb 17, 2015 at 2:41 PM, Nelson Glauber <notifications@github.com>
wrote:

> Yes, I'm using groovy with Android Studio. Everything works fine but
> DBFlow. If you comment this line, application runs
> FlowManager.init(this);
>
> I build the project and checked the directory and it is empty...
> BTW my dummy project is at https://github.com/nglauber/TestGroovy I'll
> really appreciate if you could says unless: "sorry, it's not going to work
> dude!" :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Raizlabs/DBFlow/issues/82#issuecomment-74737383>.
>



-- 
--

*Andrew Grosner, Android Developer*

Mobile Strategy, Design & Development

www.raizlabs.com | Check my calendar
<https://www.google.com/calendar/embed?src=andrew.grosner@raizlabs.com&ctz=America/New_York&mode=WEEK>
 | @agrosner <http://www.twitter.com/agrosner> | 716-472-5075
[image: Raizlabs]

**Comment by nglauber** [comment]
thank you @agrosner! groovy is a great language and it would be nice if DBFlow works with it.

**Comment by bitsnaps** [comment]
@nglauber hi, I know this has been a long time buy anyway, just make sure to use `@CompileStatic` when coding android with groovy for better performance and avoiding some issues..., also groovy orm for android could be ORMLite or SugarORM -in my opinion- since some projects have already tested it:
https://github.com/codebulb/GroovySwissKnifeAndroidApp
https://github.com/myarth/AndroidGroovyDemo
good luck.
