### ISSUE TITLE
nullpointer exception

### ISSUE THREAD

**Issue by sidshah13** [Raizlabs/DBFlow#870]
DBFlow Version:
Issue Kind (Bug, Question, Feature):

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
null
java.lang.NullPointerException
	at com.android.sdklib.repositoryv2.targets.AndroidTargetManager.getErrorForPackage(AndroidTargetManager.java:153)
	at com.android.tools.idea.gradle.service.notification.errors.MissingPlatformErrorHandler.handleError(MissingPlatformErrorHandler.java:81)
	at com.android.tools.idea.gradle.service.notification.GradleNotificationExtension.handleError(GradleNotificationExtension.java:81)
	at com.android.tools.idea.gradle.service.notification.GradleNotificationExtension.customize(GradleNotificationExtension.java:67)
	at com.intellij.openapi.externalSystem.service.notification.ExternalSystemNotificationManager.processExternalProjectRefreshError(ExternalSystemNotificationManager.java:122)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:477)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4$2.run(ExternalSystemUtil.java:500)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by agrosner** [comment]
this is not a dbflow issue. Im not sure what your asking here.
