### ISSUE TITLE
@OneToMany Not work  for me 

### ISSUE THREAD

**Issue by z-zghiba** [Raizlabs/DBFlow#887]
DBFlow Version:3.0.1
Issue Kind (Bug, Question, Feature):Bug
Description: I try to use OneToMany Relation Between Users and Organization it generates an error when I call 

```
  List<Users> usersList =  organisation.getUsers();
```

Organization : 

```
@Table(database = DBPrepa.class)
@Parcel
@ModelContainer
public class Organization extends BaseModel {

@Column
@PrimaryKey(autoincrement = true)
long id;

List<Users> users;

@Column
private String code;

(...)


public Organization() {
}

@OneToMany(methods = OneToMany.Method.ALL, variableName = "users")
public List<Users> getUsers() {
    if (users == null) {
        users = SQLite.select().from(Users.class).where(Users_Table.organisation_id.eq(id)).queryList();
    }
    return users;
}

//getter setter
}
```

Users : 

```
@Table(database = DBPrepa.class)
@Parcel
@ModelContainer
 public class Users extends BaseModel {

@Column
@PrimaryKey(autoincrement = true)
private long id;
(...)
@Column
@ForeignKey
private Organization organization;

public Users() {
}

public long getId() {
    return id;
}

//getter setter

}
```

Error : 

```
  E/AndroidRuntime: FATAL EXCEPTION: main  java.lang.StackOverflowError
                at java.lang.ref.Reference.<init>(Reference.java:85)
                at java.lang.ref.WeakReference.<init>(WeakReference.java:108)
                at java.util.WeakHashMap$Entry.<init>(WeakHashMap.java:71)
               at java.util.WeakHashMap.put(WeakHashMap.java:630)
               at android.database.sqlite.SQLiteConnectionPool.finishAcquireConnectionLocked(SQLiteConnectionPool.java:911)
               at android.database.sqlite.SQLiteConnectionPool.tryAcquirePrimaryConnectionLocked(SQLiteConnectionPool.java:847)
               at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:613)
               at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
               at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
               at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:586)
               at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
               at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
               at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
               at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
               at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
               at com.raizlabs.android.dbflow.structure.database.AndroidDatabase.rawQuery(AndroidDatabase.java:64)
               at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:56)
               at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:51)
               at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:35)
               at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:49)
               at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:266)
               at com.samples.prep.model.local.Organization.getUsers(Organization.java:47)
               at com.samples.prep.model.local.Organization_Adapter.loadFromCursor(Organization_Adapter.java:173)
               at com.samples.prep.model.local.Organization_Adapter.loadFromCursor(Organization_Adapter.java:24)
               at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:25)
               at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:32)
               at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:12)
               at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:69)
               at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:57)
               at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:51)
               at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:35)
               at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:56)
               at com.raizlabs.android.dbflow.sql.language.Where.querySingle(Where.java:285)
               at com.samples.prep.model.local.Users_Adapter.loadFromCursor(Users_Adapter.java:263)
               at com.samples.prep.model.local.Users_Adapter.loadFromCursor(Users_Adapter.java:25)
               at com.raizlabs.android.dbflow.sql.queriable.ListModelLoader.convertToData(ListModelLoader.java:33)
               at com.raizlabs.android.dbflow.sql.queriable.ListModelLoader.convertToData(ListModelLoader.java:15)
               at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:69)
               at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:57)
               at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:51)
               at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:35)
               at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:49)
               at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:266)
               at com.samples.prep.model.local.Organization.getUsers(Organization.java:47)
               at com.samples.prep.model.local.Organization_Adapter.loadFromCursor(Organization_Adapter.java:173)
               at com.samples.prep.model.local.Organization_Adapter.loadFromCursor(Organization_Adapter.java:24)
               at com.raizlabs.android.dbflow.sql.queri
```

**Comment by agrosner** [comment]
I looks like you have a recursive reference occuring. In that `Organization` holds a strong reference to `User` and `User` holds a strong reference to `Organization`. If you define the `Organization` in `User` as a `ForeignKeyContainer`, it will work

**Comment by z-zghiba** [comment]
With `ForeignKeyContainer `  it gives me this : (I'm using `org.parceler:parceler:1.1.5`)

Error:(33, 40) error: Parceler: Unable to find read/write generator for type com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer<com.samples.prep.model.Users> for com.samples.prep.model.Users.user

**Comment by go4nishu** [comment]
@z-zghiba You found any solution for this issue? I am facing same problem in my project.

I am using DbFlow with parceler library. One of the fields in my model class is of type  ForeignKeyContainer. When i compile app below error comes up
Unable to find read/write generator for type com.test.ForeignKeyContainer
If i use @Transient annotation before the field app complies fine but some other issues popup while performing write operations in database. ForeignKey becomes null for the fileds marked Transient after performing save function. How can i enable parceler for ForeignKeyContainer field?

**Comment by agrosner** [comment]
`ForeignKeyContainer` field is no more in 4.0.0-beta1 +, using `stubbedRelationship` then this would fix the issues here I believe.

**Comment by therajanmaurya** [comment]
@agrosner ```stubbedRelationship``` is not resolving issue, It's adding java object recursively that making  ```Out of Memory``` issue.
