### ISSUE TITLE
Jack compiler && annotation processor

### ISSUE THREAD

**Issue by sshutl** [Raizlabs/DBFlow#888]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature):Bug
Description: 
Can't use with Jack compiler:
annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
instead of
apt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
incremental compilation is off.

**Comment by agrosner** [comment]
need more information.

**Comment by sshutl** [comment]
https://github.com/nickwph/annotation-processor-with-java8-jack-and-jill-android

**Comment by matpag** [comment]
i have the same problem, not able to build the project if Jack is enabled.

**Comment by sshutl** [comment]
for examle like that: 
Error:/home/myusername/Projects/project-name/module-name/build/generated/source/apt/mobile/debug/package com/mycompany/model/Measurement_Adapter.java:44: Measurement_Table cannot be resolved
Maybe the issue is a space symbol between path and package/Class ?

**Comment by matpag** [comment]
i think we need the help of @agrosner to solve this when he has time to invest on this

**Comment by aliusa** [comment]
Ok, recently I issued issue in Android OS project with same error as @matpag thinking it's Jack error:
`Error:Execution failed for task ':app:transformJackWithJackForDebug'.
com.android.jack.ir.JNodeInternalError: java.lang.Exception: java.lang.NullPointerException: element == null`

And google developer said that I'ts DBFlow error [link](https://code.google.com/p/android/issues/detail?id=223288#c9)

`Apparently the bug is in DBFlow.`
`There seems to be a misuse of javax.lang.model.util.Elements.getTypeElement(CharSequence name), where 'name' passed by DBFlow have generics type parameters whereas it shouldn't.`
`So getTypeElement() returns 'null' hence the NullPointerException.`

**Comment by papauschek** [comment]
+1

**Comment by agrosner** [comment]
it looks like you have a generic parameter in the `TypeConverter`. dont specify a class that has generic parameters and this is fixed.

**Comment by vinaysshenoy** [comment]
@agrosner I am facing a similar issue when using `jack` as well, and I am not using any generic types. I don't think this is an issue with generic types.

My model class is
````java
import com.raizlabs.android.dbflow.annotation.Column;
import com.raizlabs.android.dbflow.annotation.NotNull;
import com.raizlabs.android.dbflow.annotation.PrimaryKey;
import com.raizlabs.android.dbflow.annotation.Table;
import com.raizlabs.android.dbflow.structure.BaseModel;

import java.util.Date;

@Table(database = DbFlowAppDatabase.class, name = "NOTES")
public class DbFlowNote extends BaseModel {

    @PrimaryKey
    @Column(name = "id")
    String id;

    @NotNull
    @Column(name = "text")
    String text;

    @NotNull
    @Column(name = "created")
    Date created;

    public String id() {
        return id;
    }

    public String text() {
        return text;
    }

    public Date created() {
        return created;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setText(String text) {
        this.text = text;
    }

    public void setCreated(Date created) {
        this.created = created;
    }
}
````

The exact exception thrown is
````
Caused by: java.lang.NullPointerException: element == null
        at com.squareup.javapoet.Util.checkNotNull(Util.java:68)
        at com.squareup.javapoet.ClassName.get(ClassName.java:182)
        at com.raizlabs.android.dbflow.processor.definition.column.ColumnDefinition.<init>(ColumnDefinition.java:175)
        at com.raizlabs.android.dbflow.processor.definition.column.ColumnDefinition.<init>(ColumnDefinition.java:232)
        at com.raizlabs.android.dbflow.processor.definition.TableDefinition.createColumnDefinitions(TableDefinition.java:360)
        at com.raizlabs.android.dbflow.processor.definition.TableDefinition.prepareForWrite(TableDefinition.java:266)
        at com.raizlabs.android.dbflow.processor.definition.method.DatabaseDefinition.prepareDefinitions(DatabaseDefinition.java:153)
        at com.raizlabs.android.dbflow.processor.definition.method.DatabaseDefinition.validateAndPrepareToWrite(DatabaseDefinition.java:125)
        at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:326)
        at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:98)
        at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
        ... 93 more

````

I'm currently using DbFlow version 3.1.1.

**Comment by papauschek** [comment]
Yes it's not an issue with generic types. Please reopen this.

**Comment by dudadayan** [comment]
+1

**Comment by chaleao** [comment]
+1

**Comment by agrosner** [comment]
in `develop`.
