### ISSUE TITLE
Table Not Found

### ISSUE THREAD

**Issue by therajanmaurya** [Raizlabs/DBFlow#889]
```java
Process: com.mifos.mifosxdroid, PID: 8150
android.database.sqlite.SQLiteException: no such table: ClientAccounts (code 1): , while compiling: INSERT INTO `ClientAccounts`(`id`) VALUES (NULL)
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:994)
at com.raizlabs.android.dbflow.structure.database.AndroidDatabase.compileStatement(AndroidDatabase.java:59)
at com.raizlabs.android.dbflow.structure.ModelAdapter.getInsertStatement(ModelAdapter.java:64)
at com.raizlabs.android.dbflow.structure.ModelAdapter.getInsertStatement(ModelAdapter.java:51)
at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:40)
at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:102)
at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:51)
at com.mifos.api.local.databasehelper.DatabaseHelperClient$4.run(DatabaseHelperClient.java:99)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

I am writing DatabaseHelper layer of my application. Whenever I annotating the new Model for saving data and run it says this table is not found. 
How can fix this

**Comment by agrosner** [comment]
`Whenever I annotating the new Model for saving data and run it says this table is not found. ` Its called [Migrations](https://github.com/Raizlabs/DBFlow/blob/master/usage2/Migrations.md).

**Comment by fakefacebook** [comment]
@agrosner  i have same issue ..  wt can i do for that?
