### ISSUE TITLE
Failed to open file FileNotFoundException

### ISSUE THREAD

**Issue by Pedramrn** [Raizlabs/DBFlow#920]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question):

Description: 

When starting the app for the first time I get this warning and error message, though everything working fine.

```
4650-4650 W/FlowLog: Failed to open file
                     java.io.FileNotFoundException: weather_db.db
                         at android.content.res.AssetManager.openAsset(Native Method)
                         at android.content.res.AssetManager.open(AssetManager.java:313)
                         at android.content.res.AssetManager.open(AssetManager.java:287)
                         at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.movePrepackagedDB(DatabaseHelperDelegate.java:127)
                         at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.performRestoreFromBackup(DatabaseHelperDelegate.java:44)
                         at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.performRestoreFromBackup(FlowSQLiteOpenHelper.java:33)
                         at com.raizlabs.android.dbflow.config.DatabaseDefinition.getHelper(DatabaseDefinition.java:216)
                         at com.raizlabs.android.dbflow.config.DatabaseDefinition.getWritableDatabase(DatabaseDefinition.java:222)
                         at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.getWritableDatabase(ModelSaver.java:135)
                         at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:40)
                         at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:103)
                         at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:51)
                         at com.example.MyApplication.onCreate(WeatherApplication.java:92)
                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
                         at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                         at android.os.Handler.dispatchMessage(Handler.java:102)
                         at android.os.Looper.loop(Looper.java:135)
                         at android.app.ActivityThread.main(ActivityThread.java:5254)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at java.lang.reflect.Method.invoke(Method.java:372)
                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
4650-4650 E/FlowLog: java.io.FileNotFoundException: weather_db.db
                         at android.content.res.AssetManager.openAsset(Native Method)
                         at android.content.res.AssetManager.open(AssetManager.java:313)
                         at android.content.res.AssetManager.open(AssetManager.java:287)
                         at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.restoreDatabase(DatabaseHelperDelegate.java:251)
                         at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.performRestoreFromBackup(DatabaseHelperDelegate.java:52)
                         at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.performRestoreFromBackup(FlowSQLiteOpenHelper.java:33)
                         at com.raizlabs.android.dbflow.config.DatabaseDefinition.getHelper(DatabaseDefinition.java:216)
                         at com.raizlabs.android.dbflow.config.DatabaseDefinition.getWritableDatabase(DatabaseDefinition.java:222)
                         at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.getWritableDatabase(ModelSaver.java:135)
                         at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:40)
                         at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:103)
                         at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:51)
                         at com.example.MyApplication.onCreate(WeatherApplication.java:92)
                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
                         at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                         at android.os.Handler.dispatchMessage(Handler.java:102)
                         at android.os.Looper.loop(Looper.java:135)
                         at android.app.ActivityThread.main(ActivityThread.java:5254)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at java.lang.reflect.Method.invoke(Method.java:372)
                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```

Config:

```java
@Override
public void onCreate() {
    super.onCreate();
    FlowManager.init(new FlowConfig.Builder(getApplicationContext())
                             .addDatabaseHolder(DatabaseWeatherGeneratedDatabaseHolder.class)
                             .build());
    FlowLog.setMinimumLoggingLevel(FlowLog.Level.W);
```

```groovy
apt {
    arguments {
        targetModuleName 'DatabaseWeather'
    }
}
```

**Comment by agrosner** [comment]
looks like your asset is not found as in the backup db file. if its a warning this is not a bug.
