### ISSUE TITLE
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: NewMessage.type (code 1555)

### ISSUE THREAD

**Issue by taoweiji** [Raizlabs/DBFlow#923]
DBFlow Version:3.1.1
Issue Kind (Bug, Question, Feature): Bug

Description: 
```
@ModelContainer
@Table(database = AppDatabase.class)
public class NewMessage extends BaseModel  implements Serializable {
	public NewMessage(){

	}
	public NewMessage(int type, long servertime,long localtime) {
		this.type = type;
		this.servertime = servertime;
		this.localtime = localtime;
	}

	@CustomColumn
	@PrimaryKey
	private int type;
	@CustomColumn
	@Column
	private long localtime;

	@CustomColumn
	@Column
	private long servertime;

	public long getLocaltime() {
		return localtime;
	}

	public void setLocaltime(long localtime) {
		this.localtime = localtime;
	}

	public long getServertime() {
		return servertime;
	}

	public void setServertime(long servertime) {
		this.servertime = servertime;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}


	public static NewMessage obtion(int type){
		return new NewMessage(type,System.currentTimeMillis(),System.currentTimeMillis());
	}
}
```

```
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: NewMessage.type (code 1555)
at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:952)
at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.executeInsert(AndroidDatabaseStatement.java:77)
at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.insert(ModelSaver.java:110)
at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:57)
at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:40)
at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:103)
at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:51)
at co.runner.app.util.MessageManager$4.run(MessageManager.java:198)
at co.runner.app.utils.ThreadManager$SafeRunnable.run(ThreadManager.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by agrosner** [comment]
Looks like a sqlite issue to me.

**Comment by agrosner** [comment]
Well not issue with SQLite, but its a UNIQUE constraint failing which is expected. Looks like you're trying to insert `type` into the DB with a value that already exists.

**Comment by mhswtf** [comment]
This happened to me if the inserted value had a leading whitespace. When i removed the whitespace, the problem disappeared.
