### ISSUE TITLE
Bug (NPE) creating trigger

### ISSUE THREAD

**Issue by WarrenFaith** [Raizlabs/DBFlow#935]
DBFlow Version: 3.1.1
Issue Kind: Bug
Instant Run is off

Description: 

We are creating a trigger to limit the amount of rows inserted in a table.
We have this order of code execution:

Inside our Application class:

```
FlowManager.init(new FlowConfig.Builder(sContext)
                    .addDatabaseConfig(createDatabaseConfig())
                    .build());
```
which calls
```
private static DatabaseConfig createDatabaseConfig() {
    return new DatabaseConfig.Builder(AppDatabase.class)
                .helperListener(createDatabaseHelperListener())
                .openHelper(new OurDbOpenHelperCreator())
                .build();
}
```
That is our basic setup for DBFlow. Afterwards we create the trigger:
```
private static void enableLimitTrigger() {
    CompletedTrigger<Table> trigger = Trigger.create(TABLE_LIMITATION_TRIGGER_NAME)
            .after().insert(Table.class)
            .begin(getTriggerLogicQuery(Table.class, Table.COLUMN_ID));
    trigger.enable();
}
```
where getTriggerLogicQuery is

```
private static StringQuery getTriggerLogicQuery(@NonNull final Class<? extends BaseModel> cls, @NonNull String idColumnName) {
    if (TextUtils.isEmpty(idColumnName)) {
        idColumnName = "ROWID";
    }
    String tableName = FlowManager.getTableName(cls);
    return new StringQuery<>(cls, "DELETE FROM " + tableName + " WHERE " + idColumnName + " NOT IN " +
                "(SELECT " + idColumnName + " FROM " + tableName + " ORDER BY " + idColumnName + " DESC LIMIT " + DB_ROW_LIMIT + ")");
}
```

That causes the following crash (from developer console, by a Xperia Z4 Tablet, we couldn't reproduce that on our devices):
```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.raizlabs.android.dbflow.sql.language.SQLCondition.appendConditionToQuery(com.raizlabs.android.dbflow.sql.QueryBuilder)' on a null object reference
at com.raizlabs.android.dbflow.sql.language.ConditionGroup.getQuery(ConditionGroup.java:209)
at com.raizlabs.android.dbflow.sql.language.Where.getQuery(Where.java:221)
at com.raizlabs.android.dbflow.sql.language.Where.query(Where.java:242)
at com.raizlabs.android.dbflow.sql.language.BaseQueriable.execute(BaseQueriable.java:96)
at com.raizlabs.android.dbflow.sql.migration.UpdateTableMigration.migrate(UpdateTableMigration.java:69)
at com.raizlabs.android.dbflow.structure.database.BaseDatabaseHelper.executeMigrations(BaseDatabaseHelper.java:158)
at com.raizlabs.android.dbflow.structure.database.BaseDatabaseHelper.onUpgrade(BaseDatabaseHelper.java:53)
at com.raizlabs.android.dbflow.structure.database.DatabaseHelperDelegate.onUpgrade(DatabaseHelperDelegate.java:78)
at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.onUpgrade(FlowSQLiteOpenHelper.java:76)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
at com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.getDatabase(FlowSQLiteOpenHelper.java:54)
at com.raizlabs.android.dbflow.config.DatabaseDefinition.getWritableDatabase(DatabaseDefinition.java:222)
at com.raizlabs.android.dbflow.sql.trigger.CompletedTrigger.enable(CompletedTrigger.java:45)
at com.example.package.database.DatabaseHelper.enableCallLimitTrigger(DatabaseHelper.java:532)
```

We checked that ConditionGroup:209 is
```
208: SQLCondition condition = conditionsList.get(i);
209: condition.appendConditionToQuery(query);
```

We guess that ```conditionsList``` might contain null references but we fail to see why and how that can happen.

So we guess that this is somehow a bug on your side. If not so we appreciate any feedback or suggestion you can give us.

**Comment by agrosner** [comment]
Might be that `toString` calculates the `getQuery()` method. Ive split that up and made them separate for 4.0.0-beta1, reopen when released if still happening. in `develop`.
